import type { Locale } from '@/lib/i18n';
import { LOCALES, LOCALE_METADATA } from '@/lib/i18n';
import type { ToolConfig } from '@/config/tools';
import type { LocalizedToolSeo, ToolManifest } from './tool-manifest';

const CORE: Record<Locale, {
  online: string;
  intro: string;
  step1: string;
  step2: string;
  step3: string;
  step4: string;
  features: string[];
  alt: string;
}> = {
  en: { online: 'Online tool', intro: 'Use FLIXO’s {title} directly in your browser with a fast, privacy-first workflow.', step1: 'Open the tool and choose your input.', step2: 'Adjust the available options for the desired output.', step3: 'Run the tool and review the result in your browser.', step4: 'Download or copy the finished result.', features: ['Browser-first processing', 'No account required', 'Fast local workflow'], alt: '{title} interface in FLIXO' },
  ar: { online: 'أداة عبر الإنترنت', intro: 'استخدم {title} من FLIXO مباشرة داخل المتصفح مع تجربة سريعة وتركّز على الخصوصية.', step1: 'افتح الأداة واختر المدخلات المطلوبة.', step2: 'اضبط الخيارات المتاحة للحصول على النتيجة المطلوبة.', step3: 'شغّل الأداة وراجع النتيجة داخل المتصفح.', step4: 'نزّل النتيجة النهائية أو انسخها.', features: ['معالجة أولًا داخل المتصفح', 'بدون حساب', 'سير عمل محلي سريع'], alt: 'واجهة {title} في FLIXO' },
  es: { online: 'Herramienta en línea', intro: 'Usa {title} de FLIXO directamente en tu navegador con un flujo rápido y centrado en la privacidad.', step1: 'Abre la herramienta y elige la entrada.', step2: 'Ajusta las opciones disponibles.', step3: 'Ejecuta la herramienta y revisa el resultado.', step4: 'Descarga o copia el resultado final.', features: ['Procesamiento en el navegador', 'Sin cuenta', 'Flujo local rápido'], alt: 'Interfaz de {title} en FLIXO' },
  fr: { online: 'Outil en ligne', intro: 'Utilisez {title} de FLIXO directement dans votre navigateur avec un flux rapide et axé sur la confidentialité.', step1: 'Ouvrez l’outil et choisissez l’entrée.', step2: 'Réglez les options disponibles.', step3: 'Lancez l’outil et vérifiez le résultat.', step4: 'Téléchargez ou copiez le résultat final.', features: ['Traitement dans le navigateur', 'Sans compte', 'Flux local rapide'], alt: 'Interface {title} dans FLIXO' },
  de: { online: 'Online-Tool', intro: 'Nutzen Sie {title} von FLIXO direkt im Browser mit einem schnellen, datenschutzorientierten Ablauf.', step1: 'Öffnen Sie das Tool und wählen Sie die Eingabe.', step2: 'Passen Sie die verfügbaren Optionen an.', step3: 'Starten Sie das Tool und prüfen Sie das Ergebnis.', step4: 'Laden Sie das Ergebnis herunter oder kopieren Sie es.', features: ['Verarbeitung im Browser', 'Kein Konto erforderlich', 'Schneller lokaler Ablauf'], alt: '{title}-Oberfläche in FLIXO' },
  ru: { online: 'Онлайн-инструмент', intro: 'Используйте {title} от FLIXO прямо в браузере с быстрым и ориентированным на приватность процессом.', step1: 'Откройте инструмент и выберите входные данные.', step2: 'Настройте доступные параметры.', step3: 'Запустите инструмент и проверьте результат.', step4: 'Скачайте или скопируйте готовый результат.', features: ['Обработка в браузере', 'Без аккаунта', 'Быстрый локальный процесс'], alt: 'Интерфейс {title} в FLIXO' },
  zh: { online: '在线工具', intro: '直接在浏览器中使用 FLIXO 的 {title}，体验快速且注重隐私的工作流程。', step1: '打开工具并选择输入内容。', step2: '调整可用选项以获得所需输出。', step3: '运行工具并在浏览器中查看结果。', step4: '下载或复制最终结果。', features: ['浏览器本地处理', '无需账号', '快速本地工作流'], alt: 'FLIXO 中的 {title} 界面' },
  hi: { online: 'ऑनलाइन टूल', intro: 'तेज़ और गोपनीयता-केंद्रित अनुभव के साथ सीधे ब्राउज़र में FLIXO का {title} इस्तेमाल करें।', step1: 'टूल खोलें और इनपुट चुनें।', step2: 'आवश्यक आउटपुट के लिए विकल्प समायोजित करें।', step3: 'टूल चलाएँ और परिणाम देखें।', step4: 'अंतिम परिणाम डाउनलोड या कॉपी करें।', features: ['ब्राउज़र-आधारित प्रोसेसिंग', 'खाते की आवश्यकता नहीं', 'तेज़ लोकल वर्कफ़्लो'], alt: 'FLIXO में {title} इंटरफ़ेस' },
  id: { online: 'Alat online', intro: 'Gunakan {title} dari FLIXO langsung di browser dengan alur cepat yang mengutamakan privasi.', step1: 'Buka alat dan pilih input.', step2: 'Sesuaikan opsi yang tersedia.', step3: 'Jalankan alat dan periksa hasilnya.', step4: 'Unduh atau salin hasil akhir.', features: ['Pemrosesan di browser', 'Tanpa akun', 'Alur lokal cepat'], alt: 'Antarmuka {title} di FLIXO' },
  ur: { online: 'آن لائن ٹول', intro: 'تیز اور پرائیویسی پر مبنی ورک فلو کے ساتھ FLIXO کا {title} براہِ راست براؤزر میں استعمال کریں۔', step1: 'ٹول کھولیں اور ان پٹ منتخب کریں۔', step2: 'مطلوبہ نتیجے کے لیے دستیاب اختیارات ترتیب دیں۔', step3: 'ٹول چلائیں اور نتیجہ دیکھیں۔', step4: 'حتمی نتیجہ ڈاؤن لوڈ یا کاپی کریں۔', features: ['براؤزر میں پراسیسنگ', 'اکاؤنٹ کی ضرورت نہیں', 'تیز مقامی ورک فلو'], alt: 'FLIXO میں {title} کا انٹرفیس' },
  ja: { online: 'オンラインツール', intro: '高速でプライバシーを重視したワークフローで、FLIXO の {title} をブラウザから直接利用できます。', step1: 'ツールを開いて入力を選択します。', step2: '必要な出力に合わせて設定を調整します。', step3: 'ツールを実行して結果を確認します。', step4: '完成した結果をダウンロードまたはコピーします。', features: ['ブラウザ内処理', 'アカウント不要', '高速なローカル処理'], alt: 'FLIXO の {title} インターフェース' },
  pt: { online: 'Ferramenta online', intro: 'Use o {title} da FLIXO diretamente no navegador com um fluxo rápido e focado em privacidade.', step1: 'Abra a ferramenta e escolha a entrada.', step2: 'Ajuste as opções disponíveis.', step3: 'Execute a ferramenta e confira o resultado.', step4: 'Baixe ou copie o resultado final.', features: ['Processamento no navegador', 'Sem conta', 'Fluxo local rápido'], alt: 'Interface de {title} no FLIXO' },
  it: { online: 'Strumento online', intro: 'Usa {title} di FLIXO direttamente nel browser con un flusso rapido e attento alla privacy.', step1: 'Apri lo strumento e scegli l’input.', step2: 'Regola le opzioni disponibili.', step3: 'Esegui lo strumento e controlla il risultato.', step4: 'Scarica o copia il risultato finale.', features: ['Elaborazione nel browser', 'Nessun account', 'Flusso locale rapido'], alt: 'Interfaccia {title} in FLIXO' },
  ko: { online: '온라인 도구', intro: '빠르고 개인정보 보호를 우선하는 작업 흐름으로 브라우저에서 FLIXO의 {title}을(를) 바로 사용하세요.', step1: '도구를 열고 입력을 선택합니다.', step2: '원하는 결과에 맞게 옵션을 조정합니다.', step3: '도구를 실행하고 결과를 확인합니다.', step4: '완성된 결과를 다운로드하거나 복사합니다.', features: ['브라우저 내 처리', '계정 불필요', '빠른 로컬 작업 흐름'], alt: 'FLIXO의 {title} 인터페이스' },
  nl: { online: 'Online tool', intro: 'Gebruik {title} van FLIXO direct in je browser met een snelle workflow die privacy vooropstelt.', step1: 'Open de tool en kies invoer.', step2: 'Pas de beschikbare opties aan.', step3: 'Voer de tool uit en controleer het resultaat.', step4: 'Download of kopieer het eindresultaat.', features: ['Verwerking in de browser', 'Geen account', 'Snelle lokale workflow'], alt: '{title}-interface in FLIXO' },
  pl: { online: 'Narzędzie online', intro: 'Używaj {title} FLIXO bezpośrednio w przeglądarce, korzystając z szybkiego przepływu pracy z naciskiem na prywatność.', step1: 'Otwórz narzędzie i wybierz dane wejściowe.', step2: 'Dostosuj dostępne opcje.', step3: 'Uruchom narzędzie i sprawdź wynik.', step4: 'Pobierz lub skopiuj gotowy wynik.', features: ['Przetwarzanie w przeglądarce', 'Bez konta', 'Szybki lokalny przepływ pracy'], alt: 'Interfejs {title} w FLIXO' },
  tr: { online: 'Çevrimiçi araç', intro: 'Hızlı ve gizlilik odaklı bir iş akışıyla FLIXO {title} aracını doğrudan tarayıcıda kullanın.', step1: 'Aracı açın ve girdiyi seçin.', step2: 'Kullanılabilir seçenekleri ayarlayın.', step3: 'Aracı çalıştırın ve sonucu inceleyin.', step4: 'Sonucu indirin veya kopyalayın.', features: ['Tarayıcıda işleme', 'Hesap gerekmez', 'Hızlı yerel iş akışı'], alt: 'FLIXO {title} arayüzü' },
  vi: { online: 'Công cụ trực tuyến', intro: 'Sử dụng {title} của FLIXO ngay trong trình duyệt với quy trình nhanh và ưu tiên quyền riêng tư.', step1: 'Mở công cụ và chọn dữ liệu đầu vào.', step2: 'Điều chỉnh các tùy chọn cần thiết.', step3: 'Chạy công cụ và kiểm tra kết quả.', step4: 'Tải xuống hoặc sao chép kết quả cuối cùng.', features: ['Xử lý ngay trong trình duyệt', 'Không cần tài khoản', 'Quy trình cục bộ nhanh'], alt: 'Giao diện {title} trong FLIXO' },
  th: { online: 'เครื่องมือออนไลน์', intro: 'ใช้ {title} ของ FLIXO ได้โดยตรงในเบราว์เซอร์ พร้อมขั้นตอนการทำงานที่รวดเร็วและเน้นความเป็นส่วนตัว', step1: 'เปิดเครื่องมือและเลือกข้อมูลนำเข้า', step2: 'ปรับตัวเลือกตามผลลัพธ์ที่ต้องการ', step3: 'เรียกใช้เครื่องมือและตรวจสอบผลลัพธ์', step4: 'ดาวน์โหลดหรือคัดลอกผลลัพธ์', features: ['ประมวลผลในเบราว์เซอร์', 'ไม่ต้องมีบัญชี', 'เวิร์กโฟลว์ภายในเครื่องที่รวดเร็ว'], alt: 'อินเทอร์เฟซ {title} ใน FLIXO' },
  sv: { online: 'Onlineverktyg', intro: 'Använd FLIXO:s {title} direkt i webbläsaren med ett snabbt arbetsflöde som prioriterar integritet.', step1: 'Öppna verktyget och välj indata.', step2: 'Justera tillgängliga alternativ.', step3: 'Kör verktyget och granska resultatet.', step4: 'Ladda ner eller kopiera det färdiga resultatet.', features: ['Bearbetning i webbläsaren', 'Inget konto krävs', 'Snabbt lokalt arbetsflöde'], alt: '{title}-gränssnitt i FLIXO' },
};

const TERM_MAPS: Record<Locale, Record<string, string>> = {
  en: {},
  ar: { Image:'الصور', PDF:'PDF', Compressor:'ضغط', Background:'الخلفية', Remover:'إزالة', Upscaler:'رفع الدقة', Converter:'تحويل', Merger:'دمج', Splitter:'تقسيم', Unlock:'فك القفل', Protect:'حماية', Text:'النص', Word:'الكلمات', Character:'الأحرف', Counter:'عداد', Diff:'فروقات', Checker:'فاحص', Case:'حالة الأحرف', QR:'QR', Code:'رمز', Generator:'مولد', Reader:'قارئ', Password:'كلمة المرور', Aspect:'نسبة', Ratio:'الأبعاد', Calculator:'حاسبة', JSON:'JSON', Formatter:'منسق', Validator:'مدقق', Base64:'Base64', Encoder:'مشفّر', Decoder:'فك التشفير', Color:'الألوان', Picker:'منتقي', Palette:'لوحة', Video:'فيديو', Trimmer:'تشذيب', Audio:'صوت', Extractor:'استخراج', Muter:'كتم', GIF:'GIF', Meme:'ميم', Maker:'منشئ', AI:'ذكاء اصطناعي', Captioner:'التعليقات التلقائية', SRT:'SRT', Cutter:'قص', Vocal:'صوتي', Instrumental:'موسيقي', Noise:'ضوضاء', Reducer:'تقليل', Regex:'Regex', Tester:'اختبار', Debugger:'تصحيح', Hash:'تجزئة', Object:'كائن', Watermark:'علامة مائية', Cropper:'قصاص', SVG:'SVG', OCR:'OCR', Passport:'جواز السفر', Adder:'إضافة', Collage:'كولاج', Effects:'تأثيرات', Cleaner:'منظف', Optimizer:'محسّن', Mockup:'نموذج', Studio:'استوديو', Seed:'Seed' },
  es: { Image:'Imagen', PDF:'PDF', Compressor:'Compresor', Background:'Fondo', Remover:'Eliminador', Upscaler:'Escalador', Converter:'Convertidor', Merger:'Unidor', Splitter:'Divisor', Unlock:'Desbloqueo', Protect:'Protección', Text:'Texto', Word:'Palabras', Character:'Caracteres', Counter:'Contador', Diff:'Diferencias', Checker:'Comprobador', Case:'Mayúsculas y minúsculas', QR:'QR', Code:'Código', Generator:'Generador', Reader:'Lector', Password:'Contraseñas', Aspect:'Relación', Ratio:'de aspecto', Calculator:'Calculadora', JSON:'JSON', Formatter:'Formateador', Validator:'Validador', Base64:'Base64', Encoder:'Codificador', Decoder:'Decodificador', Color:'Color', Picker:'Selector', Palette:'Paleta', Video:'Vídeo', Trimmer:'Recortador', Audio:'Audio', Extractor:'Extractor', Muter:'Silenciador', GIF:'GIF', Meme:'Memes', Maker:'Creador', AI:'IA', Captioner:'Subtítulos', SRT:'SRT', Cutter:'Cortador', Vocal:'Vocal', Instrumental:'Instrumental', Noise:'Ruido', Reducer:'Reductor', Regex:'Regex', Tester:'Probador', Debugger:'Depurador', Hash:'Hash', Object:'Objetos', Watermark:'Marca de agua', Cropper:'Recortador', SVG:'SVG', OCR:'OCR', Passport:'Pasaporte', Adder:'Añadidor', Collage:'Collage', Effects:'Efectos', Cleaner:'Limpiador', Optimizer:'Optimizador', Mockup:'Mockup', Studio:'Estudio', Seed:'Seed' },
  fr: { Image:'Image', PDF:'PDF', Compressor:'Compresseur', Background:'Arrière-plan', Remover:'Suppresseur', Upscaler:'Améliorateur', Converter:'Convertisseur', Merger:'Fusionneur', Splitter:'Séparateur', Unlock:'Déverrouillage', Protect:'Protection', Text:'Texte', Word:'Mots', Character:'Caractères', Counter:'Compteur', Diff:'Différences', Checker:'Vérificateur', Case:'Casse', QR:'QR', Code:'Code', Generator:'Générateur', Reader:'Lecteur', Password:'Mot de passe', Aspect:'Rapport', Ratio:'d’aspect', Calculator:'Calculateur', JSON:'JSON', Formatter:'Formateur', Validator:'Validateur', Base64:'Base64', Encoder:'Encodeur', Decoder:'Décodeur', Color:'Couleur', Picker:'Sélecteur', Palette:'Palette', Video:'Vidéo', Trimmer:'Rogneur', Audio:'Audio', Extractor:'Extracteur', Muter:'Sourdine', GIF:'GIF', Meme:'Mème', Maker:'Créateur', AI:'IA', Captioner:'Sous-titrage', SRT:'SRT', Cutter:'Découpeur', Vocal:'Vocal', Instrumental:'Instrumental', Noise:'Bruit', Reducer:'Réducteur', Regex:'Regex', Tester:'Testeur', Debugger:'Débogueur', Hash:'Hash', Object:'Objet', Watermark:'Filigrane', Cropper:'Recadrage', SVG:'SVG', OCR:'OCR', Passport:'Passeport', Adder:'Ajout', Collage:'Collage', Effects:'Effets', Cleaner:'Nettoyeur', Optimizer:'Optimiseur', Mockup:'Maquette', Studio:'Studio', Seed:'Seed' },
  de: { Image:'Bild', PDF:'PDF', Compressor:'Kompressor', Background:'Hintergrund', Remover:'Entferner', Upscaler:'Hochskalierer', Converter:'Konverter', Merger:'Zusammenführen', Splitter:'Teiler', Unlock:'Entsperren', Protect:'Schutz', Text:'Text', Word:'Wörter', Character:'Zeichen', Counter:'Zähler', Diff:'Differenz', Checker:'Prüfer', Case:'Groß-/Kleinschreibung', QR:'QR', Code:'Code', Generator:'Generator', Reader:'Leser', Password:'Passwort', Aspect:'Seitenverhältnis', Ratio:'Verhältnis', Calculator:'Rechner', JSON:'JSON', Formatter:'Formatierer', Validator:'Validator', Base64:'Base64', Encoder:'Encoder', Decoder:'Decoder', Color:'Farbe', Picker:'Auswahl', Palette:'Palette', Video:'Video', Trimmer:'Trimmer', Audio:'Audio', Extractor:'Extraktor', Muter:'Stummschaltung', GIF:'GIF', Meme:'Meme', Maker:'Ersteller', AI:'KI', Captioner:'Untertitel', SRT:'SRT', Cutter:'Schneider', Vocal:'Vokal', Instrumental:'Instrumental', Noise:'Rauschen', Reducer:'Reduzierer', Regex:'Regex', Tester:'Tester', Debugger:'Debugger', Hash:'Hash', Object:'Objekt', Watermark:'Wasserzeichen', Cropper:'Zuschneider', SVG:'SVG', OCR:'OCR', Passport:'Passfoto', Adder:'Hinzufügen', Collage:'Collage', Effects:'Effekte', Cleaner:'Reiniger', Optimizer:'Optimierer', Mockup:'Mockup', Studio:'Studio', Seed:'Seed' },
  ru: { Image:'Изображения', PDF:'PDF', Compressor:'Компрессор', Background:'Фон', Remover:'Удаление', Upscaler:'Апскейлер', Converter:'Конвертер', Merger:'Объединение', Splitter:'Разделитель', Unlock:'Разблокировка', Protect:'Защита', Text:'Текст', Word:'Слова', Character:'Символы', Counter:'Счётчик', Diff:'Различия', Checker:'Проверка', Case:'Регистр', QR:'QR', Code:'Код', Generator:'Генератор', Reader:'Чтение', Password:'Пароли', Aspect:'Соотношение', Ratio:'сторон', Calculator:'Калькулятор', JSON:'JSON', Formatter:'Форматирование', Validator:'Проверка', Base64:'Base64', Encoder:'Кодировщик', Decoder:'Декодировщик', Color:'Цвет', Picker:'Выбор', Palette:'Палитра', Video:'Видео', Trimmer:'Обрезка', Audio:'Аудио', Extractor:'Извлечение', Muter:'Отключение звука', GIF:'GIF', Meme:'Мемы', Maker:'Создатель', AI:'ИИ', Captioner:'Субтитры', SRT:'SRT', Cutter:'Обрезка', Vocal:'Вокал', Instrumental:'Инструментал', Noise:'Шум', Reducer:'Подавление', Regex:'Regex', Tester:'Тестер', Debugger:'Отладчик', Hash:'Хеш', Object:'Объект', Watermark:'Водяной знак', Cropper:'Кадрирование', SVG:'SVG', OCR:'OCR', Passport:'Паспорт', Adder:'Добавление', Collage:'Коллаж', Effects:'Эффекты', Cleaner:'Очистка', Optimizer:'Оптимизатор', Mockup:'Макет', Studio:'Студия', Seed:'Seed' },
  zh: { Image:'图像', PDF:'PDF', Compressor:'压缩器', Background:'背景', Remover:'移除器', Upscaler:'放大器', Converter:'转换器', Merger:'合并器', Splitter:'拆分器', Unlock:'解锁', Protect:'保护', Text:'文本', Word:'单词', Character:'字符', Counter:'计数器', Diff:'差异', Checker:'检查器', Case:'大小写', QR:'二维码', Code:'代码', Generator:'生成器', Reader:'读取器', Password:'密码', Aspect:'宽高比', Ratio:'比例', Calculator:'计算器', JSON:'JSON', Formatter:'格式化器', Validator:'验证器', Base64:'Base64', Encoder:'编码器', Decoder:'解码器', Color:'颜色', Picker:'取色器', Palette:'调色板', Video:'视频', Trimmer:'裁剪器', Audio:'音频', Extractor:'提取器', Muter:'静音器', GIF:'GIF', Meme:'表情包', Maker:'制作器', AI:'AI', Captioner:'字幕生成器', SRT:'SRT', Cutter:'剪切器', Vocal:'人声', Instrumental:'伴奏', Noise:'噪声', Reducer:'降噪器', Regex:'正则表达式', Tester:'测试器', Debugger:'调试器', Hash:'哈希', Object:'对象', Watermark:'水印', Cropper:'裁剪器', SVG:'SVG', OCR:'OCR', Passport:'证件照', Adder:'添加器', Collage:'拼图', Effects:'效果', Cleaner:'清理器', Optimizer:'优化器', Mockup:'样机', Studio:'工作室', Seed:'Seed' },
  hi: { Image:'इमेज', PDF:'PDF', Compressor:'कंप्रेसर', Background:'पृष्ठभूमि', Remover:'रिमूवर', Upscaler:'अपस्केलर', Converter:'कन्वर्टर', Merger:'मर्जर', Splitter:'स्प्लिटर', Unlock:'अनलॉक', Protect:'प्रोटेक्टर', Text:'टेक्स्ट', Word:'शब्द', Character:'अक्षर', Counter:'काउंटर', Diff:'डिफ', Checker:'चेकर', Case:'केस', QR:'QR', Code:'कोड', Generator:'जनरेटर', Reader:'रीडर', Password:'पासवर्ड', Aspect:'एस्पेक्ट', Ratio:'रेशियो', Calculator:'कैलकुलेटर', JSON:'JSON', Formatter:'फॉर्मेटर', Validator:'वैलिडेटर', Base64:'Base64', Encoder:'एन्कोडर', Decoder:'डिकोडर', Color:'रंग', Picker:'पिकर', Palette:'पैलेट', Video:'वीडियो', Trimmer:'ट्रिमर', Audio:'ऑडियो', Extractor:'एक्सट्रैक्टर', Muter:'म्यूटर', GIF:'GIF', Meme:'मीम', Maker:'मेकर', AI:'AI', Captioner:'कैप्शनर', SRT:'SRT', Cutter:'कटर', Vocal:'वोकल', Instrumental:'इंस्ट्रूमेंटल', Noise:'शोर', Reducer:'रिड्यूसर', Regex:'Regex', Tester:'टेे्ंटर', Debugger:'डिबगर', Hash:'हैश', Object:'ऑब्जेक्ट', Watermark:'वॉटरमार्क', Cropper:'क्रॉपर', SVG:'SVG', OCR:'OCR', Passport:'पासपोर्ट', Adder:'एडर', Collage:'कोलाज', Effects:'इफेक्ट्स', Cleaner:'क्लीनर', Optimizer:'ऑप्टिमाइज़र', Mockup:'मॉकअप', Studio:'स्टूडियो', Seed:'Seed' },
  id: { Image:'Gambar', PDF:'PDF', Compressor:'Kompresor', Background:'Latar', Remover:'Penghapus', Upscaler:'Peningkat resolusi', Converter:'Konverter', Merger:'Penggabung', Splitter:'Pemecah', Unlock:'Buka kunci', Protect:'Pelindung', Text:'Teks', Word:'Kata', Character:'Karakter', Counter:'Penghitung', Diff:'Perbedaan', Checker:'Pemeriksa', Case:'Huruf', QR:'QR', Code:'Kode', Generator:'Generator', Reader:'Pembaca', Password:'Kata sandi', Aspect:'Rasio', Ratio:'aspek', Calculator:'Kalkulator', JSON:'JSON', Formatter:'Pemformat', Validator:'Validator', Base64:'Base64', Encoder:'Enkoder', Decoder:'Dekoder', Color:'Warna', Picker:'Pemilih', Palette:'Palet', Video:'Video', Trimmer:'Pemangkas', Audio:'Audio', Extractor:'Ekstraktor', Muter:'Pembisuan', GIF:'GIF', Meme:'Meme', Maker:'Pembuat', AI:'AI', Captioner:'Pembuat teks', SRT:'SRT', Cutter:'Pemotong', Vocal:'Vokal', Instrumental:'Instrumental', Noise:'Derau', Reducer:'Peredam', Regex:'Regex', Tester:'Penguji', Debugger:'Debugger', Hash:'Hash', Object:'Objek', Watermark:'Tanda air', Cropper:'Pemangkas', SVG:'SVG', OCR:'OCR', Passport:'Paspor', Adder:'Penambah', Collage:'Kolase', Effects:'Efek', Cleaner:'Pembersih', Optimizer:'Pengoptimal', Mockup:'Mockup', Studio:'Studio', Seed:'Seed' },
  ur: { Image:'تصاویر', PDF:'PDF', Compressor:'کمپریسر', Background:'پس منظر', Remover:'ریموور', Upscaler:'اپ اسکیلر', Converter:'کنورٹر', Merger:'مرجر', Splitter:'اسپلٹر', Unlock:'ان لاکر', Protect:'محافظ', Text:'متن', Word:'الفاظ', Character:'حروف', Counter:'کاؤنٹر', Diff:'فرق', Checker:'چیکر', Case:'کیس', QR:'QR', Code:'کوڈ', Generator:'جنریٹر', Reader:'ریڈر', Password:'پاس ورڈ', Aspect:'تناسب', Ratio:'پہلو', Calculator:'کیلکولیٹر', JSON:'JSON', Formatter:'فارمیٹر', Validator:'ویلیڈیٹر', Base64:'Base64', Encoder:'انکوڈر', Decoder:'ڈیکوڈر', Color:'رنگ', Picker:'پکر', Palette:'پیلیٹ', Video:'ویڈیو', Trimmer:'ٹریمر', Audio:'آڈیو', Extractor:'ایکسٹریکٹر', Muter:'میوٹر', GIF:'GIF', Meme:'میم', Maker:'میکر', AI:'اے آئی', Captioner:'کیپشنر', SRT:'SRT', Cutter:'کٹر', Vocal:'آواز', Instrumental:'ساز', Noise:'شور', Reducer:'کم کرنے والا', Regex:'Regex', Tester:'ٹیسٹر', Debugger:'ڈیبگر', Hash:'ہیش', Object:'آبجیکٹ', Watermark:'واٹرمارک', Cropper:'کراپر', SVG:'SVG', OCR:'OCR', Passport:'پاسپورٹ', Adder:'ایڈر', Collage:'کولاژ', Effects:'اثرات', Cleaner:'کلینر', Optimizer:'آپٹمائزر', Mockup:'موک اپ', Studio:'اسٹوڈیو', Seed:'Seed' },
  ja: { Image:'画像', PDF:'PDF', Compressor:'圧縮', Background:'背景', Remover:'削除', Upscaler:'高画質化', Converter:'変換', Merger:'結合', Splitter:'分割', Unlock:'ロック解除', Protect:'保護', Text:'テキスト', Word:'単語', Character:'文字', Counter:'カウンター', Diff:'差分', Checker:'チェッカー', Case:'ケース', QR:'QRコード', Code:'コード', Generator:'ジェネレーター', Reader:'リーダー', Password:'パスワード', Aspect:'アスペクト', Ratio:'比率', Calculator:'計算機', JSON:'JSON', Formatter:'整形', Validator:'バリデーター', Base64:'Base64', Encoder:'エンコーダー', Decoder:'デコーダー', Color:'カラー', Picker:'ピッカー', Palette:'パレット', Video:'動画', Trimmer:'トリマー', Audio:'音声', Extractor:'抽出', Muter:'ミュート', GIF:'GIF', Meme:'ミーム', Maker:'メーカー', AI:'AI', Captioner:'字幕', SRT:'SRT', Cutter:'カッター', Vocal:'ボーカル', Instrumental:'インストゥルメンタル', Noise:'ノイズ', Reducer:'低減', Regex:'正規表現', Tester:'テスター', Debugger:'デバッガー', Hash:'ハッシュ', Object:'オブジェクト', Watermark:'透かし', Cropper:'トリミング', SVG:'SVG', OCR:'OCR', Passport:'証明写真', Adder:'追加', Collage:'コラージュ', Effects:'エフェクト', Cleaner:'クリーナー', Optimizer:'最適化', Mockup:'モックアップ', Studio:'スタジオ', Seed:'Seed' },
  pt: { Image:'Imagem', PDF:'PDF', Compressor:'Compressor', Background:'Fundo', Remover:'Removedor', Upscaler:'Upscaler', Converter:'Conversor', Merger:'Mesclador', Splitter:'Divisor', Unlock:'Desbloqueio', Protect:'Proteção', Text:'Texto', Word:'Palavras', Character:'Caracteres', Counter:'Contador', Diff:'Diferenças', Checker:'Verificador', Case:'Maiúsculas e minúsculas', QR:'QR', Code:'Código', Generator:'Gerador', Reader:'Leitor', Password:'Senha', Aspect:'Proporção', Ratio:'de aspecto', Calculator:'Calculadora', JSON:'JSON', Formatter:'Formatador', Validator:'Validador', Base64:'Base64', Encoder:'Codificador', Decoder:'Decodificador', Color:'Cor', Picker:'Seletor', Palette:'Paleta', Video:'Vídeo', Trimmer:'Cortador', Audio:'Áudio', Extractor:'Extrator', Muter:'Silenciador', GIF:'GIF', Meme:'Meme', Maker:'Criador', AI:'IA', Captioner:'Legendas', SRT:'SRT', Cutter:'Cortador', Vocal:'Vocal', Instrumental:'Instrumental', Noise:'Ruído', Reducer:'Redutor', Regex:'Regex', Tester:'Testador', Debugger:'Depurador', Hash:'Hash', Object:'Objeto', Watermark:'Marca d’água', Cropper:'Cortador', SVG:'SVG', OCR:'OCR', Passport:'Passaporte', Adder:'Adicionador', Collage:'Colagem', Effects:'Efeitos', Cleaner:'Limpador', Optimizer:'Otimizador', Mockup:'Mockup', Studio:'Estúdio', Seed:'Seed' },
  it: { Image:'Immagine', PDF:'PDF', Compressor:'Compressore', Background:'Sfondo', Remover:'Rimozione', Upscaler:'Upscaler', Converter:'Convertitore', Merger:'Unificatore', Splitter:'Divisore', Unlock:'Sblocco', Protect:'Protezione', Text:'Testo', Word:'Parole', Character:'Caratteri', Counter:'Contatore', Diff:'Differenze', Checker:'Controllore', Case:'Maiuscole/minuscole', QR:'QR', Code:'Codice', Generator:'Generatore', Reader:'Lettore', Password:'Password', Aspect:'Rapporto', Ratio:'proporzioni', Calculator:'Calcolatrice', JSON:'JSON', Formatter:'Formattatore', Validator:'Validatore', Base64:'Base64', Encoder:'Codificatore', Decoder:'Decodificatore', Color:'Colore', Picker:'Selettore', Palette:'Tavolozza', Video:'Video', Trimmer:'Ritagliatore', Audio:'Audio', Extractor:'Estrattore', Muter:'Muto', GIF:'GIF', Meme:'Meme', Maker:'Creatore', AI:'IA', Captioner:'Sottotitoli', SRT:'SRT', Cutter:'Taglierina', Vocal:'Voce', Instrumental:'Strumentale', Noise:'Rumore', Reducer:'Riduttore', Regex:'Regex', Tester:'Tester', Debugger:'Debugger', Hash:'Hash', Object:'Oggetto', Watermark:'Filigrana', Cropper:'Ritaglio', SVG:'SVG', OCR:'OCR', Passport:'Passaporto', Adder:'Aggiunta', Collage:'Collage', Effects:'Effetti', Cleaner:'Pulitore', Optimizer:'Ottimizzatore', Mockup:'Mockup', Studio:'Studio', Seed:'Seed' },
  ko: { Image:'이미지', PDF:'PDF', Compressor:'압축기', Background:'배경', Remover:'제거기', Upscaler:'업스케일러', Converter:'변환기', Merger:'병합기', Splitter:'분할기', Unlock:'잠금 해제', Protect:'보호', Text:'텍스트', Word:'단어', Character:'문자', Counter:'카운터', Diff:'차이', Checker:'검사기', Case:'대소문자', QR:'QR', Code:'코드', Generator:'생성기', Reader:'리더', Password:'비밀번호', Aspect:'가로세로', Ratio:'비율', Calculator:'계산기', JSON:'JSON', Formatter:'포매터', Validator:'검증기', Base64:'Base64', Encoder:'인코더', Decoder:'디코더', Color:'색상', Picker:'선택기', Palette:'팔레트', Video:'비디오', Trimmer:'트리머', Audio:'오디오', Extractor:'추출기', Muter:'음소거', GIF:'GIF', Meme:'밈', Maker:'제작기', AI:'AI', Captioner:'자막 생성기', SRT:'SRT', Cutter:'커터', Vocal:'보컬', Instrumental:'반주', Noise:'노이즈', Reducer:'감소기', Regex:'정규식', Tester:'테스터', Debugger:'디버거', Hash:'해시', Object:'객체', Watermark:'워터마크', Cropper:'크로퍼', SVG:'SVG', OCR:'OCR', Passport:'여권 사진', Adder:'추가', Collage:'콜라주', Effects:'효과', Cleaner:'정리기', Optimizer:'최적화', Mockup:'목업', Studio:'스튜디오', Seed:'Seed' },
  nl: { Image:'Afbeelding', PDF:'PDF', Compressor:'Compressor', Background:'Achtergrond', Remover:'Verwijderaar', Upscaler:'Upscaler', Converter:'Converter', Merger:'Samenvoeger', Splitter:'Splitsen', Unlock:'Ontgrendelen', Protect:'Beveiligen', Text:'Tekst', Word:'Woorden', Character:'Tekens', Counter:'Teller', Diff:'Verschillen', Checker:'Controleur', Case:'Hoofdletters', QR:'QR', Code:'Code', Generator:'Generator', Reader:'Lezer', Password:'Wachtwoord', Aspect:'Beeldverhouding', Ratio:'Verhouding', Calculator:'Rekenmachine', JSON:'JSON', Formatter:'Formatter', Validator:'Validator', Base64:'Base64', Encoder:'Encoder', Decoder:'Decoder', Color:'Kleur', Picker:'Kiezer', Palette:'Palet', Video:'Video', Trimmer:'Trimmer', Audio:'Audio', Extractor:'Extractor', Muter:'Demper', GIF:'GIF', Meme:'Meme', Maker:'Maker', AI:'AI', Captioner:'Ondertitels', SRT:'SRT', Cutter:'Snijder', Vocal:'Zang', Instrumental:'Instrumentaal', Noise:'Ruis', Reducer:'Verminderaar', Regex:'Regex', Tester:'Tester', Debugger:'Debugger', Hash:'Hash', Object:'Object', Watermark:'Watermerk', Cropper:'Bijsnijder', SVG:'SVG', OCR:'OCR', Passport:'Pasfoto', Adder:'Toevoegen', Collage:'Collage', Effects:'Effecten', Cleaner:'Opschoner', Optimizer:'Optimizer', Mockup:'Mockup', Studio:'Studio', Seed:'Seed' },
  pl: { Image:'Obraz', PDF:'PDF', Compressor:'Kompresor', Background:'Tło', Remover:'Usuwanie', Upscaler:'Skalowanie', Converter:'Konwerter', Merger:'Scalacz', Splitter:'Dzielnik', Unlock:'Odblokowanie', Protect:'Ochrona', Text:'Tekst', Word:'Słowa', Character:'Znaki', Counter:'Licznik', Diff:'Różnice', Checker:'Sprawdzacz', Case:'Wielkość liter', QR:'QR', Code:'Kod', Generator:'Generator', Reader:'Czytnik', Password:'Hasło', Aspect:'Proporcje', Ratio:'obrazu', Calculator:'Kalkulator', JSON:'JSON', Formatter:'Formater', Validator:'Walidator', Base64:'Base64', Encoder:'Enkoder', Decoder:'Dekoder', Color:'Kolor', Picker:'Selektor', Palette:'Paleta', Video:'Wideo', Trimmer:'Przycinanie', Audio:'Audio', Extractor:'Ekstraktor', Muter:'Wyciszenie', GIF:'GIF', Meme:'Memy', Maker:'Kreator', AI:'AI', Captioner:'Napisy', SRT:'SRT', Cutter:'Obcinacz', Vocal:'Wokal', Instrumental:'Instrumental', Noise:'Szum', Reducer:'Reduktor', Regex:'Regex', Tester:'Tester', Debugger:'Debugger', Hash:'Hash', Object:'Obiekt', Watermark:'Znak wodny', Cropper:'Przycinarka', SVG:'SVG', OCR:'OCR', Passport:'Zdjęcie paszportowe', Adder:'Dodawanie', Collage:'Kolaż', Effects:'Efekty', Cleaner:'Czyścik', Optimizer:'Optymalizator', Mockup:'Makieta', Studio:'Studio', Seed:'Seed' },
  tr: { Image:'Görüntü', PDF:'PDF', Compressor:'Sıkıştırıcı', Background:'Arka plan', Remover:'Kaldırıcı', Upscaler:'Yükseltici', Converter:'Dönüştürücü', Merger:'Birleştirici', Splitter:'Bölücü', Unlock:'Kilit açma', Protect:'Koruma', Text:'Metin', Word:'Kelime', Character:'Karakter', Counter:'Sayaç', Diff:'Fark', Checker:'Denetleyici', Case:'Büyük/küçük harf', QR:'QR', Code:'Kod', Generator:'Oluşturucu', Reader:'Okuyucu', Password:'Şifre', Aspect:'En-boy', Ratio:'oranı', Calculator:'Hesap makinesi', JSON:'JSON', Formatter:'Biçimlendirici', Validator:'Doğrulayıcı', Base64:'Base64', Encoder:'Kodlayıcı', Decoder:'Kod çözücü', Color:'Renk', Picker:'Seçici', Palette:'Palet', Video:'Video', Trimmer:'Kırpıcı', Audio:'Ses', Extractor:'Çıkarıcı', Muter:'Sessize alıcı', GIF:'GIF', Meme:'Meme', Maker:'Oluşturucu', AI:'YZ', Captioner:'Altyazı', SRT:'SRT', Cutter:'Kesici', Vocal:'Vokal', Instrumental:'Enstrümantal', Noise:'Gürültü', Reducer:'Azaltıcı', Regex:'Regex', Tester:'Test aracı', Debugger:'Hata ayıklayıcı', Hash:'Hash', Object:'Nesne', Watermark:'Filigran', Cropper:'Kırpıcı', SVG:'SVG', OCR:'OCR', Passport:'Biyometrik fotoğraf', Adder:'Ekleyici', Collage:'Kolaj', Effects:'Efektler', Cleaner:'Temizleyici', Optimizer:'İyileştirici', Mockup:'Mockup', Studio:'Stüdyo', Seed:'Seed' },
  vi: { Image:'Hình ảnh', PDF:'PDF', Compressor:'Nén', Background:'Nền', Remover:'Xóa', Upscaler:'Tăng độ phân giải', Converter:'Chuyển đổi', Merger:'Gộp', Splitter:'Tách', Unlock:'Mở khóa', Protect:'Bảo vệ', Text:'Văn bản', Word:'Từ', Character:'Ký tự', Counter:'Bộ đếm', Diff:'So sánh', Checker:'Trình kiểm tra', Case:'Chữ hoa thường', QR:'QR', Code:'Mã', Generator:'Trình tạo', Reader:'Trình đọc', Password:'Mật khẩu', Aspect:'Tỷ lệ', Ratio:'khung hình', Calculator:'Máy tính', JSON:'JSON', Formatter:'Định dạng', Validator:'Xác thực', Base64:'Base64', Encoder:'Mã hóa', Decoder:'Giải mã', Color:'Màu', Picker:'Bộ chọn', Palette:'Bảng màu', Video:'Video', Trimmer:'Cắt', Audio:'Âm thanh', Extractor:'Trích xuất', Muter:'Tắt tiếng', GIF:'GIF', Meme:'Meme', Maker:'Trình tạo', AI:'AI', Captioner:'Phụ đề', SRT:'SRT', Cutter:'Cắt âm thanh', Vocal:'Giọng hát', Instrumental:'Nhạc nền', Noise:'Nhiễu', Reducer:'Giảm', Regex:'Regex', Tester:'Bộ kiểm thử', Debugger:'Gỡ lỗi', Hash:'Băm', Object:'Đối tượng', Watermark:'Hình mờ', Cropper:'Cắt ảnh', SVG:'SVG', OCR:'OCR', Passport:'Ảnh hộ chiếu', Adder:'Thêm', Collage:'Ghép ảnh', Effects:'Hiệu ứng', Cleaner:'Làm sạch', Optimizer:'Tối ưu hóa', Mockup:'Mockup', Studio:'Studio', Seed:'Seed' },
  th: { Image:'รูปภาพ', PDF:'PDF', Compressor:'คอมเพรสเซอร์', Background:'พื้นหลัง', Remover:'ตัวลบ', Upscaler:'เพิ่มความละเอียด', Converter:'ตัวแปลง', Merger:'ตัวรวม', Splitter:'ตัวแบ่ง', Unlock:'ปลดล็อก', Protect:'ป้องกัน', Text:'ข้อความ', Word:'คำ', Character:'อักขระ', Counter:'ตัวนับ', Diff:'ความแตกต่าง', Checker:'ตัวตรวจสอบ', Case:'ตัวพิมพ์', QR:'QR', Code:'โค้ด', Generator:'ตัวสร้าง', Reader:'ตัวอ่าน', Password:'รหัสผ่าน', Aspect:'อัตราส่วน', Ratio:'ภาพ', Calculator:'เครื่องคิดเลข', JSON:'JSON', Formatter:'ตัวจัดรูปแบบ', Validator:'ตัวตรวจสอบ', Base64:'Base64', Encoder:'ตัวเข้ารหัส', Decoder:'ตัวถอดรหัส', Color:'สี', Picker:'ตัวเลือก', Palette:'พาเลต', Video:'วิดีโอ', Trimmer:'ตัวตัด', Audio:'เสียง', Extractor:'ตัวแยก', Muter:'ปิดเสียง', GIF:'GIF', Meme:'มีม', Maker:'เครื่องมือสร้าง', AI:'AI', Captioner:'สร้างคำบรรยาย', SRT:'SRT', Cutter:'เครื่องมือตัด', Vocal:'เสียงร้อง', Instrumental:'ดนตรี', Noise:'เสียงรบกวน', Reducer:'ลดเสียง', Regex:'Regex', Tester:'ตัวทดสอบ', Debugger:'ดีบักเกอร์', Hash:'แฮช', Object:'วัตถุ', Watermark:'ลายน้ำ', Cropper:'ครอป', SVG:'SVG', OCR:'OCR', Passport:'รูปถ่ายพาสปอร์ต', Adder:'ตัวเพิ่ม', Collage:'คอลลาจ', Effects:'เอฟเฟกต์', Cleaner:'ตัวทำความสะอาด', Optimizer:'ตัวเพิ่มประสิทธิภาพ', Mockup:'ม็อกอัป', Studio:'สตูดิโอ', Seed:'Seed' },
  sv: { Image:'Bild', PDF:'PDF', Compressor:'Kompressor', Background:'Bakgrund', Remover:'Borttagare', Upscaler:'Uppskalare', Converter:'Konverterare', Merger:'Sammanslagning', Splitter:'Delare', Unlock:'Lås upp', Protect:'Skydd', Text:'Text', Word:'Ord', Character:'Tecken', Counter:'Räknare', Diff:'Skillnader', Checker:'Kontroll', Case:'Skiftläge', QR:'QR', Code:'Kod', Generator:'Generator', Reader:'Läsare', Password:'Lösenord', Aspect:'Bildförhållande', Ratio:'Förhållande', Calculator:'Kalkylator', JSON:'JSON', Formatter:'Formatterare', Validator:'Validator', Base64:'Base64', Encoder:'Kodare', Decoder:'Avkodare', Color:'Färg', Picker:'Väljare', Palette:'Palett', Video:'Video', Trimmer:'Beskärare', Audio:'Ljud', Extractor:'Extraherare', Muter:'Ljudavstängare', GIF:'GIF', Meme:'Mem', Maker:'Skapare', AI:'AI', Captioner:'Undertexter', SRT:'SRT', Cutter:'Klippverktyg', Vocal:'Sång', Instrumental:'Instrumental', Noise:'Brus', Reducer:'Reducerare', Regex:'Regex', Tester:'Testare', Debugger:'Felsökare', Hash:'Hash', Object:'Objekt', Watermark:'Vattenstämpel', Cropper:'Beskärare', SVG:'SVG', OCR:'OCR', Passport:'Passfoto', Adder:'Lägg till', Collage:'Kollage', Effects:'Effekter', Cleaner:'Rengörare', Optimizer:'Optimerare', Mockup:'Mockup', Studio:'Studio', Seed:'Seed' },
};

const splitTitle = (title: string) => title.replace(/&/g, ' & ').split(/\s+/).filter(Boolean);

function localizeTitle(locale: Locale, title: string): string {
  if (locale === 'en') return title;
  const map = TERM_MAPS[locale];
  return splitTitle(title).map((token) => map[token] ?? token).join(' ');
}

function capabilitiesFor(tool: ToolConfig, locale: Locale): string[] {
  const text = `${tool.id} ${tool.title}`.toLowerCase();
  const localized = TERM_MAPS[locale];
  const caps: string[] = [];
  const add = (value: string) => { if (!caps.includes(value)) caps.push(value); };
  if (text.includes('compress')) add(localized.Compressor ?? 'Compression');
  if (text.includes('convert')) add(localized.Converter ?? 'Conversion');
  if (text.includes('image') || text.includes('photo')) add(localized.Image ?? 'Images');
  if (text.includes('pdf')) add('PDF');
  if (text.includes('video')) add(localized.Video ?? 'Video');
  if (text.includes('audio')) add(localized.Audio ?? 'Audio');
  if (text.includes('text') || text.includes('word') || text.includes('ocr')) add(localized.Text ?? 'Text');
  if (text.includes('ai')) add(localized.AI ?? 'AI');
  if (text.includes('remove')) add(localized.Remover ?? 'Removal');
  if (text.includes('generator') || text.includes('maker')) add(localized.Generator ?? 'Generation');
  if (!caps.length) add(tool.category);
  return caps;
}

export function buildLocalizedToolSeo(tool: ToolConfig, locale: Locale): LocalizedToolSeo {
  const core = CORE[locale];
  const title = localizeTitle(locale, tool.title);
  const capabilities = capabilitiesFor(tool, locale);
  const intro = core.intro.replace('{title}', title);
  const description = locale === 'en'
    ? `${tool.description} FLIXO provides a browser-first workflow designed for speed, privacy, and simple exports.`
    : `${title} — ${core.online}. ${intro} ${capabilities.join(' · ')}.`;
  return {
    title: `${title} | FLIXO`,
    description,
    intro,
    keywords: Object.freeze([title, 'FLIXO', core.online, ...capabilities]),
    howTo: Object.freeze([core.step1, core.step2, core.step3, core.step4]),
    features: Object.freeze([...core.features, ...capabilities]),
    altText: Object.freeze([core.alt.replace('{title}', title)]),
  };
}

export function buildToolSeoManifest(tool: ToolConfig): ToolManifest {
  const seoLocales = Object.fromEntries(LOCALES.map((locale) => [locale, buildLocalizedToolSeo(tool, locale)])) as Record<Locale, LocalizedToolSeo>;
  return Object.freeze({
    toolId: tool.id,
    slug: tool.id,
    status: 'ready',
    seoStatus: 'complete',
    capabilities: Object.freeze([...capabilitiesFor(tool, 'en')]),
    seoLocales: Object.freeze(seoLocales),
  });
}

export function buildAllToolSeoManifests(tools: readonly ToolConfig[]): readonly ToolManifest[] {
  return Object.freeze(tools.filter((tool) => tool.isReady).map(buildToolSeoManifest));
}

export function getLocalizedSeoLanguage(locale: Locale): string {
  return LOCALE_METADATA[locale].languageTag;
}
