import type { Locale } from '@/lib/i18n';

export type FilterMaskCopy = Readonly<{
  title: 'Filter Mask';
  selected: string;
  startCamera: string;
  stop: string;
  switchCamera: string;
  photo: string;
  recordVideo: string;
  recording: string;
  stopRecording: string;
  cameraUnavailable: string;
  cameraDenied: string;
  recordingUnsupported: string;
  recordingUnavailable: string;
  recordingFailed: string;
  recordingStartFailed: string;
  searchFilters: string;
  searchPlaceholder: string;
  filterFamilies: string;
  all: string;
  favorites: string;
  recent: string;
  favorite: string;
  favoriteActive: string;
  reset: string;
  cameraFraming: string;
  zoom: string;
  mirrorOn: string;
  mirrorOff: string;
  intensity: string;
  aspectRatio: string;
  download: string;
  share: string;
  shareSetup: string;
  shareSetupUnsupported: string;
  shareSetupFailed: string;
  shareUnsupported: string;
  shareFileUnsupported: string;
  shareFailed: string;
  family: Readonly<Record<'color' | 'mood' | 'cinematic' | 'mono' | 'retro', string>>;
}>;

const EN: FilterMaskCopy = {
  title: 'Filter Mask',
  selected: 'Selected',
  startCamera: 'Start camera',
  stop: 'Stop',
  switchCamera: 'Switch camera',
  photo: 'Photo',
  recordVideo: 'Record video',
  recording: 'Recording',
  stopRecording: 'Stop recording',
  cameraUnavailable: 'Camera is not available in this browser.',
  cameraDenied: 'Camera or microphone access was denied or unavailable.',
  recordingUnsupported: 'Video recording with live effects is not supported in this browser.',
  recordingUnavailable: 'Video recording is unavailable.',
  recordingFailed: 'Video recording failed.',
  recordingStartFailed: 'Video recording could not be started.',
  searchFilters: 'Search filters',
  searchPlaceholder: 'Search filters',
  filterFamilies: 'Filter families',
  all: 'All',
  favorites: 'Favorites',
  recent: 'Recent',
  favorite: '☆ Favorite',
  favoriteActive: '★ Favorite',
  reset: 'Reset filter',
  cameraFraming: 'Camera framing',
  zoom: 'Zoom',
  mirrorOn: 'Mirror on',
  mirrorOff: 'Mirror off',
  intensity: 'Intensity',
  aspectRatio: 'Capture aspect ratio',
  download: 'Download result',
  share: 'Share result',
  shareSetup: 'Share filter setup',
  shareSetupUnsupported: 'Filter setup sharing is not available. Copy the current URL instead.',
  shareSetupFailed: 'Could not share the filter setup. Copy the current URL instead.',
  shareUnsupported: 'Sharing is not available in this browser. Use Download result instead.',
  shareFileUnsupported: 'This device cannot share this file. Use Download result instead.',
  shareFailed: 'Sharing failed. Use Download result instead.',
  family: { color: 'Color', mood: 'Mood', cinematic: 'Cinematic', mono: 'Mono', retro: 'Retro' },
};

export const FILTER_MASK_I18N: Readonly<Record<Locale, FilterMaskCopy>> = {
  ar: { ...EN, selected: 'المحدد', startCamera: 'بدء الكاميرا', stop: 'إيقاف', switchCamera: 'تبديل الكاميرا', photo: 'صورة', recordVideo: 'تسجيل فيديو', stopRecording: 'إيقاف التسجيل', cameraUnavailable: 'الكاميرا غير متاحة في هذا المتصفح.', cameraDenied: 'تم رفض الوصول إلى الكاميرا أو الميكروفون أو أنهما غير متاحين.', recordingUnsupported: 'تسجيل الفيديو مع التأثيرات المباشرة غير مدعوم في هذا المتصفح.', recordingUnavailable: 'تسجيل الفيديو غير متاح.', recordingFailed: 'فشل تسجيل الفيديو.', recordingStartFailed: 'تعذر بدء تسجيل الفيديو.', searchFilters: 'بحث في الفلاتر', searchPlaceholder: 'ابحث عن فلتر', filterFamilies: 'فئات الفلاتر', all: 'الكل', favorites: 'المفضلة', recent: 'الأخيرة', favorite: '☆ مفضلة', favoriteActive: '★ مفضلة', reset: 'إعادة ضبط الفلتر', cameraFraming: 'إطار الكاميرا', zoom: 'التكبير', mirrorOn: 'المرآة مفعلة', mirrorOff: 'المرآة متوقفة', intensity: 'الشدة', aspectRatio: 'نسبة التصوير', download: 'تنزيل النتيجة', share: 'مشاركة النتيجة', shareUnsupported: 'المشاركة غير متاحة في هذا المتصفح. استخدم تنزيل النتيجة.', shareFileUnsupported: 'هذا الجهاز لا يستطيع مشاركة هذا الملف. استخدم تنزيل النتيجة.', shareFailed: 'فشلت المشاركة. استخدم تنزيل النتيجة.', family: { color: 'ألوان', mood: 'مزاج', cinematic: 'سينمائي', mono: 'أحادي', retro: 'ريترو' } },
  en: EN,
  es: { ...EN, selected: 'Seleccionado', startCamera: 'Iniciar cámara', stop: 'Detener', switchCamera: 'Cambiar cámara', photo: 'Foto', recordVideo: 'Grabar vídeo', stopRecording: 'Detener grabación', cameraUnavailable: 'La cámara no está disponible en este navegador.', cameraDenied: 'Se denegó el acceso a la cámara o al micrófono o no están disponibles.', recordingUnsupported: 'La grabación de vídeo con efectos en directo no es compatible con este navegador.', recordingUnavailable: 'La grabación de vídeo no está disponible.', recordingFailed: 'La grabación de vídeo ha fallado.', recordingStartFailed: 'No se pudo iniciar la grabación de vídeo.', searchFilters: 'Buscar filtros', searchPlaceholder: 'Buscar filtros', filterFamilies: 'Familias de filtros', all: 'Todos', favorites: 'Favoritos', recent: 'Recientes', favorite: '☆ Favorito', favoriteActive: '★ Favorito', reset: 'Restablecer filtro', cameraFraming: 'Encuadre de cámara', zoom: 'Zoom', mirrorOn: 'Espejo activado', mirrorOff: 'Espejo desactivado', intensity: 'Intensidad', aspectRatio: 'Relación de aspecto', download: 'Descargar resultado', share: 'Compartir resultado', shareUnsupported: 'La función de compartir no está disponible. Usa Descargar resultado.', shareFileUnsupported: 'Este dispositivo no puede compartir este archivo. Usa Descargar resultado.', shareFailed: 'No se pudo compartir. Usa Descargar resultado.', family: { color: 'Color', mood: 'Ambiente', cinematic: 'Cinemático', mono: 'Mono', retro: 'Retro' } },
  fr: { ...EN, selected: 'Sélectionné', startCamera: 'Démarrer la caméra', stop: 'Arrêter', switchCamera: 'Changer de caméra', photo: 'Photo', recordVideo: 'Enregistrer la vidéo', stopRecording: 'Arrêter l’enregistrement', cameraUnavailable: 'La caméra n’est pas disponible dans ce navigateur.', cameraDenied: 'L’accès à la caméra ou au microphone a été refusé ou est indisponible.', recordingUnsupported: 'L’enregistrement vidéo avec effets en direct n’est pas pris en charge dans ce navigateur.', recordingUnavailable: 'L’enregistrement vidéo est indisponible.', recordingFailed: 'Échec de l’enregistrement vidéo.', recordingStartFailed: 'Impossible de démarrer l’enregistrement vidéo.', searchFilters: 'Rechercher des filtres', searchPlaceholder: 'Rechercher des filtres', filterFamilies: 'Familles de filtres', all: 'Tous', favorites: 'Favoris', recent: 'Récents', favorite: '☆ Favori', favoriteActive: '★ Favori', reset: 'Réinitialiser le filtre', cameraFraming: 'Cadre de caméra', zoom: 'Zoom', mirrorOn: 'Miroir activé', mirrorOff: 'Miroir désactivé', intensity: 'Intensité', aspectRatio: 'Format de capture', download: 'Télécharger le résultat', share: 'Partager le résultat', shareUnsupported: 'Le partage n’est pas disponible. Utilisez Télécharger le résultat.', shareFileUnsupported: 'Cet appareil ne peut pas partager ce fichier. Utilisez Télécharger le résultat.', shareFailed: 'Échec du partage. Utilisez Télécharger le résultat.', family: { color: 'Couleur', mood: 'Ambiance', cinematic: 'Cinéma', mono: 'Mono', retro: 'Rétro' } },
  de: { ...EN, selected: 'Ausgewählt', startCamera: 'Kamera starten', stop: 'Stopp', switchCamera: 'Kamera wechseln', photo: 'Foto', recordVideo: 'Video aufnehmen', stopRecording: 'Aufnahme stoppen', cameraUnavailable: 'Die Kamera ist in diesem Browser nicht verfügbar.', cameraDenied: 'Der Zugriff auf Kamera oder Mikrofon wurde verweigert oder ist nicht verfügbar.', recordingUnsupported: 'Videoaufnahmen mit Live-Effekten werden in diesem Browser nicht unterstützt.', recordingUnavailable: 'Videoaufnahme ist nicht verfügbar.', recordingFailed: 'Videoaufnahme fehlgeschlagen.', recordingStartFailed: 'Videoaufnahme konnte nicht gestartet werden.', searchFilters: 'Filter suchen', searchPlaceholder: 'Filter suchen', filterFamilies: 'Filterfamilien', all: 'Alle', favorites: 'Favoriten', recent: 'Zuletzt', favorite: '☆ Favorit', favoriteActive: '★ Favorit', reset: 'Filter zurücksetzen', cameraFraming: 'Kamerabild', zoom: 'Zoom', mirrorOn: 'Spiegelung an', mirrorOff: 'Spiegelung aus', intensity: 'Intensität', aspectRatio: 'Aufnahmeformat', download: 'Ergebnis herunterladen', share: 'Ergebnis teilen', shareUnsupported: 'Teilen ist in diesem Browser nicht verfügbar. Ergebnis herunterladen.', shareFileUnsupported: 'Dieses Gerät kann diese Datei nicht teilen. Ergebnis herunterladen.', shareFailed: 'Teilen fehlgeschlagen. Ergebnis herunterladen.', family: { color: 'Farbe', mood: 'Stimmung', cinematic: 'Cine', mono: 'Mono', retro: 'Retro' } },
  hi: { ...EN, selected: 'चयनित', startCamera: 'कैमरा शुरू करें', stop: 'रोकें', switchCamera: 'कैमरा बदलें', photo: 'फ़ोटो', recordVideo: 'वीडियो रिकॉर्ड करें', stopRecording: 'रिकॉर्डिंग रोकें', cameraUnavailable: 'इस ब्राउज़र में कैमरा उपलब्ध नहीं है।', cameraDenied: 'कैमरा या माइक्रोफ़ोन की अनुमति नहीं मिली या उपलब्ध नहीं है।', searchFilters: 'फ़िल्टर खोजें', searchPlaceholder: 'फ़िल्टर खोजें', filterFamilies: 'फ़िल्टर श्रेणियाँ', all: 'सभी', favorites: 'पसंदीदा', recent: 'हाल के', favorite: '☆ पसंदीदा', favoriteActive: '★ पसंदीदा', reset: 'फ़िल्टर रीसेट करें', cameraFraming: 'कैमरा फ़्रेमिंग', zoom: 'ज़ूम', mirrorOn: 'मिरर चालू', mirrorOff: 'मिरर बंद', intensity: 'तीव्रता', aspectRatio: 'कैप्चर अनुपात', download: 'परिणाम डाउनलोड करें', share: 'परिणाम साझा करें', shareUnsupported: 'साझा करना उपलब्ध नहीं है। परिणाम डाउनलोड करें।', shareFileUnsupported: 'यह डिवाइस इस फ़ाइल को साझा नहीं कर सकता। परिणाम डाउनलोड करें।', shareFailed: 'साझा करना विफल रहा। परिणाम डाउनलोड करें।', family: { color: 'रंग', mood: 'मूड', cinematic: 'सिनेमैटिक', mono: 'मोनो', retro: 'रेट्रो' } },
  id: { ...EN, selected: 'Dipilih', startCamera: 'Mulai kamera', stop: 'Berhenti', switchCamera: 'Ganti kamera', photo: 'Foto', recordVideo: 'Rekam video', stopRecording: 'Hentikan rekaman', cameraUnavailable: 'Kamera tidak tersedia di browser ini.', cameraDenied: 'Akses kamera atau mikrofon ditolak atau tidak tersedia.', searchFilters: 'Cari filter', searchPlaceholder: 'Cari filter', filterFamilies: 'Keluarga filter', all: 'Semua', favorites: 'Favorit', recent: 'Terbaru', favorite: '☆ Favorit', favoriteActive: '★ Favorit', reset: 'Atur ulang filter', cameraFraming: 'Pembingkaian kamera', zoom: 'Zoom', mirrorOn: 'Cermin aktif', mirrorOff: 'Cermin nonaktif', intensity: 'Intensitas', aspectRatio: 'Rasio pengambilan', download: 'Unduh hasil', share: 'Bagikan hasil', shareUnsupported: 'Berbagi tidak tersedia di browser ini. Gunakan Unduh hasil.', shareFileUnsupported: 'Perangkat ini tidak dapat membagikan file ini. Gunakan Unduh hasil.', shareFailed: 'Gagal membagikan. Gunakan Unduh hasil.', family: { color: 'Warna', mood: 'Suasana', cinematic: 'Sinematik', mono: 'Mono', retro: 'Retro' } },
  it: { ...EN, selected: 'Selezionato', startCamera: 'Avvia fotocamera', stop: 'Ferma', switchCamera: 'Cambia fotocamera', photo: 'Foto', recordVideo: 'Registra video', stopRecording: 'Ferma registrazione', cameraUnavailable: 'La fotocamera non è disponibile in questo browser.', cameraDenied: 'Accesso a fotocamera o microfono negato o non disponibile.', searchFilters: 'Cerca filtri', searchPlaceholder: 'Cerca filtri', filterFamilies: 'Famiglie di filtri', all: 'Tutti', favorites: 'Preferiti', recent: 'Recenti', favorite: '☆ Preferito', favoriteActive: '★ Preferito', reset: 'Reimposta filtro', cameraFraming: 'Inquadratura fotocamera', zoom: 'Zoom', mirrorOn: 'Specchio attivo', mirrorOff: 'Specchio disattivo', intensity: 'Intensità', aspectRatio: 'Formato di acquisizione', download: 'Scarica risultato', share: 'Condividi risultato', shareUnsupported: 'Condivisione non disponibile. Usa Scarica risultato.', shareFileUnsupported: 'Questo dispositivo non può condividere il file. Usa Scarica risultato.', shareFailed: 'Condivisione non riuscita. Usa Scarica risultato.', family: { color: 'Colore', mood: 'Umore', cinematic: 'Cinematico', mono: 'Mono', retro: 'Retrò' } },
  ja: { ...EN, selected: '選択中', startCamera: 'カメラを開始', stop: '停止', switchCamera: 'カメラを切り替え', photo: '写真', recordVideo: '動画を録画', stopRecording: '録画を停止', cameraUnavailable: 'このブラウザではカメラを利用できません。', cameraDenied: 'カメラまたはマイクへのアクセスが拒否されたか利用できません。', searchFilters: 'フィルターを検索', searchPlaceholder: 'フィルターを検索', filterFamilies: 'フィルター分類', all: 'すべて', favorites: 'お気に入り', recent: '最近', favorite: '☆ お気に入り', favoriteActive: '★ お気に入り', reset: 'フィルターをリセット', cameraFraming: 'カメラのフレーミング', zoom: 'ズーム', mirrorOn: 'ミラーオン', mirrorOff: 'ミラーオフ', intensity: '強度', aspectRatio: '撮影比率', download: '結果をダウンロード', share: '結果を共有', shareUnsupported: '共有は利用できません。結果をダウンロードしてください。', shareFileUnsupported: 'このデバイスではこのファイルを共有できません。結果をダウンロードしてください。', shareFailed: '共有に失敗しました。結果をダウンロードしてください。', family: { color: 'カラー', mood: 'ムード', cinematic: 'シネマ', mono: 'モノ', retro: 'レトロ' } },
  ko: { ...EN, selected: '선택됨', startCamera: '카메라 시작', stop: '중지', switchCamera: '카메라 전환', photo: '사진', recordVideo: '동영상 녹화', stopRecording: '녹화 중지', cameraUnavailable: '이 브라우저에서는 카메라를 사용할 수 없습니다.', cameraDenied: '카메라 또는 마이크 권한이 거부되었거나 사용할 수 없습니다.', searchFilters: '필터 검색', searchPlaceholder: '필터 검색', filterFamilies: '필터 분류', all: '전체', favorites: '즐겨찾기', recent: '최근 항목', favorite: '☆ 즐겨찾기', favoriteActive: '★ 즐겨찾기', reset: '필터 초기화', cameraFraming: '카메라 프레이밍', zoom: '확대', mirrorOn: '미러 켜짐', mirrorOff: '미러 꺼짐', intensity: '강도', aspectRatio: '촬영 비율', download: '결과 다운로드', share: '결과 공유', shareUnsupported: '공유를 사용할 수 없습니다. 결과를 다운로드하세요.', shareFileUnsupported: '이 기기에서는 이 파일을 공유할 수 없습니다. 결과를 다운로드하세요.', shareFailed: '공유에 실패했습니다. 결과를 다운로드하세요.', family: { color: '색상', mood: '무드', cinematic: '시네마틱', mono: '모노', retro: '레트로' } },
  ms: { ...EN, selected: 'Dipilih', startCamera: 'Mulakan kamera', stop: 'Berhenti', switchCamera: 'Tukar kamera', photo: 'Foto', recordVideo: 'Rakam video', stopRecording: 'Hentikan rakaman', cameraUnavailable: 'Kamera tidak tersedia dalam pelayar ini.', cameraDenied: 'Akses kamera atau mikrofon ditolak atau tidak tersedia.', searchFilters: 'Cari penapis', searchPlaceholder: 'Cari penapis', filterFamilies: 'Kumpulan penapis', all: 'Semua', favorites: 'Kegemaran', recent: 'Terkini', favorite: '☆ Kegemaran', favoriteActive: '★ Kegemaran', reset: 'Tetapkan semula penapis', cameraFraming: 'Pembingkaian kamera', zoom: 'Zum', mirrorOn: 'Cermin aktif', mirrorOff: 'Cermin tidak aktif', intensity: 'Intensiti', aspectRatio: 'Nisbah tangkapan', download: 'Muat turun hasil', share: 'Kongsi hasil', shareUnsupported: 'Perkongsian tidak tersedia. Gunakan Muat turun hasil.', shareFileUnsupported: 'Peranti ini tidak boleh berkongsi fail ini. Gunakan Muat turun hasil.', shareFailed: 'Perkongsian gagal. Gunakan Muat turun hasil.', family: { color: 'Warna', mood: 'Suasana', cinematic: 'Sinematik', mono: 'Mono', retro: 'Retro' } },
  nl: { ...EN, selected: 'Geselecteerd', startCamera: 'Camera starten', stop: 'Stoppen', switchCamera: 'Camera wisselen', photo: 'Foto', recordVideo: 'Video opnemen', stopRecording: 'Opname stoppen', cameraUnavailable: 'Camera is niet beschikbaar in deze browser.', cameraDenied: 'Toegang tot camera of microfoon is geweigerd of niet beschikbaar.', searchFilters: 'Filters zoeken', searchPlaceholder: 'Filters zoeken', filterFamilies: 'Filterfamilies', all: 'Alle', favorites: 'Favorieten', recent: 'Recent', favorite: '☆ Favoriet', favoriteActive: '★ Favoriet', reset: 'Filter resetten', cameraFraming: 'Camerakadrering', zoom: 'Zoom', mirrorOn: 'Spiegel aan', mirrorOff: 'Spiegel uit', intensity: 'Intensiteit', aspectRatio: 'Opnameverhouding', download: 'Resultaat downloaden', share: 'Resultaat delen', shareUnsupported: 'Delen is niet beschikbaar. Gebruik Resultaat downloaden.', shareFileUnsupported: 'Dit apparaat kan dit bestand niet delen. Gebruik Resultaat downloaden.', shareFailed: 'Delen mislukt. Gebruik Resultaat downloaden.', family: { color: 'Kleur', mood: 'Sfeer', cinematic: 'Cinematisch', mono: 'Mono', retro: 'Retro' } },
  pl: { ...EN, selected: 'Wybrano', startCamera: 'Uruchom aparat', stop: 'Zatrzymaj', switchCamera: 'Przełącz aparat', photo: 'Zdjęcie', recordVideo: 'Nagraj wideo', stopRecording: 'Zatrzymaj nagrywanie', cameraUnavailable: 'Aparat nie jest dostępny w tej przeglądarce.', cameraDenied: 'Odmówiono dostępu do aparatu lub mikrofonu albo są one niedostępne.', searchFilters: 'Szukaj filtrów', searchPlaceholder: 'Szukaj filtrów', filterFamilies: 'Rodziny filtrów', all: 'Wszystkie', favorites: 'Ulubione', recent: 'Ostatnie', favorite: '☆ Ulubione', favoriteActive: '★ Ulubione', reset: 'Resetuj filtr', cameraFraming: 'Kadrowanie aparatu', zoom: 'Zoom', mirrorOn: 'Lustro włączone', mirrorOff: 'Lustro wyłączone', intensity: 'Intensywność', aspectRatio: 'Proporcje ujęcia', download: 'Pobierz wynik', share: 'Udostępnij wynik', shareUnsupported: 'Udostępnianie jest niedostępne. Użyj Pobierz wynik.', shareFileUnsupported: 'To urządzenie nie może udostępnić tego pliku. Użyj Pobierz wynik.', shareFailed: 'Udostępnianie nie powiodło się. Użyj Pobierz wynik.', family: { color: 'Kolor', mood: 'Nastrój', cinematic: 'Kino', mono: 'Mono', retro: 'Retro' } },
  pt: { ...EN, selected: 'Selecionado', startCamera: 'Iniciar câmera', stop: 'Parar', switchCamera: 'Trocar câmera', photo: 'Foto', recordVideo: 'Gravar vídeo', stopRecording: 'Parar gravação', cameraUnavailable: 'A câmera não está disponível neste navegador.', cameraDenied: 'O acesso à câmera ou ao microfone foi negado ou não está disponível.', searchFilters: 'Pesquisar filtros', searchPlaceholder: 'Pesquisar filtros', filterFamilies: 'Famílias de filtros', all: 'Todos', favorites: 'Favoritos', recent: 'Recentes', favorite: '☆ Favorito', favoriteActive: '★ Favorito', reset: 'Redefinir filtro', cameraFraming: 'Enquadramento da câmera', zoom: 'Zoom', mirrorOn: 'Espelho ativado', mirrorOff: 'Espelho desativado', intensity: 'Intensidade', aspectRatio: 'Proporção de captura', download: 'Baixar resultado', share: 'Compartilhar resultado', shareUnsupported: 'O compartilhamento não está disponível. Use Baixar resultado.', shareFileUnsupported: 'Este dispositivo não pode compartilhar este arquivo. Use Baixar resultado.', shareFailed: 'Falha ao compartilhar. Use Baixar resultado.', family: { color: 'Cor', mood: 'Clima', cinematic: 'Cinemático', mono: 'Mono', retro: 'Retrô' } },
  ru: { ...EN, selected: 'Выбрано', startCamera: 'Запустить камеру', stop: 'Остановить', switchCamera: 'Сменить камеру', photo: 'Фото', recordVideo: 'Записать видео', stopRecording: 'Остановить запись', cameraUnavailable: 'Камера недоступна в этом браузере.', cameraDenied: 'Доступ к камере или микрофону запрещён или недоступен.', searchFilters: 'Поиск фильтров', searchPlaceholder: 'Поиск фильтров', filterFamilies: 'Категории фильтров', all: 'Все', favorites: 'Избранное', recent: 'Недавние', favorite: '☆ Избранное', favoriteActive: '★ Избранное', reset: 'Сбросить фильтр', cameraFraming: 'Кадрирование камеры', zoom: 'Масштаб', mirrorOn: 'Зеркало включено', mirrorOff: 'Зеркало выключено', intensity: 'Интенсивность', aspectRatio: 'Соотношение кадра', download: 'Скачать результат', share: 'Поделиться результатом', shareUnsupported: 'Общий доступ недоступен. Используйте Скачать результат.', shareFileUnsupported: 'Это устройство не может поделиться этим файлом. Используйте Скачать результат.', shareFailed: 'Не удалось поделиться. Используйте Скачать результат.', family: { color: 'Цвет', mood: 'Настроение', cinematic: 'Кино', mono: 'Моно', retro: 'Ретро' } },
  sv: { ...EN, selected: 'Vald', startCamera: 'Starta kamera', stop: 'Stoppa', switchCamera: 'Byt kamera', photo: 'Foto', recordVideo: 'Spela in video', stopRecording: 'Stoppa inspelning', cameraUnavailable: 'Kameran är inte tillgänglig i den här webbläsaren.', cameraDenied: 'Åtkomst till kamera eller mikrofon nekades eller är inte tillgänglig.', searchFilters: 'Sök filter', searchPlaceholder: 'Sök filter', filterFamilies: 'Filterfamiljer', all: 'Alla', favorites: 'Favoriter', recent: 'Senaste', favorite: '☆ Favorit', favoriteActive: '★ Favorit', reset: 'Återställ filter', cameraFraming: 'Kamerainramning', zoom: 'Zoom', mirrorOn: 'Spegel på', mirrorOff: 'Spegel av', intensity: 'Intensitet', aspectRatio: 'Bildformat', download: 'Ladda ned resultat', share: 'Dela resultat', shareUnsupported: 'Delning är inte tillgänglig. Använd Ladda ned resultat.', shareFileUnsupported: 'Den här enheten kan inte dela filen. Använd Ladda ned resultat.', shareFailed: 'Delning misslyckades. Använd Ladda ned resultat.', family: { color: 'Färg', mood: 'Stämning', cinematic: 'Cinematisk', mono: 'Mono', retro: 'Retro' } },
  th: { ...EN, selected: 'เลือกแล้ว', startCamera: 'เริ่มกล้อง', stop: 'หยุด', switchCamera: 'สลับกล้อง', photo: 'ถ่ายภาพ', recordVideo: 'บันทึกวิดีโอ', stopRecording: 'หยุดการบันทึก', cameraUnavailable: 'กล้องไม่พร้อมใช้งานในเบราว์เซอร์นี้', cameraDenied: 'ไม่อนุญาตให้เข้าถึงกล้องหรือไมโครโฟน หรือไม่พร้อมใช้งาน', searchFilters: 'ค้นหาฟิลเตอร์', searchPlaceholder: 'ค้นหาฟิลเตอร์', filterFamilies: 'หมวดฟิลเตอร์', all: 'ทั้งหมด', favorites: 'รายการโปรด', recent: 'ล่าสุด', favorite: '☆ รายการโปรด', favoriteActive: '★ รายการโปรด', reset: 'รีเซ็ตฟิลเตอร์', cameraFraming: 'การจัดเฟรมกล้อง', zoom: 'ซูม', mirrorOn: 'เปิดมิเรอร์', mirrorOff: 'ปิดมิเรอร์', intensity: 'ความเข้ม', aspectRatio: 'อัตราส่วนการถ่าย', download: 'ดาวน์โหลดผลลัพธ์', share: 'แชร์ผลลัพธ์', shareUnsupported: 'ไม่รองรับการแชร์ ใช้ดาวน์โหลดผลลัพธ์แทน', shareFileUnsupported: 'อุปกรณ์นี้แชร์ไฟล์นี้ไม่ได้ ใช้ดาวน์โหลดผลลัพธ์แทน', shareFailed: 'แชร์ไม่สำเร็จ ใช้ดาวน์โหลดผลลัพธ์แทน', family: { color: 'สี', mood: 'อารมณ์', cinematic: 'ภาพยนตร์', mono: 'โมโน', retro: 'เรโทร' } },
  tr: { ...EN, selected: 'Seçili', startCamera: 'Kamerayı başlat', stop: 'Durdur', switchCamera: 'Kamerayı değiştir', photo: 'Fotoğraf', recordVideo: 'Video kaydet', stopRecording: 'Kaydı durdur', cameraUnavailable: 'Kamera bu tarayıcıda kullanılamıyor.', cameraDenied: 'Kamera veya mikrofon erişimi reddedildi ya da kullanılamıyor.', searchFilters: 'Filtreleri ara', searchPlaceholder: 'Filtreleri ara', filterFamilies: 'Filtre grupları', all: 'Tümü', favorites: 'Favoriler', recent: 'Son kullanılanlar', favorite: '☆ Favori', favoriteActive: '★ Favori', reset: 'Filtreyi sıfırla', cameraFraming: 'Kamera kadrajı', zoom: 'Yakınlaştırma', mirrorOn: 'Ayna açık', mirrorOff: 'Ayna kapalı', intensity: 'Yoğunluk', aspectRatio: 'Çekim oranı', download: 'Sonucu indir', share: 'Sonucu paylaş', shareUnsupported: 'Paylaşım bu tarayıcıda kullanılamıyor. Sonucu indirin.', shareFileUnsupported: 'Bu cihaz bu dosyayı paylaşamıyor. Sonucu indirin.', shareFailed: 'Paylaşım başarısız. Sonucu indirin.', family: { color: 'Renk', mood: 'Mod', cinematic: 'Sinematik', mono: 'Mono', retro: 'Retro' } },
  uk: { ...EN, selected: 'Вибрано', startCamera: 'Запустити камеру', stop: 'Зупинити', switchCamera: 'Перемкнути камеру', photo: 'Фото', recordVideo: 'Записати відео', stopRecording: 'Зупинити запис', cameraUnavailable: 'Камера недоступна в цьому браузері.', cameraDenied: 'Доступ до камери або мікрофона заборонено або вони недоступні.', searchFilters: 'Пошук фільтрів', searchPlaceholder: 'Пошук фільтрів', filterFamilies: 'Категорії фільтрів', all: 'Усі', favorites: 'Уподобані', recent: 'Нещодавні', favorite: '☆ Уподобане', favoriteActive: '★ Уподобане', reset: 'Скинути фільтр', cameraFraming: 'Кадрування камери', zoom: 'Масштаб', mirrorOn: 'Дзеркало увімкнено', mirrorOff: 'Дзеркало вимкнено', intensity: 'Інтенсивність', aspectRatio: 'Співвідношення кадру', download: 'Завантажити результат', share: 'Поділитися результатом', shareUnsupported: 'Спільний доступ недоступний. Використайте Завантажити результат.', shareFileUnsupported: 'Цей пристрій не може поділитися цим файлом. Використайте Завантажити результат.', shareFailed: 'Не вдалося поділитися. Використайте Завантажити результат.', family: { color: 'Колір', mood: 'Настрій', cinematic: 'Кінематографічний', mono: 'Моно', retro: 'Ретро' } },
  vi: { ...EN, selected: 'Đã chọn', startCamera: 'Bật camera', stop: 'Dừng', switchCamera: 'Đổi camera', photo: 'Ảnh', recordVideo: 'Quay video', stopRecording: 'Dừng quay', cameraUnavailable: 'Camera không khả dụng trong trình duyệt này.', cameraDenied: 'Quyền truy cập camera hoặc mic bị từ chối hoặc không khả dụng.', searchFilters: 'Tìm bộ lọc', searchPlaceholder: 'Tìm bộ lọc', filterFamilies: 'Nhóm bộ lọc', all: 'Tất cả', favorites: 'Yêu thích', recent: 'Gần đây', favorite: '☆ Yêu thích', favoriteActive: '★ Yêu thích', reset: 'Đặt lại bộ lọc', cameraFraming: 'Khung hình camera', zoom: 'Thu phóng', mirrorOn: 'Bật gương', mirrorOff: 'Tắt gương', intensity: 'Cường độ', aspectRatio: 'Tỷ lệ khung hình', download: 'Tải kết quả', share: 'Chia sẻ kết quả', shareUnsupported: 'Không hỗ trợ chia sẻ. Hãy dùng Tải kết quả.', shareFileUnsupported: 'Thiết bị này không thể chia sẻ tệp. Hãy dùng Tải kết quả.', shareFailed: 'Chia sẻ thất bại. Hãy dùng Tải kết quả.', family: { color: 'Màu', mood: 'Tâm trạng', cinematic: 'Điện ảnh', mono: 'Mono', retro: 'Retro' } },
};
