export type LiveFilterDefinition = Readonly<{canonicalId:string;version:1;family:'color'|'mood'|'cinematic'|'mono'|'retro';label:string;cssFilter:string;supportsLive:true}>;
export const LIVE_FILTER_REGISTRY:readonly LiveFilterDefinition[] = Object.freeze([
  { canonicalId: 'effect.original', version: 1, family: 'color', label: 'Original', cssFilter: 'none', supportsLive: true },
  { canonicalId: 'effect.bright', version: 1, family: 'mood', label: 'Bright', cssFilter: 'brightness(0.98) saturate(0.85) contrast(0.94) hue-rotate(-28deg)', supportsLive: true },
  { canonicalId: 'effect.soft_light', version: 1, family: 'cinematic', label: 'Soft Light', cssFilter: 'brightness(1.02) saturate(0.98) contrast(1.02) hue-rotate(-21deg)', supportsLive: true },
  { canonicalId: 'effect.clean', version: 1, family: 'mono', label: 'Clean', cssFilter: 'brightness(1.06) saturate(1.1099999999999999) contrast(1.1) hue-rotate(-14deg)', supportsLive: true },
  { canonicalId: 'effect.vivid', version: 1, family: 'retro', label: 'Vivid', cssFilter: 'brightness(1.0999999999999999) saturate(1.24) contrast(1.18) hue-rotate(-7deg)', supportsLive: true },
  { canonicalId: 'effect.pop', version: 1, family: 'color', label: 'Pop', cssFilter: 'brightness(0.94) saturate(1.37) contrast(1.26) hue-rotate(0deg)', supportsLive: true },
  { canonicalId: 'effect.punch', version: 1, family: 'mood', label: 'Punch', cssFilter: 'brightness(0.98) saturate(1.5) contrast(0.86) hue-rotate(7deg)', supportsLive: true },
  { canonicalId: 'effect.warm', version: 1, family: 'cinematic', label: 'Warm', cssFilter: 'brightness(1.02) saturate(0.72) contrast(0.94) hue-rotate(14deg)', supportsLive: true },
  { canonicalId: 'effect.sunset', version: 1, family: 'mono', label: 'Sunset', cssFilter: 'brightness(1.06) saturate(0.85) contrast(1.02) hue-rotate(21deg)', supportsLive: true },
  { canonicalId: 'effect.golden_hour', version: 1, family: 'retro', label: 'Golden Hour', cssFilter: 'brightness(1.0999999999999999) saturate(0.98) contrast(1.1) hue-rotate(28deg)', supportsLive: true },
  { canonicalId: 'effect.cool', version: 1, family: 'color', label: 'Cool', cssFilter: 'brightness(0.94) saturate(1.1099999999999999) contrast(1.18) hue-rotate(35deg)', supportsLive: true },
  { canonicalId: 'effect.ice', version: 1, family: 'mood', label: 'Ice', cssFilter: 'brightness(0.98) saturate(1.24) contrast(1.26) hue-rotate(42deg)', supportsLive: true },
  { canonicalId: 'effect.ocean', version: 1, family: 'cinematic', label: 'Ocean', cssFilter: 'brightness(1.02) saturate(1.37) contrast(0.86) hue-rotate(-35deg)', supportsLive: true },
  { canonicalId: 'effect.forest', version: 1, family: 'mono', label: 'Forest', cssFilter: 'brightness(1.06) saturate(1.5) contrast(0.94) hue-rotate(-28deg)', supportsLive: true },
  { canonicalId: 'effect.olive', version: 1, family: 'retro', label: 'Olive', cssFilter: 'brightness(1.0999999999999999) saturate(0.72) contrast(1.02) hue-rotate(-21deg)', supportsLive: true },
  { canonicalId: 'effect.rose', version: 1, family: 'color', label: 'Rose', cssFilter: 'brightness(0.94) saturate(0.85) contrast(1.1) hue-rotate(-14deg)', supportsLive: true },
  { canonicalId: 'effect.blush', version: 1, family: 'mood', label: 'Blush', cssFilter: 'brightness(0.98) saturate(0.98) contrast(1.18) hue-rotate(-7deg)', supportsLive: true },
  { canonicalId: 'effect.lavender', version: 1, family: 'cinematic', label: 'Lavender', cssFilter: 'brightness(1.02) saturate(1.1099999999999999) contrast(1.26) hue-rotate(0deg)', supportsLive: true },
  { canonicalId: 'effect.neon', version: 1, family: 'mono', label: 'Neon', cssFilter: 'brightness(1.06) saturate(1.24) contrast(0.86) hue-rotate(7deg)', supportsLive: true },
  { canonicalId: 'effect.candy', version: 1, family: 'retro', label: 'Candy', cssFilter: 'brightness(1.0999999999999999) saturate(1.37) contrast(0.94) hue-rotate(14deg)', supportsLive: true },
  { canonicalId: 'effect.pastel', version: 1, family: 'color', label: 'Pastel', cssFilter: 'brightness(0.94) saturate(1.5) contrast(1.02) hue-rotate(21deg)', supportsLive: true },
  { canonicalId: 'effect.dream', version: 1, family: 'mood', label: 'Dream', cssFilter: 'brightness(0.98) saturate(0.72) contrast(1.1) hue-rotate(28deg)', supportsLive: true },
  { canonicalId: 'effect.haze', version: 1, family: 'cinematic', label: 'Haze', cssFilter: 'brightness(1.02) saturate(0.85) contrast(1.18) hue-rotate(35deg)', supportsLive: true },
  { canonicalId: 'effect.film', version: 1, family: 'mono', label: 'Film', cssFilter: 'brightness(1.06) saturate(0.98) contrast(1.26) hue-rotate(42deg)', supportsLive: true },
  { canonicalId: 'effect.cinema', version: 1, family: 'retro', label: 'Cinema', cssFilter: 'brightness(1.0999999999999999) saturate(1.1099999999999999) contrast(0.86) hue-rotate(-35deg)', supportsLive: true },
  { canonicalId: 'effect.noir', version: 1, family: 'color', label: 'Noir', cssFilter: 'brightness(0.94) saturate(1.24) contrast(0.94) hue-rotate(-28deg)', supportsLive: true },
  { canonicalId: 'effect.silver', version: 1, family: 'mood', label: 'Silver', cssFilter: 'brightness(0.98) saturate(1.37) contrast(1.02) hue-rotate(-21deg)', supportsLive: true },
  { canonicalId: 'effect.mono_soft', version: 1, family: 'cinematic', label: 'Mono Soft', cssFilter: 'brightness(1.02) saturate(1.5) contrast(1.1) hue-rotate(-14deg)', supportsLive: true },
  { canonicalId: 'effect.mono_crush', version: 1, family: 'mono', label: 'Mono Crush', cssFilter: 'brightness(1.06) saturate(0.72) contrast(1.18) hue-rotate(-7deg)', supportsLive: true },
  { canonicalId: 'effect.fade', version: 1, family: 'retro', label: 'Fade', cssFilter: 'brightness(1.0999999999999999) saturate(0.85) contrast(1.26) hue-rotate(0deg)', supportsLive: true },
  { canonicalId: 'effect.vintage', version: 1, family: 'color', label: 'Vintage', cssFilter: 'brightness(0.94) saturate(0.98) contrast(0.86) hue-rotate(7deg)', supportsLive: true },
  { canonicalId: 'effect.70s', version: 1, family: 'mood', label: '70s', cssFilter: 'brightness(0.98) saturate(1.1099999999999999) contrast(0.94) hue-rotate(14deg)', supportsLive: true },
  { canonicalId: 'effect.80s', version: 1, family: 'cinematic', label: '80s', cssFilter: 'brightness(1.02) saturate(1.24) contrast(1.02) hue-rotate(21deg)', supportsLive: true },
  { canonicalId: 'effect.90s', version: 1, family: 'mono', label: '90s', cssFilter: 'brightness(1.06) saturate(1.37) contrast(1.1) hue-rotate(28deg)', supportsLive: true },
  { canonicalId: 'effect.polaroid', version: 1, family: 'retro', label: 'Polaroid', cssFilter: 'brightness(1.0999999999999999) saturate(1.5) contrast(1.18) hue-rotate(35deg)', supportsLive: true },
  { canonicalId: 'effect.faded_film', version: 1, family: 'color', label: 'Faded Film', cssFilter: 'brightness(0.94) saturate(0.72) contrast(1.26) hue-rotate(42deg)', supportsLive: true },
  { canonicalId: 'effect.copper', version: 1, family: 'mood', label: 'Copper', cssFilter: 'brightness(0.98) saturate(0.85) contrast(0.86) hue-rotate(-35deg)', supportsLive: true },
  { canonicalId: 'effect.amber', version: 1, family: 'cinematic', label: 'Amber', cssFilter: 'brightness(1.02) saturate(0.98) contrast(0.94) hue-rotate(-28deg)', supportsLive: true },
  { canonicalId: 'effect.teal', version: 1, family: 'mono', label: 'Teal', cssFilter: 'brightness(1.06) saturate(1.1099999999999999) contrast(1.02) hue-rotate(-21deg)', supportsLive: true },
  { canonicalId: 'effect.teal_orange', version: 1, family: 'retro', label: 'Teal Orange', cssFilter: 'brightness(1.0999999999999999) saturate(1.24) contrast(1.1) hue-rotate(-14deg)', supportsLive: true },
  { canonicalId: 'effect.drama', version: 1, family: 'color', label: 'Drama', cssFilter: 'brightness(0.94) saturate(1.37) contrast(1.18) hue-rotate(-7deg)', supportsLive: true },
  { canonicalId: 'effect.blockbuster', version: 1, family: 'mood', label: 'Blockbuster', cssFilter: 'brightness(0.98) saturate(1.5) contrast(1.26) hue-rotate(0deg)', supportsLive: true },
  { canonicalId: 'effect.matte', version: 1, family: 'cinematic', label: 'Matte', cssFilter: 'brightness(1.02) saturate(0.72) contrast(0.86) hue-rotate(7deg)', supportsLive: true },
  { canonicalId: 'effect.crisp', version: 1, family: 'mono', label: 'Crisp', cssFilter: 'brightness(1.06) saturate(0.85) contrast(0.94) hue-rotate(14deg)', supportsLive: true },
  { canonicalId: 'effect.studio', version: 1, family: 'retro', label: 'Studio', cssFilter: 'brightness(1.0999999999999999) saturate(0.98) contrast(1.02) hue-rotate(21deg)', supportsLive: true },
  { canonicalId: 'effect.portrait', version: 1, family: 'color', label: 'Portrait', cssFilter: 'brightness(0.94) saturate(1.1099999999999999) contrast(1.1) hue-rotate(28deg)', supportsLive: true },
  { canonicalId: 'effect.glow', version: 1, family: 'mood', label: 'Glow', cssFilter: 'brightness(0.98) saturate(1.24) contrast(1.18) hue-rotate(35deg)', supportsLive: true },
  { canonicalId: 'effect.soft_glow', version: 1, family: 'cinematic', label: 'Soft Glow', cssFilter: 'brightness(1.02) saturate(1.37) contrast(1.26) hue-rotate(42deg)', supportsLive: true },
  { canonicalId: 'effect.sun', version: 1, family: 'mono', label: 'Sun', cssFilter: 'brightness(1.06) saturate(1.5) contrast(0.86) hue-rotate(-35deg)', supportsLive: true },
  { canonicalId: 'effect.cloud', version: 1, family: 'retro', label: 'Cloud', cssFilter: 'brightness(1.0999999999999999) saturate(0.72) contrast(0.94) hue-rotate(-28deg)', supportsLive: true },
  { canonicalId: 'effect.moon', version: 1, family: 'color', label: 'Moon', cssFilter: 'brightness(0.94) saturate(0.85) contrast(1.02) hue-rotate(-21deg)', supportsLive: true },
  { canonicalId: 'effect.midnight', version: 1, family: 'mood', label: 'Midnight', cssFilter: 'brightness(0.98) saturate(0.98) contrast(1.1) hue-rotate(-14deg)', supportsLive: true },
  { canonicalId: 'effect.storm', version: 1, family: 'cinematic', label: 'Storm', cssFilter: 'brightness(1.02) saturate(1.1099999999999999) contrast(1.18) hue-rotate(-7deg)', supportsLive: true },
  { canonicalId: 'effect.urban', version: 1, family: 'mono', label: 'Urban', cssFilter: 'brightness(1.06) saturate(1.24) contrast(1.26) hue-rotate(0deg)', supportsLive: true },
  { canonicalId: 'effect.street', version: 1, family: 'retro', label: 'Street', cssFilter: 'brightness(1.0999999999999999) saturate(1.37) contrast(0.86) hue-rotate(7deg)', supportsLive: true },
  { canonicalId: 'effect.editorial', version: 1, family: 'color', label: 'Editorial', cssFilter: 'brightness(0.94) saturate(1.5) contrast(0.94) hue-rotate(14deg)', supportsLive: true },
  { canonicalId: 'effect.minimal', version: 1, family: 'mood', label: 'Minimal', cssFilter: 'brightness(0.98) saturate(0.72) contrast(1.02) hue-rotate(21deg)', supportsLive: true },
  { canonicalId: 'effect.natural', version: 1, family: 'cinematic', label: 'Natural', cssFilter: 'brightness(1.02) saturate(0.85) contrast(1.1) hue-rotate(28deg)', supportsLive: true },
  { canonicalId: 'effect.fresh', version: 1, family: 'mono', label: 'Fresh', cssFilter: 'brightness(1.06) saturate(0.98) contrast(1.18) hue-rotate(35deg)', supportsLive: true },
  { canonicalId: 'effect.leaf', version: 1, family: 'retro', label: 'Leaf', cssFilter: 'brightness(1.0999999999999999) saturate(1.1099999999999999) contrast(1.26) hue-rotate(42deg)', supportsLive: true },
  { canonicalId: 'effect.sky', version: 1, family: 'color', label: 'Sky', cssFilter: 'brightness(0.94) saturate(1.24) contrast(0.86) hue-rotate(-35deg)', supportsLive: true },
  { canonicalId: 'effect.chrome', version: 1, family: 'mood', label: 'Chrome', cssFilter: 'brightness(0.98) saturate(1.37) contrast(0.94) hue-rotate(-28deg)', supportsLive: true },
  { canonicalId: 'effect.graphite', version: 1, family: 'cinematic', label: 'Graphite', cssFilter: 'brightness(1.02) saturate(1.5) contrast(1.02) hue-rotate(-21deg)', supportsLive: true },
  { canonicalId: 'effect.ink', version: 1, family: 'mono', label: 'Ink', cssFilter: 'brightness(1.06) saturate(0.72) contrast(1.1) hue-rotate(-14deg)', supportsLive: true },
  { canonicalId: 'effect.peach', version: 1, family: 'retro', label: 'Peach', cssFilter: 'brightness(1.0999999999999999) saturate(0.85) contrast(1.18) hue-rotate(-7deg)', supportsLive: true },
  { canonicalId: 'effect.mint', version: 1, family: 'color', label: 'Mint', cssFilter: 'brightness(0.94) saturate(0.98) contrast(1.26) hue-rotate(0deg)', supportsLive: true },
  { canonicalId: 'effect.violet', version: 1, family: 'mood', label: 'Violet', cssFilter: 'brightness(0.98) saturate(1.1099999999999999) contrast(0.86) hue-rotate(7deg)', supportsLive: true },
  { canonicalId: 'effect.sapphire', version: 1, family: 'cinematic', label: 'Sapphire', cssFilter: 'brightness(1.02) saturate(1.24) contrast(0.94) hue-rotate(14deg)', supportsLive: true },
  { canonicalId: 'effect.crimson', version: 1, family: 'mono', label: 'Crimson', cssFilter: 'brightness(1.06) saturate(1.37) contrast(1.02) hue-rotate(21deg)', supportsLive: true },
]);
const IDS=new Set(LIVE_FILTER_REGISTRY.map((filter)=>filter.canonicalId));
if(IDS.size!==LIVE_FILTER_REGISTRY.length) throw new Error('Duplicate live filter canonicalId.');
if(LIVE_FILTER_REGISTRY.length<60) throw new Error('Filter Mask requires at least 60 live filters.');
export const getLiveFilter=(canonicalId:string)=>LIVE_FILTER_REGISTRY.find((filter)=>filter.canonicalId===canonicalId);
