import { getCapability,type CapabilityParameters } from './capability-registry.ts';
import { deriveToolSecurityProfile,assertExecutionSecurityBoundary,type ExecutionPermission } from './execution-observability.ts';
import { getToolDefinition,type ToolDefinition } from '@/config/canonical-tool-definition.ts';
export type CapabilityTrust='CORE'|'TRUSTED'|'UNTRUSTED';
export type CapabilityAccess=Readonly<{capabilityId:string;permission:ExecutionPermission;trust:CapabilityTrust;executionMode:ToolDefinition['executionMode'];network:boolean;externalProcessing:boolean;localOnly:boolean;}>;
const R:Record<CapabilityTrust,number>=Object.freeze({UNTRUSTED:0,TRUSTED:1,CORE:2});
const required=(t:ToolDefinition):CapabilityTrust=>t.executionMode==='CLOUD'||t.requirements.network?'CORE':t.operational.lifecycle==='ready'&&t.isReady?'TRUSTED':'UNTRUSTED';
export function deriveCapabilityAccess(id:string):CapabilityAccess{const c=getCapability(id),t=getToolDefinition(id);if(!c||!t)throw new Error('Unknown capability: '+id);assertExecutionSecurityBoundary(t);const s=deriveToolSecurityProfile(t);return Object.freeze({capabilityId:id,permission:c.state==='EXECUTABLE'?'EXECUTE':'READ',trust:required(t),executionMode:t.executionMode,network:s.network,externalProcessing:s.externalProcessing,localOnly:s.privacyBoundary==='LOCAL_ONLY'});}
export function authorizeCapabilityAccess(i:{capabilityId:string;requestedPermission:ExecutionPermission;actorTrust?:CapabilityTrust;parameters?:unknown;}):CapabilityAccess&{parameters:CapabilityParameters}{const a=deriveCapabilityAccess(i.capabilityId),actor=i.actorTrust??'CORE';if(i.requestedPermission==='WRITE')throw new Error('CAPABILITY_WRITE_PERMISSION_NOT_AVAILABLE');if(R[actor]<R[a.trust])throw new Error('CAPABILITY_TRUST_DENIED:'+i.capabilityId);if(i.requestedPermission==='EXECUTE'&&a.permission!=='EXECUTE')throw new Error('CAPABILITY_EXECUTION_DENIED:'+i.capabilityId);const c=getCapability(i.capabilityId);if(!c)throw new Error('Unknown capability: '+i.capabilityId);const p=i.parameters===undefined?{}:c.parameterSchema.parse(i.parameters);return Object.freeze({...a,parameters:Object.freeze(p as CapabilityParameters)});}
