import {z,type ZodType} from 'zod';
import {authorizeCapabilityAccess,type CapabilityTrust} from './capability-access.ts';
export const MCP_GATEWAY_VERSION=1 as const;
const Name=z.string().trim().min(1).max(128).regex(/^[A-Za-z0-9._:-]+$/u),Timeout=z.number().int().positive().max(120000);
export type McpCapabilityDefinition<I,O>=Readonly<{id:string;inputSchema:ZodType<I>;outputSchema:ZodType<O>;permission:'READ'|'EXECUTE';requiredTrust:CapabilityTrust;timeoutMs:number;capabilityId?:string;invoke:(input:I,signal:AbortSignal)=>Promise<unknown>;verify?:(output:O,input:I)=>boolean|Promise<boolean>}>;
export type McpInvocationResult<O>=Readonly<{output:O|undefined;audit:Readonly<{version:1;capability:string;permission:'READ'|'EXECUTE';trust:CapabilityTrust;outcome:'SUCCESS'|'BLOCKED'|'FAILURE';durationMs:number;reason?:string}>;}>;
function def<I,O>(d:McpCapabilityDefinition<I,O>){Name.parse(d.id);Timeout.parse(d.timeoutMs);if(d.requiredTrust==='UNTRUSTED'&&d.permission==='EXECUTE')throw new Error('MCP_EXECUTION_REQUIRES_TRUSTED_CAPABILITY');}
async function timed<I>(p:Promise<I>,ms:number,s:AbortSignal){return await new Promise<I>((ok,bad)=>{const t=setTimeout(()=>bad(new Error('MCP_GATEWAY_TIMEOUT')),ms);const abort=()=>{clearTimeout(t);bad(new Error('MCP_GATEWAY_ABORTED'));};if(s.aborted)return abort();s.addEventListener('abort',abort,{once:true});p.then(v=>{clearTimeout(t);s.removeEventListener('abort',abort);ok(v);},e=>{clearTimeout(t);s.removeEventListener('abort',abort);bad(e);});});}
export async function invokeMcpCapability<I,O>(d:McpCapabilityDefinition<I,O>,input:unknown,ctx:{actorTrust?:CapabilityTrust;signal?:AbortSignal}={}):Promise<McpInvocationResult<O>>{const started=Date.now(),trust=ctx.actorTrust??'CORE',signal=ctx.signal??new AbortController().signal;try{def(d);const parsed=d.inputSchema.parse(input);if(d.capabilityId)authorizeCapabilityAccess({capabilityId:d.capabilityId,requestedPermission:d.permission,actorTrust:trust,parameters:parsed});else if(d.permission==='EXECUTE'&&d.requiredTrust==='CORE'&&trust!=='CORE')throw new Error('MCP_CORE_TRUST_REQUIRED');const out=await timed(d.invoke(parsed,signal),d.timeoutMs,signal);const valid=d.outputSchema.parse(out);if(d.verify&&!(await d.verify(valid,parsed)))throw new Error('MCP_OUTPUT_VERIFICATION_FAILED');return Object.freeze({output:valid,audit:Object.freeze({version:1,capability:d.id,permission:d.permission,trust,outcome:'SUCCESS',durationMs:Date.now()-started})});}catch(e){const reason=e instanceof Error?e.message:'MCP_GATEWAY_FAILURE',blocked=/(?:DENIED|TRUST|PERMISSION|UNTRUSTED|REQUIRED_CORE|AUTHORIZATION)/u.test(reason);return Object.freeze({output:undefined,audit:Object.freeze({version:1,capability:d.id,permission:d.permission,trust,outcome:blocked?'BLOCKED':'FAILURE',durationMs:Date.now()-started,reason})});}}
