import { useEffect, useRef, useState } from 'react';
import { buildArgs, calculateSavings, getMime, getOutputName, normalizeFormat, normalizeQuality, type AudioFormat, type AudioQuality } from './engine';
type WorkerMessage = { type: 'progress'; jobId: string; progress: number } | { type: 'status'; jobId: string; message: string } | { type: 'done'; jobId: string; bytes: Uint8Array } | { type: 'error'; jobId: string; message: string };
export function AudioFormatConverterTool() {
  const workerRef = useRef<Worker | null>(null); const outputUrlRef = useRef<string | null>(null);
  const [file,setFile]=useState<File|null>(null); const [format,setFormat]=useState<AudioFormat>('mp3'); const [quality,setQuality]=useState<AudioQuality>('balanced');
  const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(0); const [status,setStatus]=useState(''); const [error,setError]=useState(''); const [outputUrl,setOutputUrl]=useState<string|null>(null); const [outputSize,setOutputSize]=useState<number|null>(null);
  useEffect(() => () => { workerRef.current?.terminate(); if (outputUrlRef.current) URL.revokeObjectURL(outputUrlRef.current); }, []);
  const choose=(next?:File)=>{ if(!next)return; if(!next.type.startsWith('audio/')){setError('Please choose an audio file.');return;} setFile(next);setError('');setStatus(`${(next.size/1024/1024).toFixed(2)} MB selected`);setOutputSize(null);if(outputUrlRef.current)URL.revokeObjectURL(outputUrlRef.current);outputUrlRef.current=null;setOutputUrl(null); };
  const run=()=>{ if(!file||busy)return; setBusy(true);setProgress(0);setError('');setStatus('Preparing local worker…'); workerRef.current?.terminate(); const worker=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});workerRef.current=worker;const jobId=crypto.randomUUID();const inputName=`input-${jobId}.${file.name.split('.').pop()||'bin'}`;const outputName=`output-${jobId}.${format}`;const args=buildArgs(inputName,outputName,normalizeFormat(format),normalizeQuality(quality));
    worker.onmessage=({data}:MessageEvent<WorkerMessage>)=>{if(data.jobId!==jobId)return;if(data.type==='progress'){setProgress(Math.round(data.progress*100));setStatus(`Converting… ${Math.round(data.progress*100)}%`);return;}if(data.type==='status'){setStatus(data.message);return;}if(data.type==='error'){setBusy(false);setError(data.message);setStatus('');worker.terminate();return;}const copy=new ArrayBuffer(data.bytes.byteLength);new Uint8Array(copy).set(data.bytes);const blob=new Blob([copy],{type:getMime(format)});const url=URL.createObjectURL(blob);if(outputUrlRef.current)URL.revokeObjectURL(outputUrlRef.current);outputUrlRef.current=url;setOutputUrl(url);setOutputSize(blob.size);setProgress(100);setBusy(false);setStatus(`Ready · ${calculateSavings(file.size,blob.size).toFixed(1)}% size change`);worker.terminate();};
    worker.onerror=()=>{setBusy(false);setError('Audio processing worker failed.');setStatus('');worker.terminate();};
    void file.arrayBuffer().then(buffer=>worker.postMessage({jobId,bytes:new Uint8Array(buffer),inputName,outputName,args},[buffer])).catch(()=>{setBusy(false);setError('Unable to read the selected file.');worker.terminate();}); };
  return <section className="mx-auto flex max-w-3xl flex-col gap-5 rounded-2xl border border-border bg-background p-6 text-foreground"><div><h1 className="text-2xl font-bold">Audio Format Converter</h1><p className="mt-1 text-sm text-muted-foreground">Convert audio locally with a background FFmpeg worker.</p></div><label className="rounded-xl border border-dashed border-border p-6 text-center"><span className="mb-3 block font-medium">Choose audio</span><input aria-label="Audio file" type="file" accept="audio/*" onChange={e=>choose(e.target.files?.[0])}/></label><div className="grid gap-4 md:grid-cols-2"><label>Format<select aria-label="Output format" className="mt-1 w-full rounded border p-2" value={format} onChange={e=>setFormat(normalizeFormat(e.target.value))}><option value="mp3">MP3</option><option value="wav">WAV</option><option value="aac">AAC</option><option value="m4a">M4A</option><option value="ogg">OGG</option><option value="flac">FLAC</option></select></label><label>Quality<select aria-label="Quality" className="mt-1 w-full rounded border p-2" value={quality} onChange={e=>setQuality(normalizeQuality(e.target.value))}><option value="high">High</option><option value="balanced">Balanced</option><option value="small">Small</option></select></label></div>{file?<p className="text-sm text-muted-foreground">Input: {file.name} · {(file.size/1024/1024).toFixed(2)} MB</p>:null}<button type="button" disabled={!file||busy} onClick={run} className="rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-50">{busy?'Converting…':'Convert Audio'}</button>{busy?<progress aria-label="Processing progress" className="w-full" max={100} value={progress}/>:null}{status?<p aria-live="polite" className="text-sm text-muted-foreground">{status}</p>:null}{error?<p role="alert" className="text-sm text-destructive">{error}</p>:null}{outputUrl?<a className="rounded-xl border border-border px-4 py-3 text-center font-semibold" href={outputUrl} download={file?getOutputName(file.name,format):`flixo-audio.${format}`}>Download output{outputSize?` · ${(outputSize/1024/1024).toFixed(2)} MB`:''}</a>:null}</section>;
}
