import { appendFile, mkdir, readFile } from 'node:fs/promises';
import { createHash, createHmac, randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { dirname } from 'node:path';

const LEDGER = process.env.FLIXO_SWARM_LEDGER ?? 'artifacts/ci/agent-coordination/events.ndjson';
const QUEUE = process.env.FLIXO_SWARM_WORK_QUEUE ?? '.ci/agent-coordination/work-queue.json';
const HEAD = process.env.EXPECTED_HEAD_SHA ?? git('rev-parse', 'HEAD');
const AGENT = process.env.FLIXO_AGENT_ID ?? '';
const BRANCH = process.env.GITHUB_HEAD_REF ?? process.env.GITHUB_REF_NAME ?? git('branch', '--show-current');
const LEASE_MS = Number.parseInt(process.env.FLIXO_SWARM_LEASE_MINUTES ?? '30', 10) * 60_000;
const HEARTBEAT_MS = Number.parseInt(process.env.FLIXO_SWARM_HEARTBEAT_MINUTES ?? '10', 10) * 60_000;
const KEY = process.env.FLIXO_SWARM_EVENT_SIGNING_KEY ?? '';
const HEX = /^[0-9a-f]{40}$/u;
const BRANCH_RE = /^agent\/[^/]+\/.+$/u;
const fail = (code, msg) => { const e = new Error(`${code}: ${msg}`); e.code = code; throw e; };
function git(...args) { try { return execFileSync('git', args, { encoding: 'utf8' }).trim(); } catch { return ''; } }
function iso(v) { const t = Date.parse(v ?? ''); if (!Number.isFinite(t)) fail('SWARM_EVENT_SCHEMA_ERROR', `invalid timestamp ${v}`); return t; }
function sha(v) { return createHash('sha256').update(v).digest('hex'); }
function canonical(event) { return JSON.stringify(event, Object.keys(event).sort()); }
function ancestor(a, b) { if (a === b) return true; try { execFileSync('git', ['merge-base', '--is-ancestor', a, b], { stdio: 'ignore' }); return true; } catch { return false; } }
function overlap(a, b) { return a === b || a.startsWith(`${b}/`) || b.startsWith(`${a}/`); }
function activeClaims(state, at = Date.now()) { return [...state.claims.values()].filter((c) => c.status === 'active' && iso(c.leaseUntil) > at); }
async function readEvents() { try { const s = await readFile(LEDGER, 'utf8'); return s.trim() ? s.split(/\r?\n/u).map((x) => JSON.parse(x)) : []; } catch (e) { if (e?.code === 'ENOENT') return []; throw e; } }
function empty() { return { claims: new Map(), work: new Map(), bids: new Map(), lastTimestamp: 0, lastHash: 'GENESIS' }; }
function validateEvent(e, seq, prev, replayHead) {
  if (e?.schemaVersion !== 1 || e.protocol !== 'FLIXO swarm event ledger') fail('SWARM_EVENT_SCHEMA_ERROR', `invalid protocol at ${seq}`);
  if (e.sequence !== seq || e.prevHash !== prev) fail('SWARM_EVENT_CHAIN_BROKEN', `sequence/link mismatch at ${seq}`);
  if (!HEX.test(e.parentSha ?? '') || !ancestor(e.parentSha, replayHead)) fail('SWARM_OCC_CONFLICT', `event ${seq} parent SHA is not in current history`);
  iso(e.timestamp); if (!e.eventId || !e.agentId || !e.type || !e.payload || typeof e.payload !== 'object') fail('SWARM_EVENT_SCHEMA_ERROR', `invalid event shape at ${seq}`);
  const unsigned = { ...e }; delete unsigned.hash; delete unsigned.signature; if (sha(canonical(unsigned)) !== e.hash) fail('SWARM_EVENT_HASH_MISMATCH', `hash mismatch at ${seq}`);
  if (e.signature) { if (!KEY) fail('SWARM_EVENT_SIGNATURE_UNVERIFIABLE', 'signing key required'); const expected = createHmac('sha256', KEY).update(e.hash).digest('hex'); if (expected !== e.signature) fail('SWARM_EVENT_SIGNATURE_INVALID', `signature mismatch at ${seq}`); }
}
function reduce(events) {
  const state = empty(); let prev = 'GENESIS'; let seq = 1;
  const collides = (a, b) => (a.scope.paths ?? []).some((p) => (b.scope.paths ?? []).some((q) => overlap(p, q))) || (a.scope.contracts ?? []).some((c) => (b.scope.contracts ?? []).includes(c)) || (a.rootCauseIds ?? []).some((r) => (b.rootCauseIds ?? []).includes(r));
  for (const e of events) {
    validateEvent(e, seq, prev, HEAD); const t = iso(e.timestamp); if (t < state.lastTimestamp) fail('SWARM_EVENT_ORDER_ERROR', `timestamp regression at ${seq}`); state.lastTimestamp = t;
    const p = e.payload;
    if (e.type === 'STATE_BOOTSTRAP') { if (seq !== 1) fail('SWARM_EVENT_SCHEMA_ERROR', 'bootstrap must be first'); for (const c of p.claims ?? []) state.claims.set(c.agentId, { ...c }); for (const w of p.workItems ?? []) state.work.set(w.id, { ...w }); }
    else if (e.type === 'CLAIM_REQUEST') { const c = p.claim; if (!c?.agentId) fail('SWARM_EVENT_STATE_CONFLICT', 'claim missing'); for (const x of activeClaims(state)) if (x.agentId !== c.agentId && collides(c, x)) fail('AGENT_COLLISION_DETECTED', `${c.agentId} conflicts with ${x.agentId}`); state.claims.set(c.agentId, { ...c, status: 'active' }); }
    else if (e.type === 'HEARTBEAT') { const c = state.claims.get(e.agentId); if (!c || c.status !== 'active') fail('SWARM_OCC_CONFLICT', `no active claim for ${e.agentId}`); c.lastHeartbeatAt = e.timestamp; c.leaseUntil = p.leaseUntil; c.lastReanchorSha = e.parentSha; }
    else if (e.type === 'CHECK_OUT' || e.type === 'HANDOFF_PENDING') { const c = state.claims.get(e.agentId); if (!c || !['active', 'handoff-pending'].includes(c.status)) fail('SWARM_OCC_CONFLICT', `no releasable claim for ${e.agentId}`); c.status = e.type === 'HANDOFF_PENDING' ? 'handoff-pending' : 'released'; c.releasedAt = e.timestamp; if (p.handoffTo) c.handoffTo = p.handoffTo; }
    else if (e.type === 'BID_REQUEST') { if (!state.work.has(p.workItemId)) fail('SWARM_EVENT_STATE_CONFLICT', `unknown work item ${p.workItemId}`); const list = state.bids.get(p.workItemId) ?? []; if (list.some((b) => b.agentId === e.agentId && b.timestamp === p.timestamp)) fail('SWARM_EVENT_STATE_CONFLICT', 'duplicate bid'); list.push({ agentId: e.agentId, timestamp: p.timestamp }); state.bids.set(p.workItemId, list); }
    else if (e.type === 'CLAIM_AWARDED') { const item = state.work.get(p.workItemId); if (!item) fail('SWARM_EVENT_STATE_CONFLICT', `unknown work item ${p.workItemId}`); const winner = [...(state.bids.get(p.workItemId) ?? [])].sort((a, b) => a.timestamp.localeCompare(b.timestamp) || a.agentId.localeCompare(b.agentId))[0]; if (!winner || winner.agentId !== p.agentId) fail('SWARM_EVENT_STATE_CONFLICT', 'award violates deterministic tie-break'); item.status = 'in_progress'; item.ownerAgentId = p.agentId; }
    else if (e.type === 'EXPIRED_EVICTED') { const c = state.claims.get(p.agentId); if (c) { c.status = 'released'; c.releasedAt = e.timestamp; c.eviction = 'expired_evicted'; } const item = p.workItemId ? state.work.get(p.workItemId) : null; if (item) { item.status = 'available'; item.ownerAgentId = null; } }
    else fail('SWARM_EVENT_SCHEMA_ERROR', `unsupported type ${e.type}`);
    prev = e.hash; state.lastHash = e.hash; seq += 1;
  }
  return state;
}
function event(type, parentSha, agentId, payload, sequence, prevHash, timestamp = new Date().toISOString()) { const unsigned = { schemaVersion: 1, protocol: 'FLIXO swarm event ledger', sequence, eventId: randomUUID(), timestamp, parentSha, agentId, type, payload, prevHash }; const h = sha(canonical(unsigned)); const e = { ...unsigned, hash: h }; if (KEY) e.signature = createHmac('sha256', KEY).update(h).digest('hex'); return e; }
async function append(e) { await mkdir(dirname(LEDGER), { recursive: true }); const now = await readEvents(); if (now.length + 1 !== e.sequence || (now.at(-1)?.hash ?? 'GENESIS') !== e.prevHash) fail('SWARM_OCC_CONFLICT', 'ledger changed concurrently; reload required'); await appendFile(LEDGER, `${JSON.stringify(e)}\n`, { flag: 'a' }); }
async function sweep(state) { const events = await readEvents(); let seq = events.length + 1; const out = []; for (const c of activeClaims(state)) { if (Date.now() > iso(c.leaseUntil) || Date.now() - iso(c.lastHeartbeatAt ?? c.leasedAt) > HEARTBEAT_MS) { const item = [...state.work.values()].find((w) => w.ownerAgentId === c.agentId); const e = event('EXPIRED_EVICTED', HEAD, 'swarm-engine', { agentId: c.agentId, workItemId: item?.id ?? null, reason: Date.now() > iso(c.leaseUntil) ? 'lease_ttl_exceeded' : 'heartbeat_timeout' }, seq++, events.at(-1)?.hash ?? 'GENESIS'); await append(e); events.push(e); out.push(e); } } return out; }
async function dryRun(state) { const paths = (process.env.FLIXO_AGENT_PATHS ?? '').split(',').map((x) => x.replace(/^\.\//u, '').replace(/\/+$/u, '')).filter(Boolean); const contracts = (process.env.FLIXO_AGENT_CONTRACTS ?? '').split(',').map((x) => x.trim()).filter(Boolean); const roots = (process.env.FLIXO_AGENT_ROOT_CAUSES ?? '').split(',').map((x) => x.trim()).filter(Boolean); const fake = { scope: { paths, contracts }, rootCauseIds: roots }; const conflicts = activeClaims(state).filter((c) => c.agentId !== AGENT && ((fake.scope.paths ?? []).some((p) => (c.scope.paths ?? []).some((q) => overlap(p, q))) || contracts.some((x) => (c.scope.contracts ?? []).includes(x)) || roots.some((x) => (c.rootCauseIds ?? []).includes(x)))); const result = { mode: 'dry-run', result: conflicts.length ? 'FAIL' : 'PASS', conflicts: conflicts.map((c) => c.agentId), parentSha: HEAD }; console.log(JSON.stringify(result, null, 2)); if (conflicts.length) process.exitCode = 1; }
async function mutate(action) { if (!HEX.test(HEAD) || !git('rev-parse', 'HEAD') || git('rev-parse', 'HEAD') !== HEAD) fail('SWARM_OCC_CONFLICT', 'parent SHA must equal current HEAD for mutation'); if (!AGENT || !BRANCH_RE.test(BRANCH)) fail('SWARM_OCC_CONFLICT', 'valid agent identity and agent branch required'); let state = reduce(await readEvents()); await sweep(state); state = reduce(await readEvents()); const events = await readEvents(); const seq = events.length + 1; const prev = events.at(-1)?.hash ?? 'GENESIS'; const existing = state.claims.get(AGENT);
  if (action === 'check-in') { if (existing?.status === 'active' && iso(existing.leaseUntil) > Date.now()) fail('SWARM_OCC_CONFLICT', `${AGENT} already active`); const claim = { agentId: AGENT, branch: BRANCH, observedHeadSha: HEAD, scope: { paths: [...new Set((process.env.FLIXO_AGENT_PATHS ?? '').split(',').map((x) => x.replace(/^\.\//u, '').replace(/\/+$/u, '')).filter(Boolean))], contracts: [...new Set((process.env.FLIXO_AGENT_CONTRACTS ?? '').split(',').map((x) => x.trim()).filter(Boolean))] }, rootCauseIds: [...new Set((process.env.FLIXO_AGENT_ROOT_CAUSES ?? '').split(',').map((x) => x.trim()).filter(Boolean))], status: 'active', leasedAt: new Date().toISOString(), leaseUntil: new Date(Date.now() + LEASE_MS).toISOString(), lastHeartbeatAt: new Date().toISOString(), sessionId: randomUUID() }; if (!claim.scope.paths.length && !claim.scope.contracts.length && !claim.rootCauseIds.length) fail('SWARM_OCC_CONFLICT', 'empty claim scope'); const collision = activeClaims(state).filter((c) => c.agentId !== AGENT && (claim.scope.paths.some((p) => (c.scope.paths ?? []).some((q) => overlap(p, q))) || claim.scope.contracts.some((x) => (c.scope.contracts ?? []).includes(x)) || claim.rootCauseIds.some((x) => (c.rootCauseIds ?? []).includes(x)))); if (collision.length) fail('AGENT_COLLISION_DETECTED', collision.map((c) => c.agentId).sort().join(',')); const e = event('CLAIM_REQUEST', HEAD, AGENT, { claim }, seq, prev); await append(e); console.log(`CHECK_IN PASS seq=${seq} hash=${e.hash}`); }
  else if (action === 'heartbeat') { if (!existing || existing.status !== 'active') fail('SWARM_OCC_CONFLICT', 'active claim required'); const e = event('HEARTBEAT', HEAD, AGENT, { leaseUntil: new Date(Date.now() + LEASE_MS).toISOString() }, seq, prev); await append(e); console.log(`HEARTBEAT PASS seq=${seq} hash=${e.hash}`); }
  else if (action === 'check-out' || action === 'handoff') { if (!existing || !['active', 'handoff-pending'].includes(existing.status)) fail('SWARM_OCC_CONFLICT', 'releasable claim required'); const e = event(action === 'handoff' ? 'HANDOFF_PENDING' : 'CHECK_OUT', HEAD, AGENT, { handoffTo: process.env.FLIXO_AGENT_HANDOFF_TO ?? null }, seq, prev); await append(e); console.log(`${action.toUpperCase()} PASS seq=${seq} hash=${e.hash}`); }
  else if (action === 'bid') { const q = JSON.parse(await readFile(QUEUE, 'utf8')); const item = q.items.find((x) => x.id === process.env.FLIXO_WORK_ITEM_ID); if (!item) fail('SWARM_EVENT_STATE_CONFLICT', 'unknown work item'); if (!['available', 'in_progress'].includes(item.status)) fail('SWARM_EVENT_STATE_CONFLICT', 'work item not available'); const e = event('BID_REQUEST', HEAD, AGENT, { workItemId: item.id, timestamp: new Date().toISOString() }, seq, prev); await append(e); console.log(`BID PASS seq=${seq} hash=${e.hash}`); }
  else fail('SWARM_EVENT_SCHEMA_ERROR', `unsupported action ${action}`); }
async function smoke() { if (!HEX.test(HEAD) || git('rev-parse', 'HEAD') !== HEAD) fail('SWARM_OCC_CONFLICT', 'smoke test requires exact HEAD'); const bids = [{ agentId: 'agent-b', timestamp: '2026-09-07T20:00:00.000Z' }, { agentId: 'agent-a', timestamp: '2026-09-07T20:00:00.000Z' }, { agentId: 'agent-c', timestamp: '2026-09-07T20:00:01.000Z' }]; const sorted = [...bids].sort((a, b) => a.timestamp.localeCompare(b.timestamp) || a.agentId.localeCompare(b.agentId)); if (sorted[0].agentId !== 'agent-a') fail('SWARM_TIE_BREAK_ERROR', 'timestamp/agentId ordering broken'); const c1 = { agentId: 'a', scope: { paths: ['scripts/ci/a'] }, rootCauseIds: [] }; const c2 = { agentId: 'b', scope: { paths: ['scripts/ci/a/x'] }, rootCauseIds: [] }; if (!overlap(c1.scope.paths[0], c2.scope.paths[0])) fail('SWARM_COLLISION_TEST_ERROR', 'path overlap not detected'); console.log(JSON.stringify({ result: 'PASS', deterministicWinner: sorted[0].agentId, collisionIsolation: 'PASS', exactHead: HEAD }, null, 2)); }
const argv = new Set(process.argv.slice(2)); if (argv.has('--smoke-test')) await smoke(); else { const actionName = argv.has('--dry-run') ? 'dry-run' : process.env.FLIXO_AGENT_ACTION ?? 'status'; if (actionName === 'status') { const s = reduce(await readEvents()); console.log(JSON.stringify({ result: 'PASS', headSha: HEAD, activeClaims: activeClaims(s).map((c) => c.agentId), sequence: (await readEvents()).length }, null, 2)); } else if (actionName === 'sweep') { const s = reduce(await readEvents()); console.log(JSON.stringify({ result: 'PASS', evicted: (await sweep(s)).length }, null, 2)); } else if (actionName === 'dry-run') await dryRun(reduce(await readEvents())); else await mutate(actionName); }
