import type { Locale } from '../lib/i18n/config';
import { localizeMsUkToolTitle } from '../lib/i18n/ms-uk-tool-title.ts';
import { TOOL_SEO_NAMES } from '../lib/i18n/tool-seo-localization.ts';
import type { ToolConfig } from './tool-definitions/types';

/** Human-reviewed additions for ready tools absent from the historical locale dictionaries. */
const REVIEWED_TOOL_SEO_OVERRIDES: Partial<Record<Locale, Record<string, string>>> = {
  ms: {
    'image-compressor': 'Pemampat Imej',
    'background-remover': 'Penyingkir Latar Belakang',
    'image-upscaler': 'Peningkat Resolusi Imej',
    'image-converter': 'Penukar Imej',
    'object-remover': 'Penyingkir Objek',
    'watermark-remover': 'Penyingkir Tanda Air',
    'image-cropper': 'Pemotong Imej',
    'image-to-svg': 'Penukar Imej kepada SVG',
    'image-ocr': 'OCR Imej kepada Teks',
    'background-blur': 'Kabur Latar Belakang',
    'passport-photo-maker': 'Pembuat Foto Pasport',
    'watermark-adder': 'Penambah Tanda Air',
    'meme-generator': 'Penjana Meme',
    'collage-maker': 'Pembuat Kolaj',
    'image-effects': 'Kesan Imej',
    'exif-cleaner': 'Pembersih Metadata EXIF',
    'svg-optimizer': 'Pengoptimum SVG',
    'mockup-generator': 'Penjana Mockup',
    seed: 'Alat Seed',
    pix: 'Studio Pix',
    'pdf-merger-splitter': 'Penggabung dan Pemisah PDF',
    'pdf-compressor': 'Pemampat PDF',
    'image-to-pdf': 'Penukar Imej kepada PDF',
    'pdf-unlock-protect': 'Buka Kunci dan Lindungi PDF',
    'pdf-to-text': 'Penukar PDF kepada Teks',
    'audio-extractor-muter': 'Pengekstrak dan Pembisukan Audio',
    'audio-cutter-trimmer': 'Pemotong dan Perapi Audio',
    'audio-compressor': 'Pemampat Audio',
    'audio-noise-reducer': 'Pengurang Bunyi Audio',
    'video-trimmer-splitter': 'Perapi dan Pemisah Video',
    'video-gif-meme': 'Penukar Video kepada GIF dan Pembuat Meme',
    'video-compressor-converter': 'Pemampat dan Penukar Video',
    'ai-captioner-srt': 'Penjana Kapsyen AI dan SRT Automatik',
    'ai-vocal-instrumental-remover': 'Penyingkir Vokal dan Instrumental AI',
    'ai-image-generator': 'Penjana Imej AI',
    'word-character-counter': 'Pengira Perkataan dan Aksara',
    'text-diff-checker': 'Pemeriksa Perbezaan Teks',
    'case-converter': 'Penukar Huruf',
    'qr-generator-reader': 'Penjana dan Pembaca Kod QR',
    'password-generator': 'Penjana Kata Laluan',
    'aspect-ratio-calculator': 'Kalkulator Nisbah Aspek',
    'json-formatter-validator': 'Pemformat dan Pengesah JSON',
    'base64-encoder-decoder': 'Pengekod dan Penyahkod Base64',
    'color-picker-palette': 'Pemilih Warna dan Penjana Palet',
    'regex-tester': 'Penguji dan Penyahpepijat Regex',
    'hash-generator': 'Penjana Hash',
  },
  uk: {
    'image-compressor': 'Компресор зображень',
    'background-remover': 'Видалення фону',
    'image-upscaler': 'Збільшувач зображень',
    'image-converter': 'Конвертер зображень',
    'object-remover': 'Видалення об’єктів',
    'watermark-remover': 'Видалення водяних знаків',
    'image-cropper': 'Обрізувач зображень',
    'image-to-svg': 'Конвертер зображень у SVG',
    'image-ocr': 'OCR зображення в текст',
    'background-blur': 'Розмиття фону',
    'passport-photo-maker': 'Створювач фото на паспорт',
    'watermark-adder': 'Додавання водяних знаків',
    'meme-generator': 'Генератор мемів',
    'collage-maker': 'Створювач колажів',
    'image-effects': 'Ефекти зображень',
    'exif-cleaner': 'Очищення метаданих EXIF',
    'svg-optimizer': 'Оптимізатор SVG',
    'mockup-generator': 'Генератор мокапів',
    seed: 'Інструмент Seed',
    pix: 'Студія Pix',
    'pdf-merger-splitter': 'Об’єднання та розділення PDF',
    'pdf-compressor': 'Компресор PDF',
    'image-to-pdf': 'Конвертер зображень у PDF',
    'pdf-unlock-protect': 'Розблокування та захист PDF',
    'pdf-to-text': 'Конвертер PDF у текст',
    'audio-extractor-muter': 'Екстрактор та вимкнення звуку',
    'audio-cutter-trimmer': 'Обрізувач та тример аудіо',
    'audio-compressor': 'Компресор аудіо',
    'audio-noise-reducer': 'Зменшення шуму аудіо',
    'video-trimmer-splitter': 'Тример та розділювач відео',
    'video-gif-meme': 'Конвертер відео в GIF та генератор мемів',
    'video-compressor-converter': 'Компресор та конвертер відео',
    'ai-captioner-srt': 'AI-генератор автоматичних субтитрів і SRT',
    'ai-vocal-instrumental-remover': 'AI-видалення вокалу та інструменталу',
    'ai-image-generator': 'AI-генератор зображень',
    'word-character-counter': 'Лічильник слів та символів',
    'text-diff-checker': 'Перевірка відмінностей тексту',
    'case-converter': 'Конвертер регістру',
    'qr-generator-reader': 'Генератор та читач QR-кодів',
    'password-generator': 'Генератор паролів',
    'aspect-ratio-calculator': 'Калькулятор співвідношення сторін',
    'json-formatter-validator': 'Форматер та валідатор JSON',
    'base64-encoder-decoder': 'Кодувальник та декодувальник Base64',
    'color-picker-palette': 'Вибір кольору та генератор палітри',
    'regex-tester': 'Тестер та налагоджувач Regex',
    'hash-generator': 'Генератор хешів',
  },
};

/** Resolve reviewed SEO names without statically importing locale dictionaries. */
export function getAuthoritativeToolSeoName(tool: ToolConfig, locale: Locale): string | undefined {
  const reviewed = REVIEWED_TOOL_SEO_OVERRIDES[locale]?.[tool.id];
  if (typeof reviewed === 'string' && reviewed.trim()) return reviewed;

  const legacy = TOOL_SEO_NAMES[tool.id]?.[locale];
  if (typeof legacy === 'string' && legacy.trim()) return legacy;

  return localizeMsUkToolTitle(locale, tool.title);
}
