import assert from "node:assert/strict";
import test from "node:test";
import { AgentCognitiveLedger, ConfidenceCalibrator, FailureIntelligence } from "../src/cognitive.ts";
test("records cognitive state and verified decisions",()=>{ const l=new AgentCognitiveLedger(); const s=l.upsertState({commandId:"cmd-1",stepId:"step-1",agentId:"architect",goal:"verify boundaries",hypotheses:["boundary valid"],assumptions:["contracts canonical"],plannedActions:["inspect"],observations:["legacy import"],evidence:["gate"],uncertainties:["generated code"],detectedRisks:["cross-app"],rejectedApproaches:["bypass"],confidence:.84,verificationState:"pending"}); assert.equal(s.confidence,.84); const d=l.recordDecision({commandId:"cmd-1",stepId:"step-1",agentId:"architect",decision:"keep boundary",alternatives:["move package"],evidence:["gate"],confidence:.84,verificationState:"pending"}); l.verifyDecision(d.id,"verified","gate passed",91); const x=l.snapshot(); assert.equal(x.states.length,1); assert.equal(x.decisions[0].verificationState,"verified"); assert.equal(x.decisions[0].reward,91); assert.equal(x.events.length,3); });
test("calibrates confidence",()=>{ const c=new ConfidenceCalibrator(); c.record("tester",.9,true); c.record("tester",.8,false); const r=c.summarize("tester"); assert.equal(r.sampleCount,2); assert.equal(r.empiricalAccuracy,.5); assert.equal(r.averageConfidence,.85); assert.equal(r.absoluteCalibrationError,.35); });
test("rejects invalid confidence",()=>{ const c=new ConfidenceCalibrator(); assert.throws(()=>c.record("tester",1.1,true),/INVALID_CONFIDENCE/); });
import { DirectCommandOrchestrator } from "../src/index.ts";

test("orchestrator exposes execution cognitive trace",async()=>{ const o=new DirectCommandOrchestrator({ async plan(command,objective){ return {commandId:command.commandId,objective,steps:[{stepId:"step-1",role:"tester",objective,dependsOn:[],constraints:[]}]}; }}); o.registerWorker({id:"tester",async run(i){return {stepId:i.stepId,commandId:i.commandId,status:"completed",summary:"verified test result"};}}); await o.dispatch({commandId:"cmd-trace",issuedBy:"human",issuedAt:new Date().toISOString()},"verify"); const s=o.cognitiveSnapshot(); assert.equal(s.states.length,1); assert.equal(s.events.filter(e=>e.type==="observation").length,1); assert.equal(s.events.find(e=>e.type==="observation")?.agentId,"tester"); });

test("classifies verified execution failures into corrective patterns",()=>{ const f=new FailureIntelligence(); const rows=f.classify("cmd-2","step-2","security",{testsPassed:1,testsFailed:2,securityFindings:1,evidenceVerified:false,outOfScopeActions:0,delegatedTasks:0}); assert.equal(rows.length,3); assert.ok(f.patterns("security").includes("verification-test-failure")); assert.ok(f.patterns("security").includes("security-findings-present")); });

test("normalizes failure taxonomy and aggregates recurrence",()=>{ const f=new FailureIntelligence(); f.classify("c1","s1","tester",{testsPassed:1,testsFailed:2,evidenceVerified:false}); f.classify("c2","s2","tester",{testsPassed:1,testsFailed:1,evidenceVerified:false}); const a=f.aggregates("tester")[0]; assert.equal(a.pattern,"verification-test-failure"); assert.equal(a.occurrences,2); assert.equal(a.maxSeverity,"high"); });
