import { lazy } from 'react';
import type { ToolConfig } from './types';

export const OTHER_TOOLS: readonly ToolConfig[] = Object.freeze([
  { id: 'word-character-counter', title: 'Word & Character Counter', path: '/en/word-character-counter', description: 'Count words, characters, sentences, paragraphs, reading time, speaking time, and keyword density locally.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/word-character-counter').then((m) => ({ default: m.WordCharacterCounterTool }))) },
  { id: 'text-diff-checker', title: 'Text Diff Checker', path: '/en/text-diff-checker', description: 'Compare two texts locally with inline or side-by-side differences.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/text-diff-checker').then((m) => ({ default: m.TextDiffCheckerTool }))) },
  { id: 'case-converter', title: 'Case Converter', path: '/en/case-converter', description: 'Convert text between common letter and identifier cases locally.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/case-converter').then((m) => ({ default: m.CaseConverterTool }))) },
  { id: 'qr-generator-reader', title: 'QR Code Generator & Reader', path: '/en/qr-generator-reader', description: 'Generate QR codes and read QR images locally in your browser.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/qr-generator-reader').then((m) => ({ default: m.QrGeneratorReaderTool }))) },
  { id: 'password-generator', title: 'Password Generator', path: '/en/password-generator', description: 'Generate secure passwords locally with Web Crypto.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/password-generator').then((m) => ({ default: m.PasswordGeneratorTool }))) },
  { id: 'aspect-ratio-calculator', title: 'Aspect Ratio Calculator', path: '/en/aspect-ratio-calculator', description: 'Calculate proportional dimensions and common aspect ratios locally.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/aspect-ratio-calculator').then((m) => ({ default: m.AspectRatioCalculatorTool }))) },
  { id: 'json-formatter-validator', title: 'JSON Formatter & Validator', path: '/en/json-formatter-validator', description: 'Validate, format, inspect, convert, copy, and download JSON locally.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/json-formatter-validator').then((m) => ({ default: m.JsonFormatterValidatorTool }))) },
  { id: 'base64-encoder-decoder', title: 'Base64 Encoder / Decoder', path: '/en/base64-encoder-decoder', description: 'Encode and decode text and files locally with browser APIs.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/base64-encoder-decoder').then((m) => ({ default: m.Base64EncoderDecoderTool }))) },
  { id: 'color-picker-palette', title: 'Color Picker & Palette Generator', path: '/en/color-picker-palette', description: 'Pick colors, generate palettes, and check WCAG contrast locally.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/color-picker-palette').then((m) => ({ default: m.ColorPickerPaletteTool }))) },
  { id: 'regex-tester', title: 'Regex Tester & Debugger', path: '/en/regex-tester', description: 'Test JavaScript regular expressions locally with live matches and capture groups.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/regex-tester').then((m) => ({ default: m.RegexTesterTool }))) },
  { id: 'hash-generator', title: 'Hash Generator', path: '/en/hash-generator', description: 'Generate SHA-256, SHA-384, and SHA-512 hashes locally with Web Crypto.', category: 'Other', isReady: true, component: lazy(() => import('@/tools/hash-generator').then((m) => ({ default: m.HashGeneratorTool }))) },
]);
