import type { Locale } from './config';

type LocaleMap = Readonly<Partial<Record<Locale, string>>>;

export const AI_CAPTIONER_UI: Readonly<Record<string, LocaleMap>> = {
  'AI Auto-Captioner & SRT Generator': { ar: 'مولد التسميات التلقائية للذكاء الاصطناعي وSRT', es: 'Generador de subtítulos automáticos con IA y SRT', fr: 'Générateur automatique de sous-titres IA et SRT', de: 'KI-Autountertitel- und SRT-Generator', hi: 'एआई ऑटो-कैप्शनर और SRT जनरेटर', id: 'Generator Keterangan Otomatis AI & SRT', it: 'Generatore automatico di sottotitoli IA e SRT', ja: 'AI自動字幕・SRTジェネレーター', ko: 'AI 자동 자막 및 SRT 생성기', ms: 'Penjana Kapsyen Automatik AI & SRT', nl: 'AI-automatische ondertitel- en SRT-generator', pl: 'Generator automatycznych napisów AI i SRT', pt: 'Gerador automático de legendas IA e SRT', ru: 'Генератор автосубтитров ИИ и SRT', sv: 'AI-generator för automatiska undertexter och SRT', th: 'เครื่องสร้างคำบรรยายอัตโนมัติ AI และ SRT', tr: 'Yapay Zeka Otomatik Altyazı ve SRT Oluşturucu', uk: 'Генератор автоматичних субтитрів ШІ та SRT', vi: 'Trình tạo phụ đề tự động AI và SRT' },
  'Transcribe short media locally with Whisper and generate timestamped SRT/VTT captions.': { ar: 'حوّل الوسائط القصيرة إلى نص محليًا باستخدام Whisper وأنشئ تسميات SRT/VTT بوقت زمني.', es: 'Transcribe medios cortos localmente con Whisper y genera subtítulos SRT/VTT con marcas de tiempo.', fr: 'Transcrivez localement de courts médias avec Whisper et générez des sous-titres SRT/VTT horodatés.', de: 'Transkribieren Sie kurze Medien lokal mit Whisper und erzeugen Sie zeitcodierte SRT/VTT-Untertitel.', hi: 'Whisper के साथ छोटे मीडिया को स्थानीय रूप से ट्रांसक्राइब करें और टाइमस्टैम्प वाले SRT/VTT कैप्शन बनाएं।', id: 'Transkripsikan media pendek secara lokal dengan Whisper dan buat keterangan SRT/VTT bertanda waktu.', it: 'Trascrivi brevi contenuti multimediali localmente con Whisper e genera sottotitoli SRT/VTT con timestamp.', ja: 'Whisperで短いメディアをローカル転写し、タイムスタンプ付きSRT/VTT字幕を生成します。', ko: 'Whisper로 짧은 미디어를 로컬에서 전사하고 타임스탬프가 있는 SRT/VTT 자막을 생성합니다.', ms: 'Transkripsikan media pendek secara setempat dengan Whisper dan jana kapsyen SRT/VTT bertanda masa.', nl: 'Transcribeer korte media lokaal met Whisper en genereer SRT/VTT-ondertitels met tijdcodes.', pl: 'Transkrybuj krótkie multimedia lokalnie za pomocą Whisper i twórz napisy SRT/VTT ze znacznikami czasu.', pt: 'Transcreva mídias curtas localmente com Whisper e gere legendas SRT/VTT com marcação de tempo.', ru: 'Локально транскрибируйте короткие медиа с Whisper и создавайте субтитры SRT/VTT с временными метками.', sv: 'Transkribera kort media lokalt med Whisper och skapa tidsstämplade SRT/VTT-undertexter.', th: 'ถอดเสียงสื่อสั้นในเครื่องด้วย Whisper และสร้างคำบรรยาย SRT/VTT พร้อมการประทับเวลา', tr: 'Kısa medyayı Whisper ile yerel olarak yazıya dönüştürün ve zaman damgalı SRT/VTT altyazıları oluşturun.', uk: 'Транскрибуйте короткі медіа локально за допомогою Whisper і створюйте субтитри SRT/VTT з часовими мітками.', vi: 'Chuyển âm thanh/video ngắn thành văn bản cục bộ bằng Whisper và tạo phụ đề SRT/VTT có dấu thời gian.' },
  'Choose video or audio': { ar: 'اختر فيديو أو صوتًا', es: 'Elegir vídeo o audio', fr: 'Choisir une vidéo ou un audio', de: 'Video oder Audio auswählen', hi: 'वीडियो या ऑडियो चुनें', id: 'Pilih video atau audio', it: 'Scegli video o audio', ja: '動画または音声を選択', ko: '비디오 또는 오디오 선택', ms: 'Pilih video atau audio', nl: 'Video of audio kiezen', pl: 'Wybierz wideo lub audio', pt: 'Escolher vídeo ou áudio', ru: 'Выберите видео или аудио', sv: 'Välj video eller ljud', th: 'เลือกวิดีโอหรือเสียง', tr: 'Video veya ses seçin', uk: 'Виберіть відео або аудіо', vi: 'Chọn video hoặc âm thanh' },
  'Media file': { ar: 'ملف وسائط', es: 'Archivo multimedia', fr: 'Fichier multimédia', de: 'Mediendatei', hi: 'मीडिया फ़ाइल', id: 'File media', it: 'File multimediale', ja: 'メディアファイル', ko: '미디어 파일', ms: 'Fail media', nl: 'Mediabestand', pl: 'Plik multimedialny', pt: 'Ficheiro multimédia', ru: 'Медиафайл', sv: 'Mediefil', th: 'ไฟล์สื่อ', tr: 'Medya dosyası', uk: 'Медіафайл', vi: 'Tệp phương tiện' },
  'Inference device': { ar: 'جهاز الاستدلال', es: 'Dispositivo de inferencia', fr: 'Appareil d’inférence', de: 'Inferenzgerät', hi: 'इंफरेंस डिवाइस', id: 'Perangkat inferensi', it: 'Dispositivo di inferenza', ja: '推論デバイス', ko: '추론 장치', ms: 'Peranti inferens', nl: 'Inferentieapparaat', pl: 'Urządzenie wnioskowania', pt: 'Dispositivo de inferência', ru: 'Устройство инференса', sv: 'Inferensenhet', th: 'อุปกรณ์อนุมาน', tr: 'Çıkarım cihazı', uk: 'Пристрій інференсу', vi: 'Thiết bị suy luận' },
  'Generate captions…': { ar: 'جارٍ إنشاء التسميات…', es: 'Generando subtítulos…', fr: 'Génération des sous-titres…', de: 'Untertitel werden erstellt…', hi: 'कैप्शन जनरेट हो रहे हैं…', id: 'Membuat keterangan…', it: 'Generazione sottotitoli…', ja: '字幕を生成中…', ko: '자막 생성 중…', ms: 'Menjana kapsyen…', nl: 'Ondertitels genereren…', pl: 'Generowanie napisów…', pt: 'A gerar legendas…', ru: 'Создание субтитров…', sv: 'Genererar undertexter…', th: 'กำลังสร้างคำบรรยาย…', tr: 'Altyazılar oluşturuluyor…', uk: 'Створення субтитрів…', vi: 'Đang tạo phụ đề…' },
  'Generate captions': { ar: 'إنشاء التسميات التوضيحية', es: 'Generar subtítulos', fr: 'Générer les sous-titres', de: 'Untertitel generieren', hi: 'कैप्शन जनरेट करें', id: 'Buat keterangan', it: 'Genera sottotitoli', ja: '字幕を生成', ko: '자막 생성', ms: 'Jana kapsyen', nl: 'Ondertitels genereren', pl: 'Generuj napisy', pt: 'Gerar legendas', ru: 'Создать субтитры', sv: 'Generera undertexter', th: 'สร้างคำบรรยาย', tr: 'Altyazı oluştur', uk: 'Створити субтитри', vi: 'Tạo phụ đề' },
  Transcript: { ar: 'النص المفرغ', es: 'Transcripción', fr: 'Transcription', de: 'Transkript', hi: 'प्रतिलिपि', id: 'Transkrip', it: 'Trascrizione', ja: '文字起こし', ko: '스크립트', ms: 'Transkrip', nl: 'Transcript', pl: 'Transkrypcja', pt: 'Transcrição', ru: 'Транскрипция', sv: 'Transkription', th: 'ข้อความถอดเสียง', tr: 'Döküm', uk: 'Транскрипція', vi: 'Bản chép lời' },
  'Download SRT': { ar: 'تنزيل SRT', es: 'Descargar SRT', fr: 'Télécharger SRT', de: 'SRT herunterladen', hi: 'SRT डाउनलोड करें', id: 'Unduh SRT', it: 'Scarica SRT', ja: 'SRTをダウンロード', ko: 'SRT 다운로드', ms: 'Muat turun SRT', nl: 'SRT downloaden', pl: 'Pobierz SRT', pt: 'Transferir SRT', ru: 'Скачать SRT', sv: 'Ladda ner SRT', th: 'ดาวน์โหลด SRT', tr: 'SRT indir', uk: 'Завантажити SRT', vi: 'Tải SRT xuống' },
  'Download VTT': { ar: 'تنزيل VTT', es: 'Descargar VTT', fr: 'Télécharger VTT', de: 'VTT herunterladen', hi: 'VTT डाउनलोड करें', id: 'Unduh VTT', it: 'Scarica VTT', ja: 'VTTをダウンロード', ko: 'VTT 다운로드', ms: 'Muat turun VTT', nl: 'VTT downloaden', pl: 'Pobierz VTT', pt: 'Transferir VTT', ru: 'Скачать VTT', sv: 'Ladda ner VTT', th: 'ดาวน์โหลด VTT', tr: 'VTT indir', uk: 'Завантажити VTT', vi: 'Tải VTT xuống' },
};
