import type { Locale } from './config';

type LocaleMap = Readonly<Partial<Record<Locale, string>>>;

const UI: Record<string, LocaleMap> = {
  'Audio Cutter & Trimmer': { ar:'قص وتشذيب الصوت', es:'Cortador y recortador de audio', fr:'Découpeur et éditeur audio', de:'Audio-Schneider und Trimmer', hi:'ऑडियो कटर और ट्रिमर', id:'Pemotong & Pemangkas Audio', it:'Taglia e rifinisci audio', ja:'オーディオカッター＆トリマー', ko:'오디오 커터 및 트리머', ms:'Pemotong & Pemangkas Audio', nl:'Audiocutter en trimmer', pl:'Przycinanie i cięcie audio', pt:'Cortador e aparador de áudio', ru:'Обрезка и редактирование аудио', sv:'Ljudklippare och trimmer', th:'เครื่องตัดและตัดแต่งเสียง', tr:'Ses Kesici ve Kırpıcı', uk:'Обрізувач і редактор аудіо', vi:'Cắt và chỉnh sửa âm thanh' },
  'Cut audio locally with precise start/end controls and a waveform preview.': { ar:'اقطع الصوت محليًا باستخدام تحكم دقيق بالبداية والنهاية ومعاينة للموجة الصوتية.', es:'Corta audio localmente con controles precisos de inicio/fin y una vista previa de la forma de onda.', fr:'Découpez l’audio localement avec des contrôles précis de début/fin et un aperçu de la forme d’onde.', de:'Audio lokal mit präzisen Start-/Endkontrollen und Wellenformvorschau schneiden.', hi:'सटीक शुरुआत/अंत नियंत्रण और वेवफॉर्म पूर्वावलोकन के साथ ऑडियो को स्थानीय रूप से काटें।', id:'Potong audio secara lokal dengan kontrol awal/akhir yang presisi dan pratinjau bentuk gelombang.', it:'Taglia l’audio localmente con controlli precisi di inizio/fine e anteprima della forma d’onda.', ja:'正確な開始/終了コントロールと波形プレビューで音声をローカルにカットします。', ko:'정확한 시작/끝 제어와 파형 미리보기로 오디오를 로컬에서 자릅니다.', ms:'Potong audio secara tempatan dengan kawalan mula/akhir yang tepat dan pratonton bentuk gelombang.', nl:'Knip audio lokaal met nauwkeurige begin-/eindbediening en een golfvormvoorbeeld.', pl:'Przycinaj audio lokalnie z precyzyjnymi punktami początku/końca i podglądem przebiegu fali.', pt:'Corte o áudio localmente com controles precisos de início/fim e pré-visualização da forma de onda.', ru:'Обрезайте аудио локально с точными настройками начала/конца и предпросмотром волны.', sv:'Klipp ljud lokalt med exakta start-/slutkontroller och en vågformsförhandsvisning.', th:'ตัดเสียงในเครื่องด้วยการควบคุมจุดเริ่มต้น/สิ้นสุดที่แม่นยำและตัวอย่างคลื่นเสียง', tr:'Kesin başlangıç/bitiş denetimleri ve dalga biçimi önizlemesiyle sesi yerel olarak kesin.', uk:'Обрізайте аудіо локально з точними налаштуваннями початку/кінця та попереднім переглядом хвилі.', vi:'Cắt âm thanh cục bộ với điều khiển đầu/cuối chính xác và xem trước dạng sóng.' },
  'Choose audio': { ar:'اختر صوتًا', es:'Elegir audio', fr:'Choisir un audio', de:'Audio auswählen', hi:'ऑडियो चुनें', id:'Pilih audio', it:'Scegli audio', ja:'音声を選択', ko:'오디오 선택', ms:'Pilih audio', nl:'Audio kiezen', pl:'Wybierz audio', pt:'Escolher áudio', ru:'Выбрать аудио', sv:'Välj ljud', th:'เลือกเสียง', tr:'Ses seç', uk:'Виберіть аудіо', vi:'Chọn âm thanh' },
  'Choose an audio file.': { ar:'اختر ملفًا صوتيًا.', es:'Elige un archivo de audio.', fr:'Choisissez un fichier audio.', de:'Wählen Sie eine Audiodatei.', hi:'एक ऑडियो फ़ाइल चुनें।', id:'Pilih berkas audio.', it:'Scegli un file audio.', ja:'音声ファイルを選択してください。', ko:'오디오 파일을 선택하세요.', ms:'Pilih fail audio.', nl:'Kies een audiobestand.', pl:'Wybierz plik audio.', pt:'Escolha um arquivo de áudio.', ru:'Выберите аудиофайл.', sv:'Välj en ljudfil.', th:'เลือกไฟล์เสียง', tr:'Bir ses dosyası seçin.', uk:'Виберіть аудіофайл.', vi:'Chọn tệp âm thanh.' },
  'Web Audio API is unavailable in this browser.': { ar:'واجهة Web Audio API غير متاحة في هذا المتصفح.', es:'La API Web Audio no está disponible en este navegador.', fr:'L’API Web Audio n’est pas disponible dans ce navigateur.', de:'Die Web Audio API ist in diesem Browser nicht verfügbar.', hi:'इस ब्राउज़र में Web Audio API उपलब्ध नहीं है।', id:'Web Audio API tidak tersedia di browser ini.', it:'La Web Audio API non è disponibile in questo browser.', ja:'このブラウザーでは Web Audio API を利用できません。', ko:'이 브라우저에서는 Web Audio API를 사용할 수 없습니다.', ms:'Web Audio API tidak tersedia dalam pelayar ini.', nl:'De Web Audio API is niet beschikbaar in deze browser.', pl:'Web Audio API nie jest dostępne w tej przeglądarce.', pt:'A Web Audio API não está disponível neste navegador.', ru:'Web Audio API недоступен в этом браузере.', sv:'Web Audio API är inte tillgängligt i den här webbläsaren.', th:'เบราว์เซอร์นี้ไม่รองรับ Web Audio API', tr:'Web Audio API bu tarayıcıda kullanılamıyor.', uk:'Web Audio API недоступний у цьому браузері.', vi:'Web Audio API không khả dụng trong trình duyệt này.' },
  'Decoding locally…': { ar:'جارٍ فك الترميز محليًا…', es:'Decodificando localmente…', fr:'Décodage local…', de:'Lokale Dekodierung…', hi:'स्थानीय रूप से डिकोड किया जा रहा है…', id:'Mendekode secara lokal…', it:'Decodifica locale…', ja:'ローカルでデコード中…', ko:'로컬에서 디코딩 중…', ms:'Menyahkod secara tempatan…', nl:'Lokaal decoderen…', pl:'Dekodowanie lokalne…', pt:'Decodificando localmente…', ru:'Локальное декодирование…', sv:'Avkodar lokalt…', th:'กำลังถอดรหัสในเครื่อง…', tr:'Yerel olarak kod çözülüyor…', uk:'Локальне декодування…', vi:'Đang giải mã cục bộ…' },
  'Unable to decode the audio file.': { ar:'تعذر فك ترميز ملف الصوت.', es:'No se pudo decodificar el archivo de audio.', fr:'Impossible de décoder le fichier audio.', de:'Die Audiodatei konnte nicht decodiert werden.', hi:'ऑडियो फ़ाइल को डिकोड नहीं किया जा सका।', id:'Tidak dapat mendekode berkas audio.', it:'Impossibile decodificare il file audio.', ja:'音声ファイルをデコードできません。', ko:'오디오 파일을 디코딩할 수 없습니다.', ms:'Tidak dapat menyahkod fail audio.', nl:'Kan het audiobestand niet decoderen.', pl:'Nie można zdekodować pliku audio.', pt:'Não foi possível decodificar o arquivo de áudio.', ru:'Не удалось декодировать аудиофайл.', sv:'Kunde inte avkoda ljudfilen.', th:'ไม่สามารถถอดรหัสไฟล์เสียงได้', tr:'Ses dosyasının kodu çözülemedi.', uk:'Не вдалося декодувати аудіофайл.', vi:'Không thể giải mã tệp âm thanh.' },
  'Audio waveform': { ar:'موجة الصوت', es:'Forma de onda de audio', fr:'Forme d’onde audio', de:'Audio-Wellenform', hi:'ऑडियो वेवफॉर्म', id:'Bentuk gelombang audio', it:'Forma d’onda audio', ja:'音声波形', ko:'오디오 파형', ms:'Bentuk gelombang audio', nl:'Audiogolfvorm', pl:'Przebieg fali audio', pt:'Forma de onda do áudio', ru:'Волна аудио', sv:'Ljudvågform', th:'รูปคลื่นเสียง', tr:'Ses dalga biçimi', uk:'Хвиля аудіо', vi:'Dạng sóng âm thanh' },
  Start: { ar:'البداية', es:'Inicio', fr:'Début', de:'Start', hi:'शुरुआत', id:'Mulai', it:'Inizio', ja:'開始', ko:'시작', ms:'Mula', nl:'Start', pl:'Początek', pt:'Início', ru:'Начало', sv:'Start', th:'เริ่มต้น', tr:'Başlangıç', uk:'Початок', vi:'Bắt đầu' },
  End: { ar:'النهاية', es:'Fin', fr:'Fin', de:'Ende', hi:'अंत', id:'Selesai', it:'Fine', ja:'終了', ko:'끝', ms:'Akhir', nl:'Einde', pl:'Koniec', pt:'Fim', ru:'Конец', sv:'Slut', th:'สิ้นสุด', tr:'Bitiş', uk:'Кінець', vi:'Kết thúc' },
  'Start time': { ar:'وقت البداية', es:'Hora de inicio', fr:'Heure de début', de:'Startzeit', hi:'प्रारंभ समय', id:'Waktu mulai', it:'Ora di inizio', ja:'開始時間', ko:'시작 시간', ms:'Masa mula', nl:'Starttijd', pl:'Czas początku', pt:'Hora de início', ru:'Время начала', sv:'Starttid', th:'เวลาเริ่มต้น', tr:'Başlangıç zamanı', uk:'Час початку', vi:'Thời gian bắt đầu' },
  'End time': { ar:'وقت النهاية', es:'Hora de fin', fr:'Heure de fin', de:'Endzeit', hi:'समाप्ति समय', id:'Waktu selesai', it:'Ora di fine', ja:'終了時間', ko:'종료 시간', ms:'Masa tamat', nl:'Eindtijd', pl:'Czas końca', pt:'Hora de fim', ru:'Время окончания', sv:'Sluttid', th:'เวลาสิ้นสุด', tr:'Bitiş zamanı', uk:'Час завершення', vi:'Thời gian kết thúc' },
  'Selected: ': { ar:'المحدد: ', es:'Seleccionado: ', fr:'Sélection : ', de:'Ausgewählt: ', hi:'चयनित: ', id:'Dipilih: ', it:'Selezionato: ', ja:'選択: ', ko:'선택됨: ', ms:'Dipilih: ', nl:'Geselecteerd: ', pl:'Wybrano: ', pt:'Selecionado: ', ru:'Выбрано: ', sv:'Valt: ', th:'ที่เลือก: ', tr:'Seçildi: ', uk:'Вибрано: ', vi:'Đã chọn: ' },
  'Choose a positive audio range.': { ar:'اختر نطاقًا صوتيًا أكبر من صفر.', es:'Elige un rango de audio positivo.', fr:'Choisissez une plage audio positive.', de:'Wählen Sie einen positiven Audiobereich.', hi:'एक सकारात्मक ऑडियो रेंज चुनें।', id:'Pilih rentang audio positif.', it:'Scegli un intervallo audio positivo.', ja:'正の音声範囲を選択してください。', ko:'양수인 오디오 범위를 선택하세요.', ms:'Pilih julat audio positif.', nl:'Kies een positief audiobereik.', pl:'Wybierz dodatni zakres audio.', pt:'Escolha um intervalo de áudio positivo.', ru:'Выберите положительный диапазон аудио.', sv:'Välj ett positivt ljudintervall.', th:'เลือกช่วงเสียงที่มากกว่าศูนย์', tr:'Pozitif bir ses aralığı seçin.', uk:'Виберіть додатний діапазон аудіо.', vi:'Chọn một khoảng âm thanh dương.' },
  'Rendering selected range locally…': { ar:'جارٍ إنشاء النطاق المحدد محليًا…', es:'Renderizando localmente el rango seleccionado…', fr:'Rendu local de la plage sélectionnée…', de:'Ausgewählten Bereich lokal rendern…', hi:'चयनित रेंज को स्थानीय रूप से रेंडर किया जा रहा है…', id:'Merender rentang yang dipilih secara lokal…', it:'Rendering locale dell’intervallo selezionato…', ja:'選択範囲をローカルで処理中…', ko:'선택한 범위를 로컬에서 렌더링 중…', ms:'Merender julat yang dipilih secara tempatan…', nl:'Geselecteerd bereik lokaal renderen…', pl:'Lokalne renderowanie wybranego zakresu…', pt:'Renderizando localmente o intervalo selecionado…', ru:'Локальный рендер выбранного диапазона…', sv:'Renderar valt intervall lokalt…', th:'กำลังสร้างช่วงที่เลือกในเครื่อง…', tr:'Seçilen aralık yerel olarak işleniyor…', uk:'Локальне створення вибраного діапазону…', vi:'Đang xử lý cục bộ khoảng đã chọn…' },
  Ready: { ar:'جاهز', es:'Listo', fr:'Prêt', de:'Bereit', hi:'तैयार', id:'Siap', it:'Pronto', ja:'準備完了', ko:'준비됨', ms:'Sedia', nl:'Gereed', pl:'Gotowe', pt:'Pronto', ru:'Готово', sv:'Klar', th:'พร้อม', tr:'Hazır', uk:'Готово', vi:'Sẵn sàng' },
  'Export WAV clip': { ar:'تصدير مقطع WAV', es:'Exportar clip WAV', fr:'Exporter le clip WAV', de:'WAV-Clip exportieren', hi:'WAV क्लिप निर्यात करें', id:'Ekspor klip WAV', it:'Esporta clip WAV', ja:'WAVクリップを書き出す', ko:'WAV 클립 내보내기', ms:'Eksport klip WAV', nl:'WAV-fragment exporteren', pl:'Eksportuj klip WAV', pt:'Exportar clipe WAV', ru:'Экспортировать WAV-фрагмент', sv:'Exportera WAV-klipp', th:'ส่งออกคลิป WAV', tr:'WAV klibini dışa aktar', uk:'Експортувати WAV-фрагмент', vi:'Xuất đoạn WAV' },
  Rendering…: { ar:'جارٍ المعالجة…', es:'Procesando…', fr:'Rendu…', de:'Wird verarbeitet…', hi:'रेंडर हो रहा है…', id:'Merender…', it:'Rendering…', ja:'処理中…', ko:'렌더링 중…', ms:'Merender…', nl:'Renderen…', pl:'Renderowanie…', pt:'Renderizando…', ru:'Обработка…', sv:'Renderar…', th:'กำลังประมวลผล…', tr:'İşleniyor…', uk:'Обробка…', vi:'Đang xử lý…' },
  'Unable to export the selected range.': { ar:'تعذر تصدير النطاق المحدد.', es:'No se pudo exportar el rango seleccionado.', fr:'Impossible d’exporter la plage sélectionnée.', de:'Der ausgewählte Bereich konnte nicht exportiert werden.', hi:'चयनित रेंज निर्यात नहीं की जा सकी।', id:'Tidak dapat mengekspor rentang yang dipilih.', it:'Impossibile esportare l’intervallo selezionato.', ja:'選択した範囲を書き出せません。', ko:'선택한 범위를 내보낼 수 없습니다.', ms:'Tidak dapat mengeksport julat yang dipilih.', nl:'Kan het geselecteerde bereik niet exporteren.', pl:'Nie można wyeksportować wybranego zakresu.', pt:'Não foi possível exportar o intervalo selecionado.', ru:'Не удалось экспортировать выбранный диапазон.', sv:'Kunde inte exportera det valda intervallet.', th:'ไม่สามารถส่งออกช่วงที่เลือกได้', tr:'Seçilen aralık dışa aktarılamadı.', uk:'Не вдалося експортувати вибраний діапазон.', vi:'Không thể xuất khoảng đã chọn.' },
  'Download WAV clip': { ar:'تنزيل مقطع WAV', es:'Descargar clip WAV', fr:'Télécharger le clip WAV', de:'WAV-Clip herunterladen', hi:'WAV क्लिप डाउनलोड करें', id:'Unduh klip WAV', it:'Scarica clip WAV', ja:'WAVクリップをダウンロード', ko:'WAV 클립 다운로드', ms:'Muat turun klip WAV', nl:'WAV-fragment downloaden', pl:'Pobierz klip WAV', pt:'Baixar clipe WAV', ru:'Скачать WAV-фрагмент', sv:'Ladda ner WAV-klipp', th:'ดาวน์โหลดคลิป WAV', tr:'WAV klibini indir', uk:'Завантажити WAV-фрагмент', vi:'Tải đoạn WAV' },
};

function translate(value: string, locale: Locale): string {
  if (locale === 'en') return value;
  const trimmed = value.trim();
  const translated = UI[trimmed]?.[locale] ?? UI[value]?.[locale];
  return translated ? value.replace(trimmed, translated) : value;
}

function apply(root: ParentNode, locale: Locale): void {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];
  while (walker.nextNode()) {
    const node = walker.currentNode as Text;
    const parent = node.parentElement;
    if (!node.nodeValue?.trim() || !parent || parent.closest('script,style,pre,textarea,[contenteditable="true"],[data-no-auto-i18n]')) continue;
    nodes.push(node);
  }
  for (const node of nodes) {
    const current = node.nodeValue ?? '';
    const next = translate(current, locale);
    if (next !== current) node.nodeValue = next;
  }
  root.querySelectorAll?.<HTMLElement>('[aria-label],[title],[placeholder]')?.forEach((element) => {
    for (const attribute of ['aria-label', 'title', 'placeholder'] as const) {
      const current = element.getAttribute(attribute);
      if (!current) continue;
      const next = translate(current, locale);
      if (next !== current) element.setAttribute(attribute, next);
    }
  });
}

export function installAudioCutterToolUiRuntimeLocalization(): () => void {
  if (typeof document === 'undefined' || !document.body) return () => undefined;
  const applyCurrent = () => {
    const locale = (document.documentElement.lang.split('-')[0] || 'en') as Locale;
    if (locale !== 'en') apply(document.body, locale);
  };
  applyCurrent();
  const observer = new MutationObserver(applyCurrent);
  observer.observe(document.body, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: ['aria-label', 'title', 'placeholder'] });
  return () => observer.disconnect();
}
