import type { Locale } from './config';

type LocaleMap = Readonly<Partial<Record<Locale, string>>>;

export const IMAGE_TOOL_UI: Readonly<Record<string, LocaleMap>> = {
  'AI Image Generator': { ar: 'مولد الصور بالذكاء الاصطناعي', es: 'Generador de imágenes con IA', fr: 'Générateur d’images IA', de: 'KI-Bildgenerator', hi: 'एआई इमेज जनरेटर', id: 'Generator Gambar AI', it: 'Generatore di immagini IA', ja: 'AI画像生成', ko: 'AI 이미지 생성기', ms: 'Penjana Imej AI', nl: 'AI-afbeeldingsgenerator', pl: 'Generator obrazów AI', pt: 'Gerador de imagens IA', ru: 'Генератор изображений ИИ', sv: 'AI-bildgenerator', th: 'เครื่องสร้างภาพ AI', tr: 'Yapay Zeka Görsel Oluşturucu', uk: 'Генератор зображень ШІ', vi: 'Trình tạo hình ảnh AI' },
  'Background Remover': { ar: 'إزالة الخلفية', es: 'Eliminador de fondo', fr: 'Suppression d’arrière-plan', de: 'Hintergrundentferner', hi: 'बैकग्राउंड रिमूवर', id: 'Penghapus latar belakang', it: 'Rimozione sfondo', ja: '背景除去', ko: '배경 제거기', ms: 'Pembuang latar belakang', nl: 'Achtergrondverwijderaar', pl: 'Usuwanie tła', pt: 'Removedor de fundo', ru: 'Удаление фона', sv: 'Bakgrundsborttagare', th: 'ลบพื้นหลัง', tr: 'Arka Plan Kaldırıcı', uk: 'Видалення фону', vi: 'Xóa nền' },
  'Image Upscaler': { ar: 'مكبر الصور', es: 'Ampliador de imágenes', fr: 'Agrandisseur d’images', de: 'Bildvergrößerer', hi: 'इमेज अपस्केलर', id: 'Peningkat gambar', it: 'Ingranditore immagini', ja: '画像アップスケーラー', ko: '이미지 업스케일러', ms: 'Penskala imej', nl: 'Beeldopschaler', pl: 'Skalowanie obrazu', pt: 'Aumentador de imagens', ru: 'Масштабирование изображений', sv: 'Bilduppskalare', th: 'เพิ่มขนาดภาพ', tr: 'Görsel Büyütücü', uk: 'Збільшувач зображень', vi: 'Phóng to hình ảnh' },
  'Image Converter': { ar: 'محول الصور', es: 'Convertidor de imágenes', fr: 'Convertisseur d’images', de: 'Bildkonverter', hi: 'इमेज कन्वर्टर', id: 'Konverter gambar', it: 'Convertitore immagini', ja: '画像変換', ko: '이미지 변환기', ms: 'Penukar imej', nl: 'Beeldconverter', pl: 'Konwerter obrazów', pt: 'Conversor de imagens', ru: 'Конвертер изображений', sv: 'Bildkonverterare', th: 'ตัวแปลงรูปภาพ', tr: 'Görsel Dönüştürücü', uk: 'Конвертер зображень', vi: 'Trình chuyển đổi hình ảnh' },
  'Image to Text OCR': { ar: 'تحويل الصورة إلى نص OCR', es: 'Imagen a texto OCR', fr: 'Image vers texte OCR', de: 'Bild zu Text OCR', hi: 'इमेज से टेक्स्ट OCR', id: 'Gambar ke Teks OCR', it: 'Immagine in testo OCR', ja: '画像からテキスト OCR', ko: '이미지 텍스트 OCR', ms: 'Imej kepada teks OCR', nl: 'Afbeelding naar tekst OCR', pl: 'Obraz na tekst OCR', pt: 'Imagem para texto OCR', ru: 'Распознавание текста OCR', sv: 'Bild till text OCR', th: 'แปลงรูปภาพเป็นข้อความ OCR', tr: 'Görüntüden Metne OCR', uk: 'Зображення в текст OCR', vi: 'OCR hình ảnh thành văn bản' },
  'Object Remover': { ar: 'إزالة العناصر', es: 'Eliminador de objetos', fr: 'Suppression d’objets', de: 'Objektentferner', hi: 'ऑब्जेक्ट रिमूवर', id: 'Penghapus objek', it: 'Rimozione oggetti', ja: 'オブジェクト除去', ko: '객체 제거기', ms: 'Pembuang objek', nl: 'Objectverwijderaar', pl: 'Usuwanie obiektów', pt: 'Removedor de objetos', ru: 'Удаление объектов', sv: 'Objektborttagare', th: 'ลบวัตถุ', tr: 'Nesne Kaldırıcı', uk: 'Видалення об’єктів', vi: 'Xóa đối tượng' },
  'Crop & Resize': { ar: 'قص وتغيير الحجم', es: 'Recortar y redimensionar', fr: 'Recadrer et redimensionner', de: 'Zuschneiden und Größe ändern', hi: 'क्रॉप और रिसाइज़', id: 'Potong & ubah ukuran', it: 'Ritaglia e ridimensiona', ja: 'トリミングとサイズ変更', ko: '자르기 및 크기 조정', ms: 'Pangkas & ubah saiz', nl: 'Bijsnijden en formaat wijzigen', pl: 'Kadrowanie i zmiana rozmiaru', pt: 'Cortar e redimensionar', ru: 'Обрезка и изменение размера', sv: 'Beskär och ändra storlek', th: 'ครอบตัดและปรับขนาด', tr: 'Kırp ve yeniden boyutlandır', uk: 'Обрізання та зміна розміру', vi: 'Cắt và đổi kích thước' },
  'Watermark Remover': { ar: 'إزالة العلامة المائية', es: 'Eliminador de marcas de agua', fr: 'Suppression de filigrane', de: 'Wasserzeichenentferner', hi: 'वॉटरमार्क रिमूवर', id: 'Penghapus tanda air', it: 'Rimozione filigrana', ja: '透かし除去', ko: '워터마크 제거기', ms: 'Pembuang tera air', nl: 'Watermerkverwijderaar', pl: 'Usuwanie znaku wodnego', pt: 'Removedor de marca d’água', ru: 'Удаление водяных знаков', sv: 'Vattenstämpelborttagare', th: 'ลบลายน้ำ', tr: 'Filigran Kaldırıcı', uk: 'Видалення водяних знаків', vi: 'Xóa hình mờ' },
  'Raster to SVG': { ar: 'تحويل Raster إلى SVG', es: 'Raster a SVG', fr: 'Raster vers SVG', de: 'Raster zu SVG', hi: 'रास्टर से SVG', id: 'Raster ke SVG', it: 'Da raster a SVG', ja: 'ラスターからSVG', ko: '래스터에서 SVG', ms: 'Raster kepada SVG', nl: 'Raster naar SVG', pl: 'Raster do SVG', pt: 'Raster para SVG', ru: 'Растр в SVG', sv: 'Raster till SVG', th: 'แรสเตอร์เป็น SVG', tr: 'Rasterdan SVG’ye', uk: 'Растр у SVG', vi: 'Raster sang SVG' },
  'FLIXO · IMAGE TOOLS': { ar: 'FLIXO · أدوات الصور', es: 'FLIXO · HERRAMIENTAS DE IMAGEN', fr: 'FLIXO · OUTILS IMAGE', de: 'FLIXO · BILDWERKZEUGE', hi: 'FLIXO · इमेज टूल्स', id: 'FLIXO · ALAT GAMBAR', it: 'FLIXO · STRUMENTI IMMAGINI', ja: 'FLIXO · 画像ツール', ko: 'FLIXO · 이미지 도구', ms: 'FLIXO · ALAT IMEJ', nl: 'FLIXO · AFBEELDINGSTOOLS', pl: 'FLIXO · NARZĘDZIA GRAFICZNE', pt: 'FLIXO · FERRAMENTAS DE IMAGEM', ru: 'FLIXO · ИНСТРУМЕНТЫ ИЗОБРАЖЕНИЙ', sv: 'FLIXO · BILDVERKTYG', th: 'FLIXO · เครื่องมือรูปภาพ', tr: 'FLIXO · GÖRSEL ARAÇLARI', uk: 'FLIXO · ІНСТРУМЕНТИ ЗОБРАЖЕНЬ', vi: 'FLIXO · CÔNG CỤ HÌNH ẢNH' },
  Prompt: { ar: 'الوصف', es: 'Descripción', fr: 'Description', de: 'Beschreibung', hi: 'प्रॉम्प्ट', id: 'Prompt', it: 'Prompt', ja: 'プロンプト', ko: '프롬프트', ms: 'Prompt', nl: 'Prompt', pl: 'Prompt', pt: 'Prompt', ru: 'Запрос', sv: 'Beskrivning', th: 'พรอมต์', tr: 'İstem', uk: 'Запит', vi: 'Mô tả' },
  'A cinematic sunset over Cairo...': { ar: 'غروب سينمائي فوق القاهرة...', es: 'Una puesta de sol cinematográfica sobre El Cairo...', fr: 'Un coucher de soleil cinématographique sur Le Caire...', de: 'Ein filmischer Sonnenuntergang über Kairo …', hi: 'काहिरा के ऊपर सिनेमाई सूर्यास्त...', id: 'Matahari terbenam sinematik di Kairo...', it: 'Un tramonto cinematografico sul Cairo...', ja: 'カイロの上に広がる映画のような夕日…', ko: '카이로 위의 영화 같은 일몰…', ms: 'Matahari terbenam sinematik di Cairo...', nl: 'Een filmische zonsondergang boven Caïro...', pl: 'Kinowy zachód słońca nad Kairem...', pt: 'Um pôr do sol cinematográfico sobre o Cairo...', ru: 'Кинематографичный закат над Каиром…', sv: 'En filmisk solnedgång över Kairo...', th: 'พระอาทิตย์ตกเหนือไคโรในแบบภาพยนตร์…', tr: 'Kahire üzerinde sinematik gün batımı...', uk: 'Кінематографічний захід сонця над Каїром…', vi: 'Hoàng hôn điện ảnh trên Cairo...' },
  'Choose an image': { ar: 'اختر صورة', es: 'Elegir una imagen', fr: 'Choisir une image', de: 'Bild auswählen', hi: 'एक छवि चुनें', id: 'Pilih gambar', it: 'Scegli un’immagine', ja: '画像を選択', ko: '이미지 선택', ms: 'Pilih imej', nl: 'Afbeelding kiezen', pl: 'Wybierz obraz', pt: 'Escolher uma imagem', ru: 'Выбрать изображение', sv: 'Välj en bild', th: 'เลือกภาพ', tr: 'Görsel seç', uk: 'Вибрати зображення', vi: 'Chọn hình ảnh' },
  'IMAGE INPUT': { ar: 'إدخال صورة', es: 'ENTRADA DE IMAGEN', fr: 'ENTRÉE IMAGE', de: 'BILDEINGABE', hi: 'इमेज इनपुट', id: 'INPUT GAMBAR', it: 'INPUT IMMAGINE', ja: '画像入力', ko: '이미지 입력', ms: 'INPUT IMEJ', nl: 'BEELDINVOER', pl: 'WEJŚCIE OBRAZU', pt: 'ENTRADA DE IMAGEM', ru: 'ВХОДНОЕ ИЗОБРАЖЕНИЕ', sv: 'BILDINDATA', th: 'อินพุตรูปภาพ', tr: 'GÖRSEL GİRDİ', uk: 'ВХІДНЕ ЗОБРАЖЕННЯ', vi: 'ĐẦU VÀO HÌNH ẢNH' },
  'Output format': { ar: 'صيغة الإخراج', es: 'Formato de salida', fr: 'Format de sortie', de: 'Ausgabeformat', hi: 'आउटपुट फ़ॉर्मेट', id: 'Format keluaran', it: 'Formato di output', ja: '出力形式', ko: '출력 형식', ms: 'Format output', nl: 'Uitvoerformaat', pl: 'Format wyjściowy', pt: 'Formato de saída', ru: 'Формат вывода', sv: 'Utdataformat', th: 'รูปแบบเอาต์พุต', tr: 'Çıkış biçimi', uk: 'Формат виводу', vi: 'Định dạng đầu ra' },
  Scale: { ar: 'المقياس', es: 'Escala', fr: 'Échelle', de: 'Skalierung', hi: 'स्केल', id: 'Skala', it: 'Scala', ja: '倍率', ko: '배율', ms: 'Skala', nl: 'Schaal', pl: 'Skala', pt: 'Escala', ru: 'Масштаб', sv: 'Skala', th: 'สเกล', tr: 'Ölçek', uk: 'Масштаб', vi: 'Tỷ lệ' },
  'Background tolerance': { ar: 'درجة تحمل الخلفية', es: 'Tolerancia del fondo', fr: 'Tolérance de l’arrière-plan', de: 'Hintergrundtoleranz', hi: 'बैकग्राउंड टॉलरेंस', id: 'Toleransi latar belakang', it: 'Tolleranza sfondo', ja: '背景許容度', ko: '배경 허용 오차', ms: 'Toleransi latar belakang', nl: 'Achtergrondtolerantie', pl: 'Tolerancja tła', pt: 'Tolerância do fundo', ru: 'Допуск фона', sv: 'Bakgrundstolerans', th: 'ค่าความคลาดเคลื่อนพื้นหลัง', tr: 'Arka plan toleransı', uk: 'Допуск фону', vi: 'Dung sai nền' },
  'SVG columns': { ar: 'أعمدة SVG', es: 'Columnas SVG', fr: 'Colonnes SVG', de: 'SVG-Spalten', hi: 'SVG कॉलम', id: 'Kolom SVG', it: 'Colonne SVG', ja: 'SVG列', ko: 'SVG 열', ms: 'Lajur SVG', nl: 'SVG-kolommen', pl: 'Kolumny SVG', pt: 'Colunas SVG', ru: 'Столбцы SVG', sv: 'SVG-kolumner', th: 'คอลัมน์ SVG', tr: 'SVG sütunları', uk: 'Стовпці SVG', vi: 'Cột SVG' },
  X: { ar: 'س', es: 'X', fr: 'X', de: 'X', hi: 'X', id: 'X', it: 'X', ja: 'X', ko: 'X', ms: 'X', nl: 'X', pl: 'X', pt: 'X', ru: 'X', sv: 'X', th: 'X', tr: 'X', uk: 'X', vi: 'X' },
  Y: { ar: 'ص', es: 'Y', fr: 'Y', de: 'Y', hi: 'Y', id: 'Y', it: 'Y', ja: 'Y', ko: 'Y', ms: 'Y', nl: 'Y', pl: 'Y', pt: 'Y', ru: 'Y', sv: 'Y', th: 'Y', tr: 'Y', uk: 'Y', vi: 'Y' },
  'Output width': { ar: 'عرض الإخراج', es: 'Ancho de salida', fr: 'Largeur de sortie', de: 'Ausgabebreite', hi: 'आउटपुट चौड़ाई', id: 'Lebar keluaran', it: 'Larghezza output', ja: '出力幅', ko: '출력 너비', ms: 'Lebar output', nl: 'Uitvoerbreedte', pl: 'Szerokość wyjściowa', pt: 'Largura de saída', ru: 'Ширина вывода', sv: 'Utdata bredd', th: 'ความกว้างเอาต์พุต', tr: 'Çıkış genişliği', uk: 'Ширина виводу', vi: 'Chiều rộng đầu ra' },
  'Output height': { ar: 'ارتفاع الإخراج', es: 'Alto de salida', fr: 'Hauteur de sortie', de: 'Ausgabehöhe', hi: 'आउटपुट ऊंचाई', id: 'Tinggi keluaran', it: 'Altezza output', ja: '出力高さ', ko: '출력 높이', ms: 'Tinggi output', nl: 'Uitvoerhoogte', pl: 'Wysokość wyjściowa', pt: 'Altura de saída', ru: 'Высота вывода', sv: 'Utdata höjd', th: 'ความสูงเอาต์พุต', tr: 'Çıkış yüksekliği', uk: 'Висота виводу', vi: 'Chiều cao đầu ra' },
  'Processing…': { ar: 'جارٍ المعالجة…', es: 'Procesando…', fr: 'Traitement…', de: 'Wird verarbeitet…', hi: 'प्रोसेस हो रहा है…', id: 'Memproses…', it: 'Elaborazione…', ja: '処理中…', ko: '처리 중…', ms: 'Memproses…', nl: 'Verwerken…', pl: 'Przetwarzanie…', pt: 'A processar…', ru: 'Обработка…', sv: 'Bearbetar…', th: 'กำลังประมวลผล…', tr: 'İşleniyor…', uk: 'Обробка…', vi: 'Đang xử lý…' },
  'Generate image': { ar: 'إنشاء الصورة', es: 'Generar imagen', fr: 'Générer une image', de: 'Bild generieren', hi: 'छवि जनरेट करें', id: 'Buat gambar', it: 'Genera immagine', ja: '画像を生成', ko: '이미지 생성', ms: 'Jana imej', nl: 'Afbeelding genereren', pl: 'Generuj obraz', pt: 'Gerar imagem', ru: 'Создать изображение', sv: 'Generera bild', th: 'สร้างภาพ', tr: 'Görsel oluştur', uk: 'Створити зображення', vi: 'Tạo hình ảnh' },
  'Run tool': { ar: 'تشغيل الأداة', es: 'Ejecutar herramienta', fr: 'Exécuter l’outil', de: 'Tool ausführen', hi: 'टूल चलाएँ', id: 'Jalankan alat', it: 'Esegui lo strumento', ja: 'ツールを実行', ko: '도구 실행', ms: 'Jalankan alat', nl: 'Tool uitvoeren', pl: 'Uruchom narzędzie', pt: 'Executar ferramenta', ru: 'Запустить инструмент', sv: 'Kör verktyget', th: 'เรียกใช้เครื่องมือ', tr: 'Aracı çalıştır', uk: 'Запустити інструмент', vi: 'Chạy công cụ' },
  'RESULT': { ar: 'النتيجة', es: 'RESULTADO', fr: 'RÉSULTAT', de: 'ERGEBNIS', hi: 'परिणाम', id: 'HASIL', it: 'RISULTATO', ja: '結果', ko: '결과', ms: 'HASIL', nl: 'RESULTAAT', pl: 'WYNIK', pt: 'RESULTADO', ru: 'РЕЗУЛЬТАТ', sv: 'RESULTAT', th: 'ผลลัพธ์', tr: 'SONUÇ', uk: 'РЕЗУЛЬТАТ', vi: 'KẾT QUẢ' },
  'No result yet.': { ar: 'لا توجد نتيجة بعد.', es: 'Aún no hay resultado.', fr: 'Aucun résultat pour le moment.', de: 'Noch kein Ergebnis.', hi: 'अभी कोई परिणाम नहीं।', id: 'Belum ada hasil.', it: 'Nessun risultato ancora.', ja: 'まだ結果がありません。', ko: '아직 결과가 없습니다.', ms: 'Belum ada hasil.', nl: 'Nog geen resultaat.', pl: 'Brak wyników.', pt: 'Ainda não há resultado.', ru: 'Результата пока нет.', sv: 'Inget resultat ännu.', th: 'ยังไม่มีผลลัพธ์', tr: 'Henüz sonuç yok.', uk: 'Результату ще немає.', vi: 'Chưa có kết quả.' },
  'No text detected.': { ar: 'لم يتم اكتشاف نص.', es: 'No se detectó texto.', fr: 'Aucun texte détecté.', de: 'Kein Text erkannt.', hi: 'कोई पाठ नहीं मिला।', id: 'Tidak ada teks yang terdeteksi.', it: 'Nessun testo rilevato.', ja: 'テキストが検出されませんでした。', ko: '텍스트가 감지되지 않았습니다.', ms: 'Tiada teks dikesan.', nl: 'Geen tekst gevonden.', pl: 'Nie wykryto tekstu.', pt: 'Nenhum texto detetado.', ru: 'Текст не обнаружен.', sv: 'Ingen text upptäcktes.', th: 'ไม่พบข้อความ', tr: 'Metin algılanmadı.', uk: 'Текст не виявлено.', vi: 'Không phát hiện văn bản.' },
  'Tool result': { ar: 'نتيجة الأداة', es: 'Resultado de la herramienta', fr: 'Résultat de l’outil', de: 'Werkzeugergebnis', hi: 'टूल परिणाम', id: 'Hasil alat', it: 'Risultato dello strumento', ja: 'ツールの結果', ko: '도구 결과', ms: 'Hasil alat', nl: 'Toolresultaat', pl: 'Wynik narzędzia', pt: 'Resultado da ferramenta', ru: 'Результат инструмента', sv: 'Verktygsresultat', th: 'ผลลัพธ์ของเครื่องมือ', tr: 'Araç sonucu', uk: 'Результат інструмента', vi: 'Kết quả công cụ' },
  'Download now': { ar: 'تنزيل الآن', es: 'Descargar ahora', fr: 'Télécharger maintenant', de: 'Jetzt herunterladen', hi: 'अभी डाउनलोड करें', id: 'Unduh sekarang', it: 'Scarica ora', ja: '今すぐダウンロード', ko: '지금 다운로드', ms: 'Muat turun sekarang', nl: 'Nu downloaden', pl: 'Pobierz teraz', pt: 'Transferir agora', ru: 'Скачать сейчас', sv: 'Ladda ner nu', th: 'ดาวน์โหลดตอนนี้', tr: 'Şimdi indir', uk: 'Завантажити зараз', vi: 'Tải xuống ngay' },
  'OCR preprocesses the selected image locally, then runs Tesseract.js recognition in a dedicated Web Worker.': { ar: 'تتم معالجة الصورة المحددة محليًا ثم تشغيل التعرف عبر Tesseract.js في Web Worker مخصص.', es: 'La imagen seleccionada se preprocesa localmente y luego Tesseract.js realiza el reconocimiento en un Web Worker dedicado.', fr: 'L’image sélectionnée est prétraitée localement, puis Tesseract.js effectue la reconnaissance dans un Web Worker dédié.', de: 'Das ausgewählte Bild wird lokal vorverarbeitet und anschließend mit Tesseract.js in einem dedizierten Web Worker erkannt.', hi: 'चयनित छवि को स्थानीय रूप से प्रीप्रोसेस किया जाता है, फिर समर्पित Web Worker में Tesseract.js पहचान चलती है।', id: 'Gambar terpilih diproses secara lokal, lalu pengenalan Tesseract.js dijalankan dalam Web Worker khusus.', it: 'L’immagine selezionata viene preprocessata localmente, quindi Tesseract.js esegue il riconoscimento in un Web Worker dedicato.', ja: '選択した画像をローカルで前処理し、専用Web WorkerでTesseract.js認識を実行します。', ko: '선택한 이미지를 로컬에서 전처리한 다음 전용 Web Worker에서 Tesseract.js 인식을 실행합니다.', ms: 'Imej yang dipilih dipraproses secara setempat, kemudian pengecaman Tesseract.js dijalankan dalam Web Worker khusus.', nl: 'De geselecteerde afbeelding wordt lokaal voorbewerkt en daarna verwerkt door Tesseract.js in een speciale Web Worker.', pl: 'Wybrany obraz jest przetwarzany lokalnie, a następnie rozpoznawany przez Tesseract.js w dedykowanym Web Workerze.', pt: 'A imagem selecionada é pré-processada localmente e o reconhecimento Tesseract.js é executado num Web Worker dedicado.', ru: 'Выбранное изображение предварительно обрабатывается локально, затем распознавание Tesseract.js выполняется в выделенном Web Worker.', sv: 'Den valda bilden förbehandlas lokalt och Tesseract.js kör sedan igenkänningen i en dedikerad Web Worker.', th: 'ประมวลผลภาพที่เลือกในเครื่องก่อน จากนั้นเรียกใช้การรู้จำ Tesseract.js ใน Web Worker เฉพาะ', tr: 'Seçilen görüntü yerel olarak ön işlenir, ardından Tesseract.js tanıması özel bir Web Worker’da çalıştırılır.', uk: 'Вибране зображення попередньо обробляється локально, після чого розпізнавання Tesseract.js запускається у виділеному Web Worker.', vi: 'Ảnh đã chọn được tiền xử lý cục bộ, sau đó nhận dạng Tesseract.js chạy trong Web Worker riêng.' },
  'Choose an image first.': { ar: 'اختر صورة أولًا.', es: 'Elige primero una imagen.', fr: 'Choisissez d’abord une image.', de: 'Bitte wählen Sie zuerst ein Bild.', hi: 'पहले एक छवि चुनें।', id: 'Pilih gambar terlebih dahulu.', it: 'Scegli prima un’immagine.', ja: '先に画像を選択してください。', ko: '먼저 이미지를 선택하세요.', ms: 'Sila pilih imej dahulu.', nl: 'Kies eerst een afbeelding.', pl: 'Najpierw wybierz obraz.', pt: 'Escolha primeiro uma imagem.', ru: 'Сначала выберите изображение.', sv: 'Välj en bild först.', th: 'โปรดเลือกภาพก่อน', tr: 'Önce bir görsel seçin.', uk: 'Спочатку виберіть зображення.', vi: 'Hãy chọn hình ảnh trước.' },
  'Enter a prompt first.': { ar: 'أدخل وصفًا أولًا.', es: 'Introduce una descripción primero.', fr: 'Saisissez d’abord une description.', de: 'Geben Sie zuerst eine Beschreibung ein.', hi: 'पहले एक प्रॉम्प्ट दर्ज करें।', id: 'Masukkan prompt terlebih dahulu.', it: 'Inserisci prima un prompt.', ja: '最初にプロンプトを入力してください。', ko: '먼저 프롬프트를 입력하세요.', ms: 'Masukkan prompt dahulu.', nl: 'Voer eerst een prompt in.', pl: 'Najpierw wpisz prompt.', pt: 'Insira primeiro um prompt.', ru: 'Сначала введите запрос.', sv: 'Ange först en beskrivning.', th: 'โปรดป้อนพรอมต์ก่อน', tr: 'Önce bir istem girin.', uk: 'Спочатку введіть запит.', vi: 'Hãy nhập mô tả trước.' },
};

export const IMAGE_TOOL_PREFIXES: ReadonlyArray<readonly [string, LocaleMap]> = [
  ['Download ', { ar: 'تنزيل ', es: 'Descargar ', fr: 'Télécharger ', de: 'Herunterladen ', hi: 'डाउनलोड ', id: 'Unduh ', it: 'Scarica ', ja: 'ダウンロード ', ko: '다운로드 ', ms: 'Muat turun ', nl: 'Downloaden ', pl: 'Pobierz ', pt: 'Baixar ', ru: 'Скачать ', sv: 'Ladda ner ', th: 'ดาวน์โหลด ', tr: 'İndir ', uk: 'Завантажити ', vi: 'Tải xuống ' }],
  ['Output: ', { ar: 'الإخراج: ', es: 'Salida: ', fr: 'Sortie : ', de: 'Ausgabe: ', hi: 'आउटपुट: ', id: 'Keluaran: ', it: 'Output: ', ja: '出力: ', ko: '출력: ', ms: 'Output: ', nl: 'Uitvoer: ', pl: 'Wyjście: ', pt: 'Saída: ', ru: 'Результат: ', sv: 'Utdata: ', th: 'เอาต์พุต: ', tr: 'Çıktı: ', uk: 'Вихід: ', vi: 'Đầu ra: ' }],
];
