import type { Locale } from './config';
import type { SeedUiTranslations } from './types';

const EN: SeedUiTranslations = {
  zoomIn: 'Zoom In Canvas', zoomOut: 'Zoom Out Canvas', zoomReset: 'Reset Canvas Zoom', undo: 'Undo Action', redo: 'Redo Action',
  compareHold: 'Hold to Compare Original', compareLabel: 'Compare', fullscreenEnter: 'Enter Fullscreen', fullscreenExit: 'Exit Fullscreen',
  resetAll: 'Reset all controls', exportPng: 'Export PNG', replaceImage: 'Replace image', lightColor: 'Light & Color',
  lightColorSubtitle: 'Core tonal response and chromatic balance', brightness: 'Brightness', contrast: 'Contrast', saturation: 'Saturation',
  warmth: 'Warmth', ambiance: 'Ambiance', highlights: 'Highlights', shadows: 'Shadows', fxFocus: 'FX & Focus',
  fxFocusSubtitle: 'Blur, bokeh, curves and exposure compositing', globalBlur: 'Global Blur', lensBlur: 'Lens Blur',
  bokehFocusShift: 'Bokeh / Focus Shift', curves: 'Curves', curvesPreview: 'Curves preview', curvesStrength: 'Curves Strength',
  doubleExposure: 'Double Exposure', doubleExposureFile: 'Double Exposure file', exposureOpacity: 'Exposure Opacity', exposureBlendMode: 'Exposure blend mode',
  geometry: 'Geometry', geometrySubtitle: 'Perspective and crop preparation', perspectiveX: 'Perspective X', perspectiveY: 'Perspective Y',
  cropX: 'Crop X', cropY: 'Crop Y', retouch: 'Retouch', retouchSubtitle: 'Selective brush and healing controls',
  brushStrength: 'Selective / Brush Strength', healingX: 'Healing X', healingY: 'Healing Y', resetSection: 'Reset section',
  seedPreview: 'Seed preview', dropImage: 'Drop an image into Seed', browseFiles: 'Browse files', brushActive: 'Brush active · click preview',
};

const make = (values: Partial<Record<keyof typeof EN, string>>): SeedUiTranslations => ({ ...EN, ...values } as SeedUiTranslations);

export const SEED_UI_TRANSLATIONS: Readonly<Record<Locale, SeedUiTranslations>> = {
  ar: make({
    zoomIn: 'تكبير اللوحة', zoomOut: 'تصغير اللوحة', zoomReset: 'إعادة ضبط تكبير اللوحة', undo: 'تراجع', redo: 'إعادة',
    compareHold: 'اضغط للمقارنة مع الأصل', compareLabel: 'مقارنة', fullscreenEnter: 'دخول ملء الشاشة', fullscreenExit: 'الخروج من ملء الشاشة',
    resetAll: 'إعادة ضبط كل عناصر التحكم', exportPng: 'تصدير PNG', replaceImage: 'استبدال الصورة', lightColor: 'الضوء واللون',
    lightColorSubtitle: 'الاستجابة اللونية الأساسية والتوازن اللوني', brightness: 'السطوع', contrast: 'التباين', saturation: 'التشبع', warmth: 'الدفء', ambiance: 'الأجواء',
    highlights: 'الإبرازات', shadows: 'الظلال', fxFocus: 'التأثيرات والتركيز', fxFocusSubtitle: 'التمويه والبُوكِه والمنحنيات وتركيب التعريض',
    globalBlur: 'تمويه عام', lensBlur: 'تمويه العدسة', bokehFocusShift: 'بُوكِه / تغيير التركيز', curves: 'المنحنيات', curvesPreview: 'معاينة المنحنيات', curvesStrength: 'شدة المنحنيات',
    doubleExposure: 'تعريض مزدوج', doubleExposureFile: 'ملف التعريض المزدوج', exposureOpacity: 'شفافية التعريض', exposureBlendMode: 'وضع مزج التعريض',
    geometry: 'الهندسة', geometrySubtitle: 'تهيئة المنظور والاقتصاص', perspectiveX: 'منظور X', perspectiveY: 'منظور Y', cropX: 'اقتصاص X', cropY: 'اقتصاص Y',
    retouch: 'تنقيح', retouchSubtitle: 'فرشاة انتقائية وعناصر إصلاح', brushStrength: 'شدة الفرشاة الانتقائية', healingX: 'إصلاح X', healingY: 'إصلاح Y', resetSection: 'إعادة ضبط القسم',
    seedPreview: 'معاينة Seed', dropImage: 'أسقط صورة في Seed', browseFiles: 'استعراض الملفات', brushActive: 'الفرشاة نشطة · انقر على المعاينة',
  }),
  en: EN,
  es: make({
    zoomIn: 'Acercar lienzo', zoomOut: 'Alejar lienzo', zoomReset: 'Restablecer zoom del lienzo', undo: 'Deshacer', redo: 'Rehacer',
    compareHold: 'Mantener para comparar con el original', compareLabel: 'Comparar', fullscreenEnter: 'Entrar en pantalla completa', fullscreenExit: 'Salir de pantalla completa',
    resetAll: 'Restablecer todos los controles', exportPng: 'Exportar PNG', replaceImage: 'Reemplazar imagen', lightColor: 'Luz y color', lightColorSubtitle: 'Respuesta tonal principal y equilibrio cromático',
    brightness: 'Brillo', contrast: 'Contraste', saturation: 'Saturación', warmth: 'Temperatura', ambiance: 'Ambiente', highlights: 'Iluminaciones', shadows: 'Sombras',
    fxFocus: 'FX y enfoque', fxFocusSubtitle: 'Desenfoque, bokeh, curvas y composición de exposición', globalBlur: 'Desenfoque global', lensBlur: 'Desenfoque de lente',
    bokehFocusShift: 'Bokeh / cambio de enfoque', curves: 'Curvas', curvesPreview: 'Vista previa de curvas', curvesStrength: 'Intensidad de curvas', doubleExposure: 'Doble exposición',
    doubleExposureFile: 'Archivo de doble exposición', exposureOpacity: 'Opacidad de exposición', exposureBlendMode: 'Modo de mezcla de exposición', geometry: 'Geometría', geometrySubtitle: 'Preparación de perspectiva y recorte',
    perspectiveX: 'Perspectiva X', perspectiveY: 'Perspectiva Y', cropX: 'Recorte X', cropY: 'Recorte Y', retouch: 'Retoque', retouchSubtitle: 'Pincel selectivo y controles de reparación',
    brushStrength: 'Intensidad selectiva / pincel', healingX: 'Reparación X', healingY: 'Reparación Y', resetSection: 'Restablecer sección', seedPreview: 'Vista previa de Seed',
    dropImage: 'Suelta una imagen en Seed', browseFiles: 'Explorar archivos', brushActive: 'Pincel activo · haz clic en la vista previa',
  }),
  fr: make({
    zoomIn: 'Agrandir le canevas', zoomOut: 'Réduire le canevas', zoomReset: 'Réinitialiser le zoom du canevas', undo: 'Annuler', redo: 'Rétablir',
    compareHold: "Maintenir pour comparer à l'original", compareLabel: 'Comparer', fullscreenEnter: 'Passer en plein écran', fullscreenExit: 'Quitter le plein écran', resetAll: 'Réinitialiser tous les contrôles', exportPng: 'Exporter PNG', replaceImage: "Remplacer l'image",
    lightColor: 'Lumière et couleur', lightColorSubtitle: 'Réponse tonale principale et équilibre chromatique', brightness: 'Luminosité', contrast: 'Contraste', saturation: 'Saturation', warmth: 'Chaleur', ambiance: 'Ambiance', highlights: 'Hautes lumières', shadows: 'Ombres',
    fxFocus: 'FX et mise au point', fxFocusSubtitle: "Flou, bokeh, courbes et composition de l'exposition", globalBlur: 'Flou global', lensBlur: 'Flou de lentille', bokehFocusShift: 'Bokeh / décalage de mise au point', curves: 'Courbes', curvesPreview: 'Aperçu des courbes', curvesStrength: 'Intensité des courbes',
    doubleExposure: 'Double exposition', doubleExposureFile: 'Fichier de double exposition', exposureOpacity: "Opacité de l'exposition", exposureBlendMode: "Mode de fusion de l'exposition", geometry: 'Géométrie', geometrySubtitle: 'Préparation de la perspective et du recadrage', perspectiveX: 'Perspective X', perspectiveY: 'Perspective Y', cropX: 'Recadrage X', cropY: 'Recadrage Y',
    retouch: 'Retouche', retouchSubtitle: 'Pinceau sélectif et contrôles de correction', brushStrength: 'Intensité du pinceau sélectif', healingX: 'Correction X', healingY: 'Correction Y', resetSection: 'Réinitialiser la section', seedPreview: 'Aperçu de Seed', dropImage: 'Déposez une image dans Seed', browseFiles: 'Parcourir les fichiers', brushActive: 'Pinceau actif · cliquez sur l’aperçu',
  }),
  de: make({
    zoomIn: 'Leinwand vergrößern', zoomOut: 'Leinwand verkleinern', zoomReset: 'Leinwand-Zoom zurücksetzen', undo: 'Rückgängig', redo: 'Wiederholen', compareHold: 'Gedrückt halten zum Vergleich mit dem Original', compareLabel: 'Vergleichen', fullscreenEnter: 'Vollbild öffnen', fullscreenExit: 'Vollbild verlassen', resetAll: 'Alle Steuerelemente zurücksetzen', exportPng: 'PNG exportieren', replaceImage: 'Bild ersetzen',
    lightColor: 'Licht und Farbe', lightColorSubtitle: 'Grundlegende Tonwertantwort und Farbbalance', brightness: 'Helligkeit', contrast: 'Kontrast', saturation: 'Sättigung', warmth: 'Wärme', ambiance: 'Atmosphäre', highlights: 'Lichter', shadows: 'Schatten', fxFocus: 'FX und Fokus', fxFocusSubtitle: 'Unschärfe, Bokeh, Kurven und Belichtungskomposition', globalBlur: 'Globale Unschärfe', lensBlur: 'Objektivunschärfe', bokehFocusShift: 'Bokeh / Fokusverschiebung', curves: 'Kurven', curvesPreview: 'Kurvenvorschau', curvesStrength: 'Kurvenstärke', doubleExposure: 'Doppelbelichtung', doubleExposureFile: 'Datei für Doppelbelichtung', exposureOpacity: 'Belichtungsdeckkraft', exposureBlendMode: 'Mischmodus der Belichtung', geometry: 'Geometrie', geometrySubtitle: 'Vorbereitung von Perspektive und Zuschnitt', perspectiveX: 'Perspektive X', perspectiveY: 'Perspektive Y', cropX: 'Zuschnitt X', cropY: 'Zuschnitt Y', retouch: 'Retusche', retouchSubtitle: 'Selektiver Pinsel und Reparatursteuerung', brushStrength: 'Stärke des selektiven Pinsels', healingX: 'Reparatur X', healingY: 'Reparatur Y', resetSection: 'Abschnitt zurücksetzen', seedPreview: 'Seed-Vorschau', dropImage: 'Bild in Seed ablegen', browseFiles: 'Dateien durchsuchen', brushActive: 'Pinsel aktiv · Vorschau anklicken',
  }),
  hi: make({ zoomIn: 'कैनवास ज़ूम इन', zoomOut: 'कैनवास ज़ूम आउट', zoomReset: 'कैनवास ज़ूम रीसेट करें', undo: 'पूर्ववत करें', redo: 'फिर से करें', compareHold: 'मूल से तुलना करने के लिए दबाए रखें', compareLabel: 'तुलना करें', fullscreenEnter: 'फुल स्क्रीन में जाएँ', fullscreenExit: 'फुल स्क्रीन से बाहर निकलें', resetAll: 'सभी नियंत्रण रीसेट करें', exportPng: 'PNG निर्यात करें', replaceImage: 'छवि बदलें', lightColor: 'प्रकाश और रंग', lightColorSubtitle: 'मुख्य टोनल प्रतिक्रिया और रंग संतुलन', brightness: 'चमक', contrast: 'कंट्रास्ट', saturation: 'संतृप्ति', warmth: 'गर्माहट', ambiance: 'माहौल', highlights: 'हाइलाइट्स', shadows: 'छायाएँ', fxFocus: 'FX और फोकस', fxFocusSubtitle: 'ब्लर, बोकेह, कर्व्स और एक्सपोज़र कंपोज़िटिंग', globalBlur: 'ग्लोबल ब्लर', lensBlur: 'लेंस ब्लर', bokehFocusShift: 'बोकेह / फोकस शिफ्ट', curves: 'कर्व्स', curvesPreview: 'कर्व्स पूर्वावलोकन', curvesStrength: 'कर्व्स की तीव्रता', doubleExposure: 'डबल एक्सपोज़र', doubleExposureFile: 'डबल एक्सपोज़र फ़ाइल', exposureOpacity: 'एक्सपोज़र अपारदर्शिता', exposureBlendMode: 'एक्सपोज़र ब्लेंड मोड', geometry: 'ज्यामिति', geometrySubtitle: 'परिप्रेक्ष्य और क्रॉप की तैयारी', perspectiveX: 'परिप्रेक्ष्य X', perspectiveY: 'परिप्रेक्ष्य Y', cropX: 'क्रॉप X', cropY: 'क्रॉप Y', retouch: 'रीटच', retouchSubtitle: 'चयनात्मक ब्रश और सुधार नियंत्रण', brushStrength: 'चयनात्मक ब्रश की तीव्रता', healingX: 'हीलिंग X', healingY: 'हीलिंग Y', resetSection: 'सेक्शन रीसेट करें', seedPreview: 'Seed पूर्वावलोकन', dropImage: 'Seed में छवि छोड़ें', browseFiles: 'फ़ाइलें ब्राउज़ करें', brushActive: 'ब्रश सक्रिय · पूर्वावलोकन पर क्लिक करें' }),
  id: make({ zoomIn: 'Perbesar kanvas', zoomOut: 'Perkecil kanvas', zoomReset: 'Atur ulang zoom kanvas', undo: 'Batalkan', redo: 'Ulangi', compareHold: 'Tahan untuk membandingkan dengan asli', compareLabel: 'Bandingkan', fullscreenEnter: 'Masuk layar penuh', fullscreenExit: 'Keluar layar penuh', resetAll: 'Atur ulang semua kontrol', exportPng: 'Ekspor PNG', replaceImage: 'Ganti gambar', lightColor: 'Cahaya dan warna', lightColorSubtitle: 'Respons tonal utama dan keseimbangan warna', brightness: 'Kecerahan', contrast: 'Kontras', saturation: 'Saturasi', warmth: 'Kehangatan', ambiance: 'Suasana', highlights: 'Sorotan', shadows: 'Bayangan', fxFocus: 'FX dan fokus', fxFocusSubtitle: 'Blur, bokeh, kurva, dan komposisi eksposur', globalBlur: 'Blur global', lensBlur: 'Blur lensa', bokehFocusShift: 'Bokeh / pergeseran fokus', curves: 'Kurva', curvesPreview: 'Pratinjau kurva', curvesStrength: 'Kekuatan kurva', doubleExposure: 'Paparan ganda', doubleExposureFile: 'Berkas paparan ganda', exposureOpacity: 'Opasitas paparan', exposureBlendMode: 'Mode campuran paparan', geometry: 'Geometri', geometrySubtitle: 'Persiapan perspektif dan pemotongan', perspectiveX: 'Perspektif X', perspectiveY: 'Perspektif Y', cropX: 'Potong X', cropY: 'Potong Y', retouch: 'Retus', retouchSubtitle: 'Kuas selektif dan kontrol perbaikan', brushStrength: 'Kekuatan kuas selektif', healingX: 'Perbaikan X', healingY: 'Perbaikan Y', resetSection: 'Atur ulang bagian', seedPreview: 'Pratinjau Seed', dropImage: 'Jatuhkan gambar ke Seed', browseFiles: 'Telusuri berkas', brushActive: 'Kuas aktif · klik pratinjau' }),
  it: make({ zoomIn: 'Ingrandisci canvas', zoomOut: 'Riduci canvas', zoomReset: 'Reimposta zoom canvas', undo: 'Annulla', redo: 'Ripristina', compareHold: 'Tieni premuto per confrontare con l’originale', compareLabel: 'Confronta', fullscreenEnter: 'Entra a schermo intero', fullscreenExit: 'Esci dallo schermo intero', resetAll: 'Reimposta tutti i controlli', exportPng: 'Esporta PNG', replaceImage: 'Sostituisci immagine', lightColor: 'Luce e colore', lightColorSubtitle: 'Risposta tonale principale ed equilibrio cromatico', brightness: 'Luminosità', contrast: 'Contrasto', saturation: 'Saturazione', warmth: 'Calore', ambiance: 'Atmosfera', highlights: 'Alte luci', shadows: 'Ombre', fxFocus: 'FX e messa a fuoco', fxFocusSubtitle: 'Sfocatura, bokeh, curve e composizione dell’esposizione', globalBlur: 'Sfocatura globale', lensBlur: 'Sfocatura lente', bokehFocusShift: 'Bokeh / spostamento del fuoco', curves: 'Curve', curvesPreview: 'Anteprima curve', curvesStrength: 'Intensità curve', doubleExposure: 'Doppia esposizione', doubleExposureFile: 'File doppia esposizione', exposureOpacity: 'Opacità esposizione', exposureBlendMode: 'Metodo di fusione esposizione', geometry: 'Geometria', geometrySubtitle: 'Preparazione prospettiva e ritaglio', perspectiveX: 'Prospettiva X', perspectiveY: 'Prospettiva Y', cropX: 'Ritaglio X', cropY: 'Ritaglio Y', retouch: 'Ritocco', retouchSubtitle: 'Pennello selettivo e controlli di correzione', brushStrength: 'Intensità pennello selettivo', healingX: 'Correzione X', healingY: 'Correzione Y', resetSection: 'Reimposta sezione', seedPreview: 'Anteprima Seed', dropImage: 'Trascina un’immagine in Seed', browseFiles: 'Sfoglia file', brushActive: 'Pennello attivo · fai clic sull’anteprima' }),
  ja: EN, ko: EN, ms: EN, nl: EN, pl: EN, pt: EN, ru: EN, sv: EN, th: EN, tr: EN, uk: EN, vi: EN,
};