import type { Locale } from './config';
import type { SeedUiTranslations } from './types';

const EN: SeedUiTranslations = {
  zoomIn: 'Zoom In Canvas', zoomOut: 'Zoom Out Canvas', zoomReset: 'Reset Canvas Zoom', undo: 'Undo Action', redo: 'Redo Action',
  compareHold: 'Hold to Compare Original', compareLabel: 'Compare', fullscreenEnter: 'Enter Fullscreen', fullscreenExit: 'Exit Fullscreen',
  resetAll: 'Reset all controls', exportPng: 'Export PNG', replaceImage: 'Replace image', lightColor: 'Light & Color',
  lightColorSubtitle: 'Core tonal response and chromatic balance', brightness: 'Brightness', contrast: 'Contrast', saturation: 'Saturation',
  warmth: 'Warmth', ambiance: 'Ambiance', highlights: 'Highlights', shadows: 'Shadows', fxFocus: 'FX & Focus',
  fxFocusSubtitle: 'Blur, bokeh, curves and exposure compositing', globalBlur: 'Global Blur', lensBlur: 'Lens Blur',
  bokehFocusShift: 'Bokeh / Focus Shift', curves: 'Curves', curvesPreview: 'Curves preview', curvesStrength: 'Curves Strength',
  doubleExposure: 'Double Exposure', doubleExposureFile: 'Double Exposure file', exposureOpacity: 'Exposure Opacity', exposureBlendMode: 'Exposure blend mode',
  geometry: 'Geometry', geometrySubtitle: 'Perspective and crop preparation', perspectiveX: 'Perspective X', perspectiveY: 'Perspective Y',
  cropX: 'Crop X', cropY: 'Crop Y', retouch: 'Retouch', retouchSubtitle: 'Selective brush and healing controls',
  brushStrength: 'Selective / Brush Strength', healingX: 'Healing X', healingY: 'Healing Y', resetSection: 'Reset section',
  seedPreview: 'Seed preview', dropImage: 'Drop an image into Seed', browseFiles: 'Browse files', brushActive: 'Brush active · click preview',
};

const make = (values: Partial<Record<keyof typeof EN, string>>): SeedUiTranslations => ({ ...EN, ...values });

export const SEED_UI_TRANSLATIONS: Readonly<Record<Locale, SeedUiTranslations>> = {
  ar: make({
    zoomIn: 'تكبير اللوحة', zoomOut: 'تصغير اللوحة', zoomReset: 'إعادة ضبط تكبير اللوحة', undo: 'تراجع', redo: 'إعادة',
    compareHold: 'اضغط للمقارنة مع الأصل', compareLabel: 'مقارنة', fullscreenEnter: 'دخول ملء الشاشة', fullscreenExit: 'الخروج من ملء الشاشة',
    resetAll: 'إعادة ضبط كل عناصر التحكم', exportPng: 'تصدير PNG', replaceImage: 'استبدال الصورة', lightColor: 'الضوء واللون',
    lightColorSubtitle: 'الاستجابة اللونية الأساسية والتوازن اللوني', brightness: 'السطوع', contrast: 'التباين', saturation: 'التشبع', warmth: 'الدفء', ambiance: 'الأجواء',
    highlights: 'الإبرازات', shadows: 'الظلال', fxFocus: 'التأثيرات والتركيز', fxFocusSubtitle: 'التمويه والبُوكِه والمنحنيات وتركيب التعريض',
    globalBlur: 'تمويه عام', lensBlur: 'تمويه العدسة', bokehFocusShift: 'بُوكِه / تغيير التركيز', curves: 'المنحنيات', curvesPreview: 'معاينة المنحنيات', curvesStrength: 'شدة المنحنيات',
    doubleExposure: 'تعريض مزدوج', doubleExposureFile: 'ملف التعريض المزدوج', exposureOpacity: 'شفافية التعريض', exposureBlendMode: 'وضع مزج التعريض',
    geometry: 'الهندسة', geometrySubtitle: 'تهيئة المنظور والاقتصاص', perspectiveX: 'منظور X', perspectiveY: 'منظور Y', cropX: 'اقتصاص X', cropY: 'اقتصاص Y',
    retouch: 'تنقيح', retouchSubtitle: 'فرشاة انتقائية وعناصر إصلاح', brushStrength: 'شدة الفرشاة الانتقائية', healingX: 'إصلاح X', healingY: 'إصلاح Y', resetSection: 'إعادة ضبط القسم',
    seedPreview: 'معاينة Seed', dropImage: 'أسقط صورة في Seed', browseFiles: 'استعراض الملفات', brushActive: 'الفرشاة نشطة · انقر على المعاينة',
  }),
  en: EN,
  es: make({
    zoomIn: 'Acercar lienzo', zoomOut: 'Alejar lienzo', zoomReset: 'Restablecer zoom del lienzo', undo: 'Deshacer', redo: 'Rehacer',
    compareHold: 'Mantener para comparar con el original', compareLabel: 'Comparar', fullscreenEnter: 'Entrar en pantalla completa', fullscreenExit: 'Salir de pantalla completa',
    resetAll: 'Restablecer todos los controles', exportPng: 'Exportar PNG', replaceImage: 'Reemplazar imagen', lightColor: 'Luz y color', lightColorSubtitle: 'Respuesta tonal principal y equilibrio cromático',
    brightness: 'Brillo', contrast: 'Contraste', saturation: 'Saturación', warmth: 'Temperatura', ambiance: 'Ambiente', highlights: 'Iluminaciones', shadows: 'Sombras',
    fxFocus: 'FX y enfoque', fxFocusSubtitle: 'Desenfoque, bokeh, curvas y composición de exposición', globalBlur: 'Desenfoque global', lensBlur: 'Desenfoque de lente',
    bokehFocusShift: 'Bokeh / cambio de enfoque', curves: 'Curvas', curvesPreview: 'Vista previa de curvas', curvesStrength: 'Intensidad de curvas', doubleExposure: 'Doble exposición',
    doubleExposureFile: 'Archivo de doble exposición', exposureOpacity: 'Opacidad de exposición', exposureBlendMode: 'Modo de mezcla de exposición', geometry: 'Geometría', geometrySubtitle: 'Preparación de perspectiva y recorte',
    perspectiveX: 'Perspectiva X', perspectiveY: 'Perspectiva Y', cropX: 'Recorte X', cropY: 'Recorte Y', retouch: 'Retoque', retouchSubtitle: 'Pincel selectivo y controles de reparación',
    brushStrength: 'Intensidad selectiva / pincel', healingX: 'Reparación X', healingY: 'Reparación Y', resetSection: 'Restablecer sección', seedPreview: 'Vista previa de Seed',
    dropImage: 'Suelta una imagen en Seed', browseFiles: 'Explorar archivos', brushActive: 'Pincel activo · haz clic en la vista previa',
  }),
  fr: make({
    zoomIn: 'Agrandir le canevas', zoomOut: 'Réduire le canevas', zoomReset: 'Réinitialiser le zoom du canevas', undo: 'Annuler', redo: 'Rétablir',
    compareHold: "Maintenir pour comparer à l'original", compareLabel: 'Comparer', fullscreenEnter: 'Passer en plein écran', fullscreenExit: 'Quitter le plein écran', resetAll: 'Réinitialiser tous les contrôles', exportPng: 'Exporter PNG', replaceImage: "Remplacer l'image",
    lightColor: 'Lumière et couleur', lightColorSubtitle: 'Réponse tonale principale et équilibre chromatique', brightness: 'Luminosité', contrast: 'Contraste', saturation: 'Saturation', warmth: 'Chaleur', ambiance: 'Ambiance', highlights: 'Hautes lumières', shadows: 'Ombres',
    fxFocus: 'FX et mise au point', fxFocusSubtitle: "Flou, bokeh, courbes et composition de l'exposition", globalBlur: 'Flou global', lensBlur: 'Flou de lentille', bokehFocusShift: 'Bokeh / décalage de mise au point', curves: 'Courbes', curvesPreview: 'Aperçu des courbes', curvesStrength: 'Intensité des courbes',
    doubleExposure: 'Double exposition', doubleExposureFile: 'Fichier de double exposition', exposureOpacity: "Opacité de l'exposition", exposureBlendMode: "Mode de fusion de l'exposition", geometry: 'Géométrie', geometrySubtitle: 'Préparation de la perspective et du recadrage', perspectiveX: 'Perspective X', perspectiveY: 'Perspective Y', cropX: 'Recadrage X', cropY: 'Recadrage Y',
    retouch: 'Retouche', retouchSubtitle: 'Pinceau sélectif et contrôles de correction', brushStrength: 'Intensité du pinceau sélectif', healingX: 'Correction X', healingY: 'Correction Y', resetSection: 'Réinitialiser la section', seedPreview: 'Aperçu de Seed', dropImage: 'Déposez une image dans Seed', browseFiles: 'Parcourir les fichiers', brushActive: 'Pinceau actif · cliquez sur l’aperçu',
  }),
  de: make({
    zoomIn: 'Leinwand vergrößern', zoomOut: 'Leinwand verkleinern', zoomReset: 'Leinwand-Zoom zurücksetzen', undo: 'Rückgängig', redo: 'Wiederholen', compareHold: 'Gedrückt halten zum Vergleich mit dem Original', compareLabel: 'Vergleichen', fullscreenEnter: 'Vollbild öffnen', fullscreenExit: 'Vollbild verlassen', resetAll: 'Alle Steuerelemente zurücksetzen', exportPng: 'PNG exportieren', replaceImage: 'Bild ersetzen',
    lightColor: 'Licht und Farbe', lightColorSubtitle: 'Grundlegende Tonwertantwort und Farbbalance', brightness: 'Helligkeit', contrast: 'Kontrast', saturation: 'Sättigung', warmth: 'Wärme', ambiance: 'Atmosphäre', highlights: 'Lichter', shadows: 'Schatten', fxFocus: 'FX und Fokus', fxFocusSubtitle: 'Unschärfe, Bokeh, Kurven und Belichtungskomposition', globalBlur: 'Globale Unschärfe', lensBlur: 'Objektivunschärfe', bokehFocusShift: 'Bokeh / Fokusverschiebung', curves: 'Kurven', curvesPreview: 'Kurvenvorschau', curvesStrength: 'Kurvenstärke', doubleExposure: 'Doppelbelichtung', doubleExposureFile: 'Datei für Doppelbelichtung', exposureOpacity: 'Belichtungsdeckkraft', exposureBlendMode: 'Mischmodus der Belichtung', geometry: 'Geometrie', geometrySubtitle: 'Vorbereitung von Perspektive und Zuschnitt', perspectiveX: 'Perspektive X', perspectiveY: 'Perspektive Y', cropX: 'Zuschnitt X', cropY: 'Zuschnitt Y', retouch: 'Retusche', retouchSubtitle: 'Selektiver Pinsel und Reparatursteuerung', brushStrength: 'Stärke des selektiven Pinsels', healingX: 'Reparatur X', healingY: 'Reparatur Y', resetSection: 'Abschnitt zurücksetzen', seedPreview: 'Seed-Vorschau', dropImage: 'Bild in Seed ablegen', browseFiles: 'Dateien durchsuchen', brushActive: 'Pinsel aktiv · Vorschau anklicken',
  }),
  hi: make({ zoomIn: 'कैनवास ज़ूम इन', zoomOut: 'कैनवास ज़ूम आउट', zoomReset: 'कैनवास ज़ूम रीसेट करें', undo: 'पूर्ववत करें', redo: 'फिर से करें', compareHold: 'मूल से तुलना करने के लिए दबाए रखें', compareLabel: 'तुलना करें', fullscreenEnter: 'फुल स्क्रीन में जाएँ', fullscreenExit: 'फुल स्क्रीन से बाहर निकलें', resetAll: 'सभी नियंत्रण रीसेट करें', exportPng: 'PNG निर्यात करें', replaceImage: 'छवि बदलें', lightColor: 'प्रकाश और रंग', lightColorSubtitle: 'मुख्य टोनल प्रतिक्रिया और रंग संतुलन', brightness: 'चमक', contrast: 'कंट्रास्ट', saturation: 'संतृप्ति', warmth: 'गर्माहट', ambiance: 'माहौल', highlights: 'हाइलाइट्स', shadows: 'छायाएँ', fxFocus: 'FX और फोकस', fxFocusSubtitle: 'ब्लर, बोकेह, कर्व्स और एक्सपोज़र कंपोज़िटिंग', globalBlur: 'ग्लोबल ब्लर', lensBlur: 'लेंस ब्लर', bokehFocusShift: 'बोकेह / फोकस शिफ्ट', curves: 'कर्व्स', curvesPreview: 'कर्व्स पूर्वावलोकन', curvesStrength: 'कर्व्स की तीव्रता', doubleExposure: 'डबल एक्सपोज़र', doubleExposureFile: 'डबल एक्सपोज़र फ़ाइल', exposureOpacity: 'एक्सपोज़र अपारदर्शिता', exposureBlendMode: 'एक्सपोज़र ब्लेंड मोड', geometry: 'ज्यामिति', geometrySubtitle: 'परिप्रेक्ष्य और क्रॉप की तैयारी', perspectiveX: 'परिप्रेक्ष्य X', perspectiveY: 'परिप्रेक्ष्य Y', cropX: 'क्रॉप X', cropY: 'क्रॉप Y', retouch: 'रीटच', retouchSubtitle: 'चयनात्मक ब्रश और सुधार नियंत्रण', brushStrength: 'चयनात्मक ब्रश की तीव्रता', healingX: 'हीलिंग X', healingY: 'हीलिंग Y', resetSection: 'सेक्शन रीसेट करें', seedPreview: 'Seed पूर्वावलोकन', dropImage: 'Seed में छवि छोड़ें', browseFiles: 'फ़ाइलें ब्राउज़ करें', brushActive: 'ब्रश सक्रिय · पूर्वावलोकन पर क्लिक करें' }),
  id: make({ zoomIn: 'Perbesar kanvas', zoomOut: 'Perkecil kanvas', zoomReset: 'Atur ulang zoom kanvas', undo: 'Batalkan', redo: 'Ulangi', compareHold: 'Tahan untuk membandingkan dengan asli', compareLabel: 'Bandingkan', fullscreenEnter: 'Masuk layar penuh', fullscreenExit: 'Keluar layar penuh', resetAll: 'Atur ulang semua kontrol', exportPng: 'Ekspor PNG', replaceImage: 'Ganti gambar', lightColor: 'Cahaya dan warna', lightColorSubtitle: 'Respons tonal utama dan keseimbangan warna', brightness: 'Kecerahan', contrast: 'Kontras', saturation: 'Saturasi', warmth: 'Kehangatan', ambiance: 'Suasana', highlights: 'Sorotan', shadows: 'Bayangan', fxFocus: 'FX dan fokus', fxFocusSubtitle: 'Blur, bokeh, kurva, dan komposisi eksposur', globalBlur: 'Blur global', lensBlur: 'Blur lensa', bokehFocusShift: 'Bokeh / pergeseran fokus', curves: 'Kurva', curvesPreview: 'Pratinjau kurva', curvesStrength: 'Kekuatan kurva', doubleExposure: 'Paparan ganda', doubleExposureFile: 'Berkas paparan ganda', exposureOpacity: 'Opasitas paparan', exposureBlendMode: 'Mode campuran paparan', geometry: 'Geometri', geometrySubtitle: 'Persiapan perspektif dan pemotongan', perspectiveX: 'Perspektif X', perspectiveY: 'Perspektif Y', cropX: 'Potong X', cropY: 'Potong Y', retouch: 'Retus', retouchSubtitle: 'Kuas selektif dan kontrol perbaikan', brushStrength: 'Kekuatan kuas selektif', healingX: 'Perbaikan X', healingY: 'Perbaikan Y', resetSection: 'Atur ulang bagian', seedPreview: 'Pratinjau Seed', dropImage: 'Jatuhkan gambar ke Seed', browseFiles: 'Telusuri berkas', brushActive: 'Kuas aktif · klik pratinjau' }),
  it: make({ zoomIn: 'Ingrandisci canvas', zoomOut: 'Riduci canvas', zoomReset: 'Reimposta zoom canvas', undo: 'Annulla', redo: 'Ripristina', compareHold: 'Tieni premuto per confrontare con l’originale', compareLabel: 'Confronta', fullscreenEnter: 'Entra a schermo intero', fullscreenExit: 'Esci dallo schermo intero', resetAll: 'Reimposta tutti i controlli', exportPng: 'Esporta PNG', replaceImage: 'Sostituisci immagine', lightColor: 'Luce e colore', lightColorSubtitle: 'Risposta tonale principale ed equilibrio cromatico', brightness: 'Luminosità', contrast: 'Contrasto', saturation: 'Saturazione', warmth: 'Calore', ambiance: 'Atmosfera', highlights: 'Alte luci', shadows: 'Ombre', fxFocus: 'FX e messa a fuoco', fxFocusSubtitle: 'Sfocatura, bokeh, curve e composizione dell’esposizione', globalBlur: 'Sfocatura globale', lensBlur: 'Sfocatura lente', bokehFocusShift: 'Bokeh / spostamento del fuoco', curves: 'Curve', curvesPreview: 'Anteprima curve', curvesStrength: 'Intensità curve', doubleExposure: 'Doppia esposizione', doubleExposureFile: 'File doppia esposizione', exposureOpacity: 'Opacità esposizione', exposureBlendMode: 'Metodo di fusione esposizione', geometry: 'Geometria', geometrySubtitle: 'Preparazione prospettiva e ritaglio', perspectiveX: 'Prospettiva X', perspectiveY: 'Prospettiva Y', cropX: 'Ritaglio X', cropY: 'Ritaglio Y', retouch: 'Ritocco', retouchSubtitle: 'Pennello selettivo e controlli di correzione', brushStrength: 'Intensità pennello selettivo', healingX: 'Correzione X', healingY: 'Correzione Y', resetSection: 'Reimposta sezione', seedPreview: 'Anteprima Seed', dropImage: 'Trascina un’immagine in Seed', browseFiles: 'Sfoglia file', brushActive: 'Pennello attivo · fai clic sull’anteprima' }),
  ja: make({ zoomIn: 'キャンバスを拡大', zoomOut: 'キャンバスを縮小', zoomReset: 'キャンバスズームをリセット', undo: '元に戻す', redo: 'やり直す', compareHold: '押したまま元画像と比較', compareLabel: '比較', fullscreenEnter: '全画面に入る', fullscreenExit: '全画面を終了', resetAll: 'すべてのコントロールをリセット', exportPng: 'PNGを書き出す', replaceImage: '画像を置換', lightColor: '光と色', lightColorSubtitle: '基本のトーン応答と色バランス', brightness: '明るさ', contrast: 'コントラスト', saturation: '彩度', warmth: '暖かさ', ambiance: '雰囲気', highlights: 'ハイライト', shadows: 'シャドウ', fxFocus: 'FXとフォーカス', fxFocusSubtitle: 'ぼかし、ボケ、カーブ、露出合成', globalBlur: '全体ぼかし', lensBlur: 'レンズぼかし', bokehFocusShift: 'ボケ / フォーカスシフト', curves: 'カーブ', curvesPreview: 'カーブプレビュー', curvesStrength: 'カーブ強度', doubleExposure: '二重露光', doubleExposureFile: '二重露光ファイル', exposureOpacity: '露出の不透明度', exposureBlendMode: '露出ブレンドモード', geometry: 'ジオメトリ', geometrySubtitle: 'パースとトリミングの準備', perspectiveX: 'パース X', perspectiveY: 'パース Y', cropX: 'トリミング X', cropY: 'トリミング Y', retouch: 'レタッチ', retouchSubtitle: '選択ブラシと修復コントロール', brushStrength: '選択ブラシ強度', healingX: '修復 X', healingY: '修復 Y', resetSection: 'セクションをリセット', seedPreview: 'Seed プレビュー', dropImage: 'Seed に画像をドロップ', browseFiles: 'ファイルを参照', brushActive: 'ブラシ有効 · プレビューをクリック' }),
  ko: make({ zoomIn: '캔버스 확대', zoomOut: '캔버스 축소', zoomReset: '캔버스 확대/축소 재설정', undo: '실행 취소', redo: '다시 실행', compareHold: '원본과 비교하려면 길게 누르세요', compareLabel: '비교', fullscreenEnter: '전체 화면으로 들어가기', fullscreenExit: '전체 화면 나가기', resetAll: '모든 컨트롤 재설정', exportPng: 'PNG 내보내기', replaceImage: '이미지 교체', lightColor: '빛과 색상', lightColorSubtitle: '기본 톤 응답 및 색 균형', brightness: '밝기', contrast: '대비', saturation: '채도', warmth: '따뜻함', ambiance: '분위기', highlights: '하이라이트', shadows: '그림자', fxFocus: 'FX 및 초점', fxFocusSubtitle: '블러, 보케, 곡선 및 노출 합성', globalBlur: '전체 블러', lensBlur: '렌즈 블러', bokehFocusShift: '보케 / 초점 이동', curves: '곡선', curvesPreview: '곡선 미리보기', curvesStrength: '곡선 강도', doubleExposure: '이중 노출', doubleExposureFile: '이중 노출 파일', exposureOpacity: '노출 불투명도', exposureBlendMode: '노출 혼합 모드', geometry: '기하학', geometrySubtitle: '원근 및 자르기 준비', perspectiveX: '원근 X', perspectiveY: '원근 Y', cropX: '자르기 X', cropY: '자르기 Y', retouch: '리터치', retouchSubtitle: '선택 브러시 및 복구 컨트롤', brushStrength: '선택 브러시 강도', healingX: '복구 X', healingY: '복구 Y', resetSection: '섹션 재설정', seedPreview: 'Seed 미리보기', dropImage: 'Seed에 이미지를 놓으세요', browseFiles: '파일 찾아보기', brushActive: '브러시 활성 · 미리보기 클릭' }),
  ms: make({ zoomIn: 'Zum masuk kanvas', zoomOut: 'Zum keluar kanvas', zoomReset: 'Tetapkan semula zum kanvas', undo: 'Buat asal', redo: 'Buat semula', compareHold: 'Tahan untuk bandingkan dengan asal', compareLabel: 'Bandingkan', fullscreenEnter: 'Masuk skrin penuh', fullscreenExit: 'Keluar skrin penuh', resetAll: 'Tetapkan semula semua kawalan', exportPng: 'Eksport PNG', replaceImage: 'Gantikan imej', lightColor: 'Cahaya dan warna', lightColorSubtitle: 'Respons ton utama dan keseimbangan warna', brightness: 'Kecerahan', contrast: 'Kontras', saturation: 'Ketepuan', warmth: 'Kehangatan', ambiance: 'Suasana', highlights: 'Sorotan', shadows: 'Bayang', fxFocus: 'FX dan fokus', fxFocusSubtitle: 'Kabur, bokeh, lengkung dan komposit pendedahan', globalBlur: 'Kabur global', lensBlur: 'Kabur kanta', bokehFocusShift: 'Bokeh / anjakan fokus', curves: 'Lengkung', curvesPreview: 'Pratonton lengkung', curvesStrength: 'Kekuatan lengkung', doubleExposure: 'Dedahan berganda', doubleExposureFile: 'Fail dedahan berganda', exposureOpacity: 'Kelegapan dedahan', exposureBlendMode: 'Mod campuran dedahan', geometry: 'Geometri', geometrySubtitle: 'Persediaan perspektif dan pangkasan', perspectiveX: 'Perspektif X', perspectiveY: 'Perspektif Y', cropX: 'Pangkasan X', cropY: 'Pangkasan Y', retouch: 'Retus', retouchSubtitle: 'Berus terpilih dan kawalan pemulihan', brushStrength: 'Kekuatan berus terpilih', healingX: 'Pemulihan X', healingY: 'Pemulihan Y', resetSection: 'Tetapkan semula bahagian', seedPreview: 'Pratonton Seed', dropImage: 'Lepaskan imej ke dalam Seed', browseFiles: 'Semak imbas fail', brushActive: 'Berus aktif · klik pratonton' }),
  nl: make({ zoomIn: 'Canvas vergroten', zoomOut: 'Canvas verkleinen', zoomReset: 'Canvaszoom resetten', undo: 'Ongedaan maken', redo: 'Opnieuw uitvoeren', compareHold: 'Vasthouden om met het origineel te vergelijken', compareLabel: 'Vergelijken', fullscreenEnter: 'Volledig scherm openen', fullscreenExit: 'Volledig scherm sluiten', resetAll: 'Alle bedieningselementen resetten', exportPng: 'PNG exporteren', replaceImage: 'Afbeelding vervangen', lightColor: 'Licht en kleur', lightColorSubtitle: 'Basisrespons van tonen en kleurbalans', brightness: 'Helderheid', contrast: 'Contrast', saturation: 'Verzadiging', warmth: 'Warmte', ambiance: 'Sfeer', highlights: 'Lichte partijen', shadows: 'Schaduwen', fxFocus: 'FX en focus', fxFocusSubtitle: 'Vervaging, bokeh, curven en belichtingscompositie', globalBlur: 'Globale vervaging', lensBlur: 'Lensvervaging', bokehFocusShift: 'Bokeh / focusverschuiving', curves: 'Curven', curvesPreview: 'Curvenvoorbeeld', curvesStrength: 'Curve-intensiteit', doubleExposure: 'Dubbele belichting', doubleExposureFile: 'Bestand voor dubbele belichting', exposureOpacity: 'Dekking belichting', exposureBlendMode: 'Mengmodus belichting', geometry: 'Geometrie', geometrySubtitle: 'Voorbereiding perspectief en uitsnede', perspectiveX: 'Perspectief X', perspectiveY: 'Perspectief Y', cropX: 'Uitsnede X', cropY: 'Uitsnede Y', retouch: 'Retouche', retouchSubtitle: 'Selectieve penseel- en herstelinstellingen', brushStrength: 'Sterkte selectief penseel', healingX: 'Herstel X', healingY: 'Herstel Y', resetSection: 'Sectie resetten', seedPreview: 'Seed-voorbeeld', dropImage: 'Sleep een afbeelding naar Seed', browseFiles: 'Bestanden bladeren', brushActive: 'Penseel actief · klik op voorbeeld' }),
  pl: make({ zoomIn: 'Powiększ płótno', zoomOut: 'Pomniejsz płótno', zoomReset: 'Resetuj powiększenie płótna', undo: 'Cofnij', redo: 'Ponów', compareHold: 'Przytrzymaj, aby porównać z oryginałem', compareLabel: 'Porównaj', fullscreenEnter: 'Wejdź w tryb pełnoekranowy', fullscreenExit: 'Wyjdź z trybu pełnoekranowego', resetAll: 'Resetuj wszystkie elementy sterujące', exportPng: 'Eksportuj PNG', replaceImage: 'Zastąp obraz', lightColor: 'Światło i kolor', lightColorSubtitle: 'Podstawowa odpowiedź tonalna i balans kolorów', brightness: 'Jasność', contrast: 'Kontrast', saturation: 'Nasycenie', warmth: 'Ciepło', ambiance: 'Atmosfera', highlights: 'Światła', shadows: 'Cienie', fxFocus: 'FX i ostrość', fxFocusSubtitle: 'Rozmycie, bokeh, krzywe i kompozycja ekspozycji', globalBlur: 'Rozmycie globalne', lensBlur: 'Rozmycie obiektywu', bokehFocusShift: 'Bokeh / przesunięcie ostrości', curves: 'Krzywe', curvesPreview: 'Podgląd krzywych', curvesStrength: 'Siła krzywych', doubleExposure: 'Podwójna ekspozycja', doubleExposureFile: 'Plik podwójnej ekspozycji', exposureOpacity: 'Krycie ekspozycji', exposureBlendMode: 'Tryb mieszania ekspozycji', geometry: 'Geometria', geometrySubtitle: 'Przygotowanie perspektywy i kadrowania', perspectiveX: 'Perspektywa X', perspectiveY: 'Perspektywa Y', cropX: 'Kadrowanie X', cropY: 'Kadrowanie Y', retouch: 'Retusz', retouchSubtitle: 'Pędzel selektywny i kontrolki naprawy', brushStrength: 'Siła pędzla selektywnego', healingX: 'Naprawa X', healingY: 'Naprawa Y', resetSection: 'Resetuj sekcję', seedPreview: 'Podgląd Seed', dropImage: 'Upuść obraz do Seed', browseFiles: 'Przeglądaj pliki', brushActive: 'Pędzel aktywny · kliknij podgląd' }),
  pt: make({ zoomIn: 'Ampliar tela', zoomOut: 'Reduzir tela', zoomReset: 'Repor zoom da tela', undo: 'Desfazer', redo: 'Refazer', compareHold: 'Segure para comparar com o original', compareLabel: 'Comparar', fullscreenEnter: 'Entrar em tela cheia', fullscreenExit: 'Sair da tela cheia', resetAll: 'Repor todos os controlos', exportPng: 'Exportar PNG', replaceImage: 'Substituir imagem', lightColor: 'Luz e cor', lightColorSubtitle: 'Resposta tonal principal e equilíbrio cromático', brightness: 'Brilho', contrast: 'Contraste', saturation: 'Saturação', warmth: 'Calor', ambiance: 'Ambiente', highlights: 'Realces', shadows: 'Sombras', fxFocus: 'FX e foco', fxFocusSubtitle: 'Desfoque, bokeh, curvas e composição da exposição', globalBlur: 'Desfoque global', lensBlur: 'Desfoque de lente', bokehFocusShift: 'Bokeh / deslocamento do foco', curves: 'Curvas', curvesPreview: 'Pré-visualização das curvas', curvesStrength: 'Intensidade das curvas', doubleExposure: 'Dupla exposição', doubleExposureFile: 'Ficheiro de dupla exposição', exposureOpacity: 'Opacidade da exposição', exposureBlendMode: 'Modo de mistura da exposição', geometry: 'Geometria', geometrySubtitle: 'Preparação da perspetiva e recorte', perspectiveX: 'Perspetiva X', perspectiveY: 'Perspetiva Y', cropX: 'Recorte X', cropY: 'Recorte Y', retouch: 'Retoque', retouchSubtitle: 'Pincel seletivo e controlos de correção', brushStrength: 'Intensidade do pincel seletivo', healingX: 'Correção X', healingY: 'Correção Y', resetSection: 'Repor secção', seedPreview: 'Pré-visualização do Seed', dropImage: 'Largue uma imagem no Seed', browseFiles: 'Procurar ficheiros', brushActive: 'Pincel ativo · clique na pré-visualização' }),
  ru: make({ zoomIn: 'Увеличить холст', zoomOut: 'Уменьшить холст', zoomReset: 'Сбросить масштаб холста', undo: 'Отменить', redo: 'Повторить', compareHold: 'Удерживайте для сравнения с оригиналом', compareLabel: 'Сравнить', fullscreenEnter: 'Полноэкранный режим', fullscreenExit: 'Выйти из полноэкранного режима', resetAll: 'Сбросить все элементы управления', exportPng: 'Экспорт PNG', replaceImage: 'Заменить изображение', lightColor: 'Свет и цвет', lightColorSubtitle: 'Основная тональная характеристика и цветовой баланс', brightness: 'Яркость', contrast: 'Контраст', saturation: 'Насыщенность', warmth: 'Теплота', ambiance: 'Атмосфера', highlights: 'Света', shadows: 'Тени', fxFocus: 'FX и фокус', fxFocusSubtitle: 'Размытие, боке, кривые и компоновка экспозиции', globalBlur: 'Общее размытие', lensBlur: 'Размытие объектива', bokehFocusShift: 'Боке / смещение фокуса', curves: 'Кривые', curvesPreview: 'Предпросмотр кривых', curvesStrength: 'Сила кривых', doubleExposure: 'Двойная экспозиция', doubleExposureFile: 'Файл двойной экспозиции', exposureOpacity: 'Непрозрачность экспозиции', exposureBlendMode: 'Режим смешивания экспозиции', geometry: 'Геометрия', geometrySubtitle: 'Подготовка перспективы и кадрирования', perspectiveX: 'Перспектива X', perspectiveY: 'Перспектива Y', cropX: 'Обрезка X', cropY: 'Обрезка Y', retouch: 'Ретушь', retouchSubtitle: 'Выборочная кисть и управление восстановлением', brushStrength: 'Сила выборочной кисти', healingX: 'Восстановление X', healingY: 'Восстановление Y', resetSection: 'Сбросить раздел', seedPreview: 'Предпросмотр Seed', dropImage: 'Перетащите изображение в Seed', browseFiles: 'Обзор файлов', brushActive: 'Кисть активна · нажмите на предпросмотр' }),
  sv: make({ zoomIn: 'Zooma in på arbetsytan', zoomOut: 'Zooma ut från arbetsytan', zoomReset: 'Återställ zoom för arbetsytan', undo: 'Ångra', redo: 'Gör om', compareHold: 'Håll för att jämföra med originalet', compareLabel: 'Jämför', fullscreenEnter: 'Öppna helskärm', fullscreenExit: 'Avsluta helskärm', resetAll: 'Återställ alla kontroller', exportPng: 'Exportera PNG', replaceImage: 'Byt bild', lightColor: 'Ljus och färg', lightColorSubtitle: 'Grundläggande tonrespons och färgbalans', brightness: 'Ljusstyrka', contrast: 'Kontrast', saturation: 'Mättnad', warmth: 'Värme', ambiance: 'Stämning', highlights: 'Högdagrar', shadows: 'Skuggor', fxFocus: 'FX och fokus', fxFocusSubtitle: 'Oskärpa, bokeh, kurvor och exponeringskomposition', globalBlur: 'Global oskärpa', lensBlur: 'Linsoskärpa', bokehFocusShift: 'Bokeh / fokusförskjutning', curves: 'Kurvor', curvesPreview: 'Förhandsvisning av kurvor', curvesStrength: 'Kurvstyrka', doubleExposure: 'Dubbelexponering', doubleExposureFile: 'Fil för dubbelexponering', exposureOpacity: 'Exponeringsopacitet', exposureBlendMode: 'Blandningsläge för exponering', geometry: 'Geometri', geometrySubtitle: 'Förberedelse av perspektiv och beskärning', perspectiveX: 'Perspektiv X', perspectiveY: 'Perspektiv Y', cropX: 'Beskärning X', cropY: 'Beskärning Y', retouch: 'Retusch', retouchSubtitle: 'Selektiv pensel och reparationskontroller', brushStrength: 'Styrka för selektiv pensel', healingX: 'Reparation X', healingY: 'Reparation Y', resetSection: 'Återställ avsnitt', seedPreview: 'Seed-förhandsvisning', dropImage: 'Släpp en bild i Seed', browseFiles: 'Bläddra bland filer', brushActive: 'Pensel aktiv · klicka på förhandsvisningen' }),
  th: make({ zoomIn: 'ขยายผืนผ้าใบ', zoomOut: 'ย่อผืนผ้าใบ', zoomReset: 'รีเซ็ตการซูมผืนผ้าใบ', undo: 'เลิกทำ', redo: 'ทำซ้ำ', compareHold: 'กดค้างเพื่อเปรียบเทียบกับต้นฉบับ', compareLabel: 'เปรียบเทียบ', fullscreenEnter: 'เข้าสู่เต็มหน้าจอ', fullscreenExit: 'ออกจากเต็มหน้าจอ', resetAll: 'รีเซ็ตการควบคุมทั้งหมด', exportPng: 'ส่งออก PNG', replaceImage: 'แทนที่รูปภาพ', lightColor: 'แสงและสี', lightColorSubtitle: 'การตอบสนองโทนหลักและสมดุลสี', brightness: 'ความสว่าง', contrast: 'คอนทราสต์', saturation: 'ความอิ่มสี', warmth: 'ความอุ่น', ambiance: 'บรรยากาศ', highlights: 'ไฮไลต์', shadows: 'เงา', fxFocus: 'FX และโฟกัส', fxFocusSubtitle: 'เบลอ โบเก้ เส้นโค้ง และการผสมแสง', globalBlur: 'เบลอทั่วภาพ', lensBlur: 'เบลอเลนส์', bokehFocusShift: 'โบเก้ / เลื่อนโฟกัส', curves: 'เส้นโค้ง', curvesPreview: 'ตัวอย่างเส้นโค้ง', curvesStrength: 'ความแรงของเส้นโค้ง', doubleExposure: 'การเปิดรับแสงซ้อน', doubleExposureFile: 'ไฟล์การเปิดรับแสงซ้อน', exposureOpacity: 'ความทึบของการรับแสง', exposureBlendMode: 'โหมดผสมการรับแสง', geometry: 'เรขาคณิต', geometrySubtitle: 'เตรียมเปอร์สเปกทีฟและการครอป', perspectiveX: 'เปอร์สเปกทีฟ X', perspectiveY: 'เปอร์สเปกทีฟ Y', cropX: 'ครอป X', cropY: 'ครอป Y', retouch: 'รีทัช', retouchSubtitle: 'แปรงเลือกเฉพาะจุดและการซ่อมแซม', brushStrength: 'ความแรงแปรงเลือกเฉพาะจุด', healingX: 'การซ่อมแซม X', healingY: 'การซ่อมแซม Y', resetSection: 'รีเซ็ตส่วน', seedPreview: 'ตัวอย่าง Seed', dropImage: 'วางรูปภาพลงใน Seed', browseFiles: 'เรียกดูไฟล์', brushActive: 'แปรงทำงาน · คลิกตัวอย่าง' }),
  tr: make({ zoomIn: 'Tuvali yakınlaştır', zoomOut: 'Tuvali uzaklaştır', zoomReset: 'Tuval yakınlaştırmasını sıfırla', undo: 'Geri al', redo: 'Yinele', compareHold: 'Orijinalle karşılaştırmak için basılı tutun', compareLabel: 'Karşılaştır', fullscreenEnter: 'Tam ekrana geç', fullscreenExit: 'Tam ekrandan çık', resetAll: 'Tüm kontrolleri sıfırla', exportPng: 'PNG dışa aktar', replaceImage: 'Görseli değiştir', lightColor: 'Işık ve renk', lightColorSubtitle: 'Temel ton tepkisi ve renk dengesi', brightness: 'Parlaklık', contrast: 'Kontrast', saturation: 'Doygunluk', warmth: 'Sıcaklık', ambiance: 'Ambiyans', highlights: 'Parlak alanlar', shadows: 'Gölgeler', fxFocus: 'FX ve odak', fxFocusSubtitle: 'Bulanıklık, bokeh, eğriler ve pozlama kompoziti', globalBlur: 'Genel bulanıklık', lensBlur: 'Lens bulanıklığı', bokehFocusShift: 'Bokeh / odak kaydırma', curves: 'Eğriler', curvesPreview: 'Eğri önizlemesi', curvesStrength: 'Eğri gücü', doubleExposure: 'Çift pozlama', doubleExposureFile: 'Çift pozlama dosyası', exposureOpacity: 'Pozlama opaklığı', exposureBlendMode: 'Pozlama karıştırma modu', geometry: 'Geometri', geometrySubtitle: 'Perspektif ve kırpma hazırlığı', perspectiveX: 'Perspektif X', perspectiveY: 'Perspektif Y', cropX: 'Kırpma X', cropY: 'Kırpma Y', retouch: 'Rötuş', retouchSubtitle: 'Seçici fırça ve iyileştirme kontrolleri', brushStrength: 'Seçici fırça gücü', healingX: 'İyileştirme X', healingY: 'İyileştirme Y', resetSection: 'Bölümü sıfırla', seedPreview: 'Seed önizlemesi', dropImage: 'Seed içine görüntü bırak', browseFiles: 'Dosyalara göz at', brushActive: 'Fırça etkin · önizlemeye tıklayın' }),
  uk: make({ zoomIn: 'Збільшити полотно', zoomOut: 'Зменшити полотно', zoomReset: 'Скинути масштаб полотна', undo: 'Скасувати', redo: 'Повторити', compareHold: 'Утримуйте для порівняння з оригіналом', compareLabel: 'Порівняти', fullscreenEnter: 'Увімкнути повний екран', fullscreenExit: 'Вийти з повного екрана', resetAll: 'Скинути всі елементи керування', exportPng: 'Експортувати PNG', replaceImage: 'Замінити зображення', lightColor: 'Світло й колір', lightColorSubtitle: 'Основна тональна реакція та баланс кольорів', brightness: 'Яскравість', contrast: 'Контраст', saturation: 'Насиченість', warmth: 'Тепло', ambiance: 'Атмосфера', highlights: 'Світла', shadows: 'Тіні', fxFocus: 'FX і фокус', fxFocusSubtitle: 'Розмиття, боке, криві та композиція експозиції', globalBlur: 'Загальне розмиття', lensBlur: 'Розмиття об’єктива', bokehFocusShift: 'Боке / зміщення фокуса', curves: 'Криві', curvesPreview: 'Попередній перегляд кривих', curvesStrength: 'Сила кривих', doubleExposure: 'Подвійна експозиція', doubleExposureFile: 'Файл подвійної експозиції', exposureOpacity: 'Непрозорість експозиції', exposureBlendMode: 'Режим змішування експозиції', geometry: 'Геометрія', geometrySubtitle: 'Підготовка перспективи та кадрування', perspectiveX: 'Перспектива X', perspectiveY: 'Перспектива Y', cropX: 'Кадрування X', cropY: 'Кадрування Y', retouch: 'Ретуш', retouchSubtitle: 'Вибірковий пензель і засоби відновлення', brushStrength: 'Сила вибіркового пензля', healingX: 'Відновлення X', healingY: 'Відновлення Y', resetSection: 'Скинути розділ', seedPreview: 'Попередній перегляд Seed', dropImage: 'Перетягніть зображення в Seed', browseFiles: 'Переглянути файли', brushActive: 'Пензель активний · натисніть попередній перегляд' }),
  vi: make({ zoomIn: 'Phóng to canvas', zoomOut: 'Thu nhỏ canvas', zoomReset: 'Đặt lại thu phóng canvas', undo: 'Hoàn tác', redo: 'Làm lại', compareHold: 'Giữ để so sánh với ảnh gốc', compareLabel: 'So sánh', fullscreenEnter: 'Vào toàn màn hình', fullscreenExit: 'Thoát toàn màn hình', resetAll: 'Đặt lại tất cả điều khiển', exportPng: 'Xuất PNG', replaceImage: 'Thay ảnh', lightColor: 'Ánh sáng và màu', lightColorSubtitle: 'Đáp ứng tông màu chính và cân bằng màu', brightness: 'Độ sáng', contrast: 'Độ tương phản', saturation: 'Độ bão hòa', warmth: 'Độ ấm', ambiance: 'Không khí', highlights: 'Vùng sáng', shadows: 'Bóng', fxFocus: 'FX và tiêu điểm', fxFocusSubtitle: 'Làm mờ, bokeh, đường cong và phối ghép phơi sáng', globalBlur: 'Làm mờ toàn cục', lensBlur: 'Làm mờ ống kính', bokehFocusShift: 'Bokeh / dịch chuyển tiêu điểm', curves: 'Đường cong', curvesPreview: 'Xem trước đường cong', curvesStrength: 'Cường độ đường cong', doubleExposure: 'Phơi sáng kép', doubleExposureFile: 'Tệp phơi sáng kép', exposureOpacity: 'Độ mờ phơi sáng', exposureBlendMode: 'Chế độ hòa trộn phơi sáng', geometry: 'Hình học', geometrySubtitle: 'Chuẩn bị phối cảnh và cắt', perspectiveX: 'Phối cảnh X', perspectiveY: 'Phối cảnh Y', cropX: 'Cắt X', cropY: 'Cắt Y', retouch: 'Chỉnh sửa', retouchSubtitle: 'Cọ chọn vùng và điều khiển phục hồi', brushStrength: 'Cường độ cọ chọn vùng', healingX: 'Phục hồi X', healingY: 'Phục hồi Y', resetSection: 'Đặt lại phần', seedPreview: 'Xem trước Seed', dropImage: 'Thả ảnh vào Seed', browseFiles: 'Duyệt tệp', brushActive: 'Cọ đang hoạt động · nhấp vào bản xem trước' }),
};
