import type { Locale } from './config';

export type ToolSeoLocale = Readonly<Record<Locale, string>>;

/** Canonical localized SEO names for image-platform tools only. */
export const TOOL_SEO_NAMES: Readonly<Record<string, ToolSeoLocale>> = Object.freeze({
  'image-compressor': Object.freeze({ en:'Image Compressor', ar:'ضاغط الصور', es:'Compresor de imágenes', fr:"Compresseur d’images", de:'Bildkompressor', hi:'इमेज कंप्रेसर', id:'Kompresor Gambar', it:'Compressore di immagini', ja:'画像圧縮', ko:'이미지 압축기', nl:'Afbeeldingscompressor', pl:'Kompresor obrazów', pt:'Compressor de Imagens', ru:'Компрессор изображений', sv:'Bildkompressor', th:'เครื่องมือบีบอัดรูปภาพ', tr:'Görsel sıkıştırıcı', vi:'Trình nén ảnh', zh:'图像压缩器', ur:'تصویر کمپریسر' }),
  'background-remover': Object.freeze({ en:'Background Remover', ar:'إزالة خلفية الصور', es:'Eliminador de fondos', fr:'Suppression d’arrière-plan', de:'Hintergrund entfernen', hi:'बैकग्राउंड रिमूवर', id:'Penghapus Latar Belakang', it:'Rimozione sfondo', ja:'背景削除', ko:'배경 제거', nl:'Achtergrond verwijderen', pl:'Usuwanie tła', pt:'Removedor de Fundo', ru:'Удаление фона', sv:'Ta bort bakgrund', th:'ลบพื้นหลัง', tr:'Arka plan kaldırma', vi:'Xóa nền ảnh', zh:'背景移除器', ur:'پس منظر ہٹانے والا' }),
  'image-upscaler': Object.freeze({ en:'Image Upscaler', ar:'تكبير الصور وتحسين دقتها', es:'Mejorador de resolución de imágenes', fr:'Améliorateur de résolution d’images', de:'Bild-Hochskalierer', hi:'इमेज अपस्केलर', id:'Peningkat Resolusi Gambar', it:'Upscaler di immagini', ja:'画像高画質化', ko:'이미지 업스케일러', nl:'Afbeeldingen opschalen', pl:'Skalowanie obrazów', pt:'Upscaler de Imagens', ru:'Масштабирование изображений', sv:'Bilduppskalare', th:'เพิ่มความละเอียดรูปภาพ', tr:'Görsel büyütücü', vi:'Tăng độ phân giải ảnh', zh:'图像放大器', ur:'تصویر اپ اسکیلر' }),
  'image-converter': Object.freeze({ en:'Image Converter', ar:'محول الصور', es:'Convertidor de imágenes', fr:'Convertisseur d’images', de:'Bildkonverter', hi:'इमेज कनवर्टर', id:'Konverter Gambar', it:'Convertitore di immagini', ja:'画像変換', ko:'이미지 변환기', nl:'Afbeeldingsconverter', pl:'Konwerter obrazów', pt:'Conversor de Imagens', ru:'Конвертер изображений', sv:'Bildkonverterare', th:'ตัวแปลงรูปภาพ', tr:'Görsel dönüştürücü', vi:'Trình chuyển đổi ảnh', zh:'图像转换器', ur:'تصویر کنورٹر' }),
  'object-remover': Object.freeze({ en:'Object Remover', ar:'إزالة العناصر من الصور', es:'Eliminador de objetos', fr:'Suppression d’objets', de:'Objekte entfernen', hi:'ऑब्जेक्ट रिमूवर', id:'Penghapus Objek', it:'Rimozione oggetti', ja:'オブジェクト削除', ko:'개체 제거', nl:'Objecten verwijderen', pl:'Usuwanie obiektów', pt:'Removedor de Objetos', ru:'Удаление объектов', sv:'Ta bort objekt', th:'ลบวัตถุ', tr:'Nesne kaldırma', vi:'Xóa đối tượng', zh:'对象移除器', ur:'آبجیکٹ ہٹانے والا' }),
  'watermark-remover': Object.freeze({ en:'Watermark Remover', ar:'إزالة العلامة المائية', es:'Eliminador de marcas de agua', fr:'Suppression de filigrane', de:'Wasserzeichen entfernen', hi:'वॉटरमार्क रिमूवर', id:'Penghapus Tanda Air', it:'Rimozione filigrana', ja:'透かし削除', ko:'워터마크 제거', nl:'Watermerk verwijderen', pl:'Usuwanie znaków wodnych', pt:'Removedor de Marca d’água', ru:'Удаление водяных знаков', sv:'Ta bort vattenstämpel', th:'ลบลายน้ำ', tr:'Filigran kaldırma', vi:'Xóa hình mờ', zh:'水印移除器', ur:'واٹر مارک ہٹانے والا' }),
  'image-cropper': Object.freeze({ en:'Image Cropper', ar:'قص الصور وتغيير حجمها', es:'Recortador de imágenes', fr:'Recadrage d’images', de:'Bild zuschneiden', hi:'इमेज क्रॉपर', id:'Pemotong Gambar', it:'Ritaglio immagini', ja:'画像トリミング', ko:'이미지 자르기', nl:'Afbeeldingen bijsnijden', pl:'Kadrowanie obrazów', pt:'Cortador de Imagens', ru:'Обрезка изображений', sv:'Beskär bilder', th:'ครอบตัดรูปภาพ', tr:'Görsel kırpma', vi:'Cắt ảnh', zh:'图像裁剪器', ur:'تصویر کراپر' }),
  'image-to-svg': Object.freeze({ en:'Image to SVG Converter', ar:'تحويل الصور إلى SVG', es:'Convertidor de imagen a SVG', fr:'Convertisseur d’image en SVG', de:'Bild-zu-SVG-Konverter', hi:'इमेज से SVG कनवर्टर', id:'Konverter Gambar ke SVG', it:'Convertitore da immagine a SVG', ja:'画像からSVG変換', ko:'이미지 SVG 변환기', nl:'Afbeelding naar SVG converter', pl:'Konwerter obrazu do SVG', pt:'Conversor de Imagem para SVG', ru:'Конвертер изображения в SVG', sv:'Bild till SVG-konverterare', th:'แปลงรูปภาพเป็น SVG', tr:'Görselden SVG dönüştürücü', vi:'Trình chuyển ảnh sang SVG', zh:'图像转 SVG 转换器', ur:'تصویر سے SVG کنورٹر' }),
  'image-ocr': Object.freeze({ en:'Image to Text OCR', ar:'استخراج النص من الصور OCR', es:'OCR de imagen a texto', fr:'OCR d’image vers texte', de:'Bild-zu-Text-OCR', hi:'इमेज OCR से टेक्स्ट', id:'OCR Gambar ke Teks', it:'OCR da immagine a testo', ja:'画像OCR文字認識', ko:'이미지 OCR 텍스트 변환', nl:'Afbeelding naar tekst OCR', pl:'OCR obrazu na tekst', pt:'OCR de Imagem para Texto', ru:'Распознавание текста на изображении', sv:'Bild till text OCR', th:'OCR รูปภาพเป็นข้อความ', tr:'Görsel OCR metin çıkarma', vi:'OCR ảnh sang văn bản', zh:'图像转文字 OCR', ur:'تصویر سے متن OCR' }),
  'background-blur': Object.freeze({ en:'Background Blur', ar:'تمويه خلفية الصورة', es:'Desenfoque de fondo', fr:'Flou d’arrière-plan', de:'Hintergrund weichzeichnen', hi:'बैकग्राउंड ब्लर', id:'Buram Latar Belakang', it:'Sfocatura dello sfondo', ja:'背景ぼかし', ko:'배경 흐림', nl:'Achtergrond vervagen', pl:'Rozmycie tła', pt:'Desfoque de Fundo', ru:'Размытие фона', sv:'Bakgrundsoskärpa', th:'เบลอพื้นหลัง', tr:'Arka plan bulanıklaştırma', vi:'Làm mờ nền', zh:'背景模糊', ur:'پس منظر دھندلا' }),
  'passport-photo-maker': Object.freeze({ en:'Passport Photo Maker', ar:'صانع صور جواز السفر', es:'Creador de fotos para pasaporte', fr:'Créateur de photos d’identité', de:'Passfoto-Ersteller', hi:'पासपोर्ट फोटो मेकर', id:'Pembuat Foto Paspor', it:'Creatore di foto per passaporto', ja:'パスポート写真メーカー', ko:'여권 사진 만들기', nl:'Pasfoto maker', pl:'Kreator zdjęć paszportowych', pt:'Criador de Fotos para Passaporte', ru:'Создатель фото на паспорт', sv:'Passfotoverktyg', th:'สร้างรูปถ่ายหนังสือเดินทาง', tr:'Pasaport fotoğrafı oluşturucu', vi:'Tạo ảnh hộ chiếu', zh:'证件照制作器', ur:'پاسپورٹ فوٹو میکر' }),
  'watermark-adder': Object.freeze({ en:'Watermark Adder', ar:'إضافة علامة مائية', es:'Añadir marca de agua', fr:'Ajouter un filigrane', de:'Wasserzeichen hinzufügen', hi:'वॉटरमार्क जोड़ें', id:'Penambah Tanda Air', it:'Aggiungi filigrana', ja:'透かし追加', ko:'워터마크 추가', nl:'Watermerk toevoegen', pl:'Dodawanie znaku wodnego', pt:'Adicionar Marca d’água', ru:'Добавление водяного знака', sv:'Lägg till vattenstämpel', th:'เพิ่มลายน้ำ', tr:'Filigran ekleme', vi:'Thêm hình mờ', zh:'添加水印', ur:'واٹر مارک شامل کرنا' }),
  'meme-generator': Object.freeze({ en:'Meme Generator', ar:'منشئ الميمات', es:'Generador de memes', fr:'Générateur de mèmes', de:'Meme-Generator', hi:'मीम जनरेटर', id:'Generator Meme', it:'Generatore di meme', ja:'ミームジェネレーター', ko:'밈 생성기', nl:'Memegenerator', pl:'Generator memów', pt:'Gerador de Memes', ru:'Генератор мемов', sv:'Memgenerator', th:'เครื่องมือสร้างมีม', tr:'Meme oluşturucu', vi:'Trình tạo meme', zh:'表情包生成器', ur:'میم جنریٹر' }),
  'collage-maker': Object.freeze({ en:'Collage Maker', ar:'منشئ الكولاج', es:'Creador de collages', fr:'Créateur de collages', de:'Collage-Ersteller', hi:'कोलाज मेकर', id:'Pembuat Kolase', it:'Creatore di collage', ja:'コラージュ作成', ko:'콜라주 만들기', nl:'Collagemaker', pl:'Kreator kolaży', pt:'Criador de Colagens', ru:'Создатель коллажей', sv:'Kollageverktyg', th:'เครื่องมือสร้างภาพคอลลาจ', tr:'Kolaj oluşturucu', vi:'Trình tạo ảnh ghép', zh:'拼贴画制作器', ur:'کولاج میکر' }),
  'image-effects': Object.freeze({ en:'Image Effects', ar:'تأثيرات الصور', es:'Efectos de imagen', fr:'Effets d’image', de:'Bildeffekte', hi:'इमेज इफेक्ट्स', id:'Efek Gambar', it:'Effetti immagine', ja:'画像エフェクト', ko:'이미지 효과', nl:'Afbeeldingseffecten', pl:'Efekty obrazów', pt:'Efeitos de Imagem', ru:'Эффекты изображения', sv:'Bildeffekter', th:'เอฟเฟกต์รูปภาพ', tr:'Görsel efektleri', vi:'Hiệu ứng ảnh', zh:'图像效果', ur:'تصویری اثرات' }),
  'exif-cleaner': Object.freeze({ en:'EXIF Metadata Remover', ar:'إزالة بيانات EXIF', es:'Eliminador de metadatos EXIF', fr:'Suppression des métadonnées EXIF', de:'EXIF-Metadaten entfernen', hi:'EXIF मेटाडेटा रिमूवर', id:'Penghapus Metadata EXIF', it:'Rimozione metadati EXIF', ja:'EXIFメタデータ削除', ko:'EXIF 메타데이터 제거', nl:'EXIF-metadata verwijderen', pl:'Usuwanie metadanych EXIF', pt:'Removedor de Metadados EXIF', ru:'Удаление EXIF-метаданных', sv:'Ta bort EXIF-metadata', th:'ลบข้อมูลเมตา EXIF', tr:'EXIF meta verilerini kaldırma', vi:'Xóa siêu dữ liệu EXIF', zh:'EXIF 元数据移除器', ur:'EXIF میٹا ڈیٹا ہٹانے والا' }),
  'svg-optimizer': Object.freeze({ en:'SVG Optimizer', ar:'تحسين ملفات SVG', es:'Optimizador SVG', fr:'Optimiseur SVG', de:'SVG-Optimierer', hi:'SVG ऑप्टिमाइज़र', id:'Pengoptimal SVG', it:'Ottimizzatore SVG', ja:'SVG最適化', ko:'SVG 최적화기', nl:'SVG-optimizer', pl:'Optymalizator SVG', pt:'Otimizador SVG', ru:'Оптимизатор SVG', sv:'SVG-optimerare', th:'เครื่องมือเพิ่มประสิทธิภาพ SVG', tr:'SVG iyileştirici', vi:'Trình tối ưu hóa SVG', zh:'SVG 优化器', ur:'SVG آپٹمائزر' }),
  'mockup-generator': Object.freeze({ en:'Mockup Generator', ar:'منشئ نماذج العرض', es:'Generador de mockups', fr:'Générateur de mockups', de:'Mockup-Generator', hi:'मॉकअप जनरेटर', id:'Generator Mockup', it:'Generatore di mockup', ja:'モックアップ生成', ko:'목업 생성기', nl:'Mockupgenerator', pl:'Generator makiet', pt:'Gerador de Mockups', ru:'Генератор мокапов', sv:'Mockupgenerator', th:'เครื่องมือสร้างม็อกอัป', tr:'Mockup oluşturucu', vi:'Trình tạo mockup', zh:'模型生成器', ur:'موک اپ جنریٹر' }),
  seed: Object.freeze({ en:'Seed Image Editor', ar:'محرر الصور Seed', es:'Editor de imágenes Seed', fr:'Éditeur d’images Seed', de:'Seed-Bildeditor', hi:'Seed इमेज एडिटर', id:'Editor Imej Seed', it:'Editor immagini Seed', ja:'Seed画像エディター', ko:'Seed 이미지 편집기', nl:'Seed-afbeeldingseditor', pl:'Edytor obrazów Seed', pt:'Editor de Imagens Seed', ru:'Фоторедактор Seed', sv:'Seed-bildredigerare', th:'เครื่องมือแก้ไขรูปภาพ Seed', tr:'Seed Görsel Düzenleyici', vi:'Trình chỉnh sửa ảnh Seed', zh:'Seed 图像编辑器', ur:'Seed امیج ایڈیٹر' }),
  pix: Object.freeze({ en:'Pix Studio', ar:'استوديو Pix', es:'Estudio Pix', fr:'Studio Pix', de:'Pix Studio', hi:'Pix स्टूडियो', id:'Studio Pix', it:'Studio Pix', ja:'Pix スタジオ', ko:'Pix 스튜디오', nl:'Pix Studio', pl:'Studio Pix', pt:'Estúdio Pix', ru:'Студия Pix', sv:'Pix Studio', th:'Pix Studio', tr:'Pix Stüdyo', vi:'Xưởng Pix', zh:'Pix 工作室', ur:'Pix اسٹوڈیو' }),
  'ai-image-generator': Object.freeze({ en:'AI Image Generator', ar:'مولد الصور بالذكاء الاصطناعي', es:'Generador de imágenes con IA', fr:'Générateur d’images IA', de:'KI-Bildgenerator', hi:'एआई इमेज जनरेटर', id:'Generator Gambar AI', it:'Generatore di immagini AI', ja:'AI画像生成', ko:'AI 이미지 생성기', nl:'AI-afbeeldingsgenerator', pl:'Generator obrazów AI', pt:'Gerador de Imagens com IA', ru:'AI-генератор изображений', sv:'AI-bildgenerator', th:'เครื่องมือสร้างรูปภาพ AI', tr:'Yapay zekâ görsel oluşturucu', vi:'Trình tạo ảnh AI', zh:'AI 图像生成器', ur:'AI تصویر جنریٹر' }),
  'photo-colorizer': Object.freeze({ en:'Photo Colorizer', ar:'ملوّن الصور', es:'Colorizador de fotos', fr:'Coloriseur de photos', de:'Fotokolorierer', hi:'फोटो कलराइज़र', id:'Pewarna Foto', it:'Colorizzatore di foto', ja:'写真カラー化', ko:'사진 색상화', nl:'Foto-kleurgever', pl:'Koloryzator zdjęć', pt:'Colorizador de Fotos', ru:'Колоризатор фотографий', sv:'Fotokoloriserare', th:'เครื่องมือเติมสีภาพถ่าย', tr:'Fotoğraf renklendirici', vi:'Trình tô màu ảnh', zh:'照片上色器', ur:'تصویر کلرائزر' }),
});

export function getToolSeoName(toolId: string, locale: Locale): string | undefined {
  return TOOL_SEO_NAMES[toolId]?.[locale];
}
