import type { Locale } from './config.ts';
import { LOCALES } from './config.ts';

export type ToolSeoLocale = Readonly<Record<Locale, string>>;

/** Human-reviewed SEO names. IDs and URLs stay stable. */
export const TOOL_SEO_NAMES: Readonly<Record<string, ToolSeoLocale>> = Object.freeze({
  'image-compressor': Object.freeze({ en:'Image Compressor', ar:'ضاغط الصور', es:'Compresor de imágenes', fr:"Compresseur d’images", de:'Bildkompressor', ru:'Компрессор изображений', zh:'图片压缩器', hi:'इमेज कंप्रेसर', id:'Kompresor Gambar', ur:'امیج کمپریسر', ja:'画像圧縮', pt:'Compressor de Imagens', it:'Compressore di immagini', ko:'이미지 압축기', nl:'Afbeeldingscompressor', pl:'Kompresor obrazów', tr:'Görsel sıkıştırıcı', vi:'Trình nén ảnh', th:'เครื่องมือบีบอัดรูปภาพ', sv:'Bildkompressor' }),
  'background-remover': Object.freeze({ en:'Background Remover', ar:'إزالة خلفية الصور', es:'Eliminador de fondos', fr:'Suppression d’arrière-plan', de:'Hintergrund entfernen', ru:'Удаление фона', zh:'背景移除器', hi:'बैकग्राउंड रिमूवर', id:'Penghapus Latar Belakang', ur:'بیک گراؤنڈ ریموور', ja:'背景削除', pt:'Removedor de Fundo', it:'Rimozione sfondo', ko:'배경 제거', nl:'Achtergrond verwijderen', pl:'Usuwanie tła', tr:'Arka plan kaldırma', vi:'Xóa nền ảnh', th:'ลบพื้นหลัง', sv:'Ta bort bakgrund' }),
  'image-upscaler': Object.freeze({ en:'Image Upscaler', ar:'تكبير الصور وتحسين دقتها', es:'Mejorador de resolución de imágenes', fr:'Améliorateur de résolution d’images', de:'Bild-Hochskalierer', ru:'Масштабирование изображений', zh:'图片放大与增强', hi:'इमेज अपस्केलर', id:'Peningkat Resolusi Gambar', ur:'تصاویر کی ریزولوشن بڑھانے والا', ja:'画像高画質化', pt:'Upscaler de Imagens', it:'Upscaler di immagini', ko:'이미지 업스케일러', nl:'Afbeeldingen opschalen', pl:'Skalowanie obrazów', tr:'Görsel büyütücü', vi:'Tăng độ phân giải ảnh', th:'เพิ่มความละเอียดรูปภาพ', sv:'Bilduppskalare' }),
  'image-converter': Object.freeze({ en:'Image Converter', ar:'محول الصور', es:'Convertidor de imágenes', fr:'Convertisseur d’images', de:'Bildkonverter', ru:'Конвертер изображений', zh:'图片格式转换器', hi:'इमेज कनवर्टर', id:'Konverter Gambar', ur:'امیج کنورٹر', ja:'画像変換', pt:'Conversor de Imagens', it:'Convertitore di immagini', ko:'이미지 변환기', nl:'Afbeeldingsconverter', pl:'Konwerter obrazów', tr:'Görsel dönüştürücü', vi:'Trình chuyển đổi ảnh', th:'ตัวแปลงรูปภาพ', sv:'Bildkonverterare' }),
  'object-remover': Object.freeze({ en:'Object Remover', ar:'إزالة العناصر من الصور', es:'Eliminador de objetos', fr:'Suppression d’objets', de:'Objekte entfernen', ru:'Удаление объектов', zh:'对象移除器', hi:'ऑब्जेक्ट रिमूवर', id:'Penghapus Objek', ur:'آبجیکٹ ریموور', ja:'オブジェクト削除', pt:'Removedor de Objetos', it:'Rimozione oggetti', ko:'개체 제거', nl:'Objecten verwijderen', pl:'Usuwanie obiektów', tr:'Nesne kaldırma', vi:'Xóa đối tượng', th:'ลบวัตถุ', sv:'Ta bort objekt' }),
  'watermark-remover': Object.freeze({ en:'Watermark Remover', ar:'إزالة العلامة المائية', es:'Eliminador de marcas de agua', fr:'Suppression de filigrane', de:'Wasserzeichen entfernen', ru:'Удаление водяных знаков', zh:'去水印', hi:'वॉटरमार्क रिमूवर', id:'Penghapus Tanda Air', ur:'واٹر مارک ریموور', ja:'透かし削除', pt:'Removedor de Marca d’água', it:'Rimozione filigrana', ko:'워터마크 제거', nl:'Watermerk verwijderen', pl:'Usuwanie znaków wodnych', tr:'Filigran kaldırma', vi:'Xóa hình mờ', th:'ลบลายน้ำ', sv:'Ta bort vattenstämpel' }),
  'image-cropper': Object.freeze({ en:'Image Cropper', ar:'قص الصور وتغيير حجمها', es:'Recortador de imágenes', fr:'Recadrage d’images', de:'Bild zuschneiden', ru:'Обрезка изображений', zh:'图片裁剪器', hi:'इमेज क्रॉपर', id:'Pemotong Gambar', ur:'امیج کراپر', ja:'画像トリミング', pt:'Cortador de Imagens', it:'Ritaglio immagini', ko:'이미지 자르기', nl:'Afbeeldingen bijsnijden', pl:'Kadrowanie obrazów', tr:'Görsel kırpma', vi:'Cắt ảnh', th:'ครอบตัดรูปภาพ', sv:'Beskär bilder' }),
  'image-to-svg': Object.freeze({ en:'Image to SVG Converter', ar:'تحويل الصور إلى SVG', es:'Convertidor de imagen a SVG', fr:'Convertisseur d’image en SVG', de:'Bild-zu-SVG-Konverter', ru:'Конвертер изображения в SVG', zh:'图片转 SVG', hi:'इमेज से SVG कनवर्टर', id:'Konverter Gambar ke SVG', ur:'امیج سے SVG کنورٹر', ja:'画像からSVG変換', pt:'Conversor de Imagem para SVG', it:'Convertitore da immagine a SVG', ko:'이미지 SVG 변환기', nl:'Afbeelding naar SVG converter', pl:'Konwerter obrazu do SVG', tr:'Görselden SVG dönüştürücü', vi:'Trình chuyển ảnh sang SVG', th:'แปลงรูปภาพเป็น SVG', sv:'Bild till SVG-konverterare' }),
  'image-ocr': Object.freeze({ en:'Image to Text OCR', ar:'استخراج النص من الصور OCR', es:'OCR de imagen a texto', fr:'OCR d’image vers texte', de:'Bild-zu-Text-OCR', ru:'Распознавание текста на изображении', zh:'图片 OCR 文字识别', hi:'इमेज OCR से टेक्स्ट', id:'OCR Gambar ke Teks', ur:'امیج OCR ٹو ٹیکسٹ', ja:'画像OCR文字認識', pt:'OCR de Imagem para Texto', it:'OCR da immagine a testo', ko:'이미지 OCR 텍스트 변환', nl:'Afbeelding naar tekst OCR', pl:'OCR obrazu na tekst', tr:'Görsel OCR metin çıkarma', vi:'OCR ảnh sang văn bản', th:'OCR รูปภาพเป็นข้อความ', sv:'Bild till text OCR' }),
  'background-blur': Object.freeze({ en:'Background Blur', ar:'تمويه خلفية الصورة', es:'Desenfoque de fondo', fr:'Flou d’arrière-plan', de:'Hintergrund weichzeichnen', ru:'Размытие фона', zh:'背景虚化', hi:'बैकग्राउंड ब्लर', id:'Buram Latar Belakang', ur:'بیک گراؤنڈ بلر', ja:'背景ぼかし', pt:'Desfoque de Fundo', it:'Sfocatura dello sfondo', ko:'배경 흐림', nl:'Achtergrond vervagen', pl:'Rozmycie tła', tr:'Arka plan bulanıklaştırma', vi:'Làm mờ nền', th:'เบลอพื้นหลัง', sv:'Bakgrundsoskärpa' }),
  'passport-photo-maker': Object.freeze({ en:'Passport Photo Maker', ar:'صانع صور جواز السفر', es:'Creador de fotos para pasaporte', fr:'Créateur de photos d’identité', de:'Passfoto-Ersteller', ru:'Создатель фото на паспорт', zh:'证件照制作器', hi:'पासपोर्ट फोटो मेकर', id:'Pembuat Foto Paspor', ur:'پاسپورٹ فوٹو میکر', ja:'パスポート写真メーカー', pt:'Criador de Fotos para Passaporte', it:'Creatore di foto per passaporto', ko:'여권 사진 만들기', nl:'Pasfoto maker', pl:'Kreator zdjęć paszportowych', tr:'Pasaport fotoğrafı oluşturucu', vi:'Tạo ảnh hộ chiếu', th:'สร้างรูปถ่ายหนังสือเดินทาง', sv:'Passfotoverktyg' }),
  'watermark-adder': Object.freeze({ en:'Watermark Adder', ar:'إضافة علامة مائية', es:'Añadir marca de agua', fr:'Ajouter un filigrane', de:'Wasserzeichen hinzufügen', ru:'Добавление водяных знаков', zh:'添加水印', hi:'वॉटरमार्क जोड़ें', id:'Penambah Tanda Air', ur:'واٹر مارک شامل کریں', ja:'透かし追加', pt:'Adicionar Marca d’água', it:'Aggiungi filigrana', ko:'워터마크 추가', nl:'Watermerk toevoegen', pl:'Dodawanie znaku wodnego', tr:'Filigran ekleme', vi:'Thêm hình mờ', th:'เพิ่มลายน้ำ', sv:'Lägg till vattenstämpel' }),
  'meme-generator': Object.freeze({ en:'Meme Generator', ar:'منشئ الميمات', es:'Generador de memes', fr:'Générateur de mèmes', de:'Meme-Generator', ru:'Генератор мемов', zh:'表情包生成器', hi:'मीम जनरेटर', id:'Generator Meme', ur:'میم جنریٹر', ja:'ミームジェネレーター', pt:'Gerador de Memes', it:'Generatore di meme', ko:'밈 생성기', nl:'Memegenerator', pl:'Generator memów', tr:'Meme oluşturucu', vi:'Trình tạo meme', th:'เครื่องมือสร้างมีม', sv:'Memgenerator' }),
  'collage-maker': Object.freeze({ en:'Collage Maker', ar:'منشئ الكولاج', es:'Creador de collages', fr:'Créateur de collages', de:'Collage-Ersteller', ru:'Создатель коллажей', zh:'拼贴画制作器', hi:'कोलाज मेकर', id:'Pembuat Kolase', ur:'کولاج میکر', ja:'コラージュ作成', pt:'Criador de Colagens', it:'Creatore di collage', ko:'콜라주 만들기', nl:'Collagemaker', pl:'Kreator kolaży', tr:'Kolaj oluşturucu', vi:'Trình tạo ảnh ghép', th:'เครื่องมือสร้างภาพคอลลาจ', sv:'Kollageverktyg' }),
  'image-effects': Object.freeze({ en:'Image Effects', ar:'تأثيرات الصور', es:'Efectos de imagen', fr:'Effets d’image', de:'Bildeffekte', ru:'Эффекты изображения', zh:'图片效果', hi:'इमेज इफेक्ट्स', id:'Efek Gambar', ur:'امیج ایفیکٹس', ja:'画像エフェクト', pt:'Efeitos de Imagem', it:'Effetti immagine', ko:'이미지 효과', nl:'Afbeeldingseffecten', pl:'Efekty obrazów', tr:'Görsel efektleri', vi:'Hiệu ứng ảnh', th:'เอฟเฟกต์รูปภาพ', sv:'Bildeffekter' }),
  'exif-cleaner': Object.freeze({ en:'EXIF Metadata Remover', ar:'إزالة بيانات EXIF', es:'Eliminador de metadatos EXIF', fr:'Suppression des métadonnées EXIF', de:'EXIF-Metadaten entfernen', ru:'Удаление EXIF-метаданных', zh:'EXIF 元数据清理', hi:'EXIF मेटाडेटा रिमूवर', id:'Penghapus Metadata EXIF', ur:'EXIF میٹا ڈیٹا ریموور', ja:'EXIFメタデータ削除', pt:'Removedor de Metadados EXIF', it:'Rimozione metadati EXIF', ko:'EXIF 메타데이터 제거', nl:'EXIF-metadata verwijderen', pl:'Usuwanie metadanych EXIF', tr:'EXIF meta verilerini kaldırma', vi:'Xóa siêu dữ liệu EXIF', th:'ลบข้อมูลเมตา EXIF', sv:'Ta bort EXIF-metadata' }),
  'svg-optimizer': Object.freeze({ en:'SVG Optimizer', ar:'تحسين ملفات SVG', es:'Optimizador SVG', fr:'Optimiseur SVG', de:'SVG-Optimierer', ru:'Оптимизатор SVG', zh:'SVG 优化器', hi:'SVG ऑप्टिमाइज़र', id:'Pengoptimal SVG', ur:'SVG آپٹیمائزر', ja:'SVG最適化', pt:'Otimizador SVG', it:'Ottimizzatore SVG', ko:'SVG 최적화기', nl:'SVG-optimizer', pl:'Optymalizator SVG', tr:'SVG iyileştirici', vi:'Trình tối ưu SVG', th:'เครื่องมือเพิ่มประสิทธิภาพ SVG', sv:'SVG-optimerare' }),
  'mockup-generator': Object.freeze({ en:'Mockup Generator', ar:'مولد نماذج العرض', es:'Generador de maquetas', fr:'Générateur de maquettes', de:'Mockup-Generator', ru:'Генератор мокапов', zh:'样机生成器', hi:'मॉकअप जनरेटर', id:'Generator Mockup', ur:'موک اپ جنریٹر', ja:'モックアップ生成', pt:'Gerador de Mockups', it:'Generatore di mockup', ko:'목업 생성기', nl:'Mockupgenerator', pl:'Generator makiet', tr:'Mockup oluşturucu', vi:'Trình tạo mockup', th:'เครื่องมือสร้างม็อกอัป', sv:'Mockupgenerator' }),
  seed: Object.freeze({ en:'Seed Tool', ar:'أداة Seed', es:'Herramienta Seed', fr:'Outil Seed', de:'Seed-Werkzeug', ru:'Инструмент Seed', zh:'Seed 工具', hi:'Seed टूल', id:'Alat Seed', ur:'Seed ٹول', ja:'Seed ツール', pt:'Ferramenta Seed', it:'Strumento Seed', ko:'Seed 도구', nl:'Seed-tool', pl:'Narzędzie Seed', tr:'Seed aracı', vi:'Công cụ Seed', th:'เครื่องมือ Seed', sv:'Seed-verktyg' }),
  pix: Object.freeze({ en:'Pix Studio', ar:'استوديو Pix', es:'Estudio Pix', fr:'Studio Pix', de:'Pix Studio', ru:'Студия Pix', zh:'Pix 工作室', hi:'Pix स्टूडियो', id:'Studio Pix', ur:'Pix اسٹوڈیو', ja:'Pix スタジオ', pt:'Estúdio Pix', it:'Studio Pix', ko:'Pix 스튜디오', nl:'Pix Studio', pl:'Studio Pix', tr:'Pix Studio', vi:'Studio Pix', th:'สตูดิโอ Pix', sv:'Pix Studio' }),
  'pdf-merger-splitter': Object.freeze({ en:'PDF Merger & Splitter', ar:'دمج وتقسيم PDF', es:'Unir y dividir PDF', fr:'Fusionner et diviser des PDF', de:'PDF zusammenfügen und teilen', ru:'Объединение и разделение PDF', zh:'PDF 合并与拆分', hi:'PDF मर्ज और स्प्लिटर', id:'Penggabung & Pemisah PDF', ur:'PDF مرجر اور اسپلٹر', ja:'PDF結合・分割', pt:'Mesclar e Dividir PDF', it:'Unione e divisione PDF', ko:'PDF 병합 및 분할', nl:'PDF samenvoegen en splitsen', pl:'Scalanie i dzielenie PDF', tr:'PDF birleştirme ve bölme', vi:'Gộp và tách PDF', th:'รวมและแยก PDF', sv:'Slå ihop och dela PDF' }),
  'pdf-compressor': Object.freeze({ en:'PDF Compressor', ar:'ضغط PDF', es:'Compresor de PDF', fr:'Compresseur PDF', de:'PDF-Kompressor', ru:'Компрессор PDF', zh:'PDF 压缩器', hi:'PDF कंप्रेसर', id:'Kompresor PDF', ur:'PDF کمپریسر', ja:'PDF圧縮', pt:'Compressor de PDF', it:'Compressore PDF', ko:'PDF 압축기', nl:'PDF-compressor', pl:'Kompresor PDF', tr:'PDF sıkıştırıcı', vi:'Trình nén PDF', th:'เครื่องมือบีบอัด PDF', sv:'PDF-kompressor' }),
  'image-to-pdf': Object.freeze({ en:'Image to PDF Converter', ar:'تحويل الصور إلى PDF', es:'Convertidor de imagen a PDF', fr:'Convertisseur d’image en PDF', de:'Bild-zu-PDF-Konverter', ru:'Конвертер изображений в PDF', zh:'图片转 PDF', hi:'इमेज से PDF कनवर्टर', id:'Konverter Gambar ke PDF', ur:'امیج سے PDF کنورٹر', ja:'画像からPDF変換', pt:'Conversor de Imagem para PDF', it:'Convertitore da immagine a PDF', ko:'이미지 PDF 변환기', nl:'Afbeelding naar PDF-converter', pl:'Konwerter obrazu do PDF', tr:'Görselden PDF dönüştürücü', vi:'Trình chuyển ảnh sang PDF', th:'แปลงรูปภาพเป็น PDF', sv:'Bild till PDF-konverterare' }),
  'pdf-unlock-protect': Object.freeze({ en:'PDF Unlock & Protect', ar:'فتح وحماية PDF', es:'Desbloquear y proteger PDF', fr:'Déverrouiller et protéger un PDF', de:'PDF entsperren und schützen', ru:'Разблокировка и защита PDF', zh:'PDF 解锁与保护', hi:'PDF अनलॉक और प्रोटेक्ट', id:'Buka & Lindungi PDF', ur:'PDF ان لاک اور پروٹیکٹ', ja:'PDFロック解除・保護', pt:'Desbloquear e Proteger PDF', it:'Sblocca e proteggi PDF', ko:'PDF 잠금 해제 및 보호', nl:'PDF ontgrendelen en beveiligen', pl:'Odblokowanie i ochrona PDF', tr:'PDF kilidini açma ve koruma', vi:'Mở khóa và bảo vệ PDF', th:'ปลดล็อกและป้องกัน PDF', sv:'Lås upp och skydda PDF' }),
  'pdf-to-text': Object.freeze({ en:'PDF to Text', ar:'تحويل PDF إلى نص', es:'PDF a texto', fr:'PDF vers texte', de:'PDF zu Text', ru:'PDF в текст', zh:'PDF 转文本', hi:'PDF से टेक्स्ट', id:'PDF ke Teks', ur:'PDF سے ٹیکسٹ', ja:'PDFからテキスト', pt:'PDF para Texto', it:'PDF in testo', ko:'PDF 텍스트 변환', nl:'PDF naar tekst', pl:'PDF do tekstu', tr:'PDF metne dönüştürme', vi:'PDF sang văn bản', th:'แปลง PDF เป็นข้อความ', sv:'PDF till text' }),
  'audio-extractor-muter': Object.freeze({ en:'Audio Extractor & Muter', ar:'استخراج وكتم الصوت', es:'Extractor y silenciador de audio', fr:'Extracteur et sourdine audio', de:'Audio extrahieren und stummschalten', ru:'Извлечение и отключение звука', zh:'音频提取与静音', hi:'ऑडियो एक्सट्रैक्टर और म्यूटर', id:'Pengekstrak & Pembisuan Audio', ur:'آڈیو ایکسٹریکٹر اور میوٹر', ja:'音声抽出・ミュート', pt:'Extrator e Silenciador de Áudio', it:'Estrattore e silenziatore audio', ko:'오디오 추출 및 음소거', nl:'Audio-extractor & demper', pl:'Ekstraktor i wyciszacz audio', tr:'Ses çıkarıcı ve sessize alıcı', vi:'Trình tách và tắt tiếng âm thanh', th:'เครื่องมือแยกและปิดเสียง', sv:'Ljudextraherare och ljud av' }),
  'audio-cutter-trimmer': Object.freeze({ en:'Audio Cutter & Trimmer', ar:'قص وتشذيب الصوت', es:'Cortador y recortador de audio', fr:'Coupeur et éditeur audio', de:'Audio schneiden und trimmen', ru:'Обрезка аудио', zh:'音频剪辑与裁剪', hi:'ऑडियो कटर और ट्रिमर', id:'Pemotong & Pemangkas Audio', ur:'آڈیو کٹر اور ٹریمر', ja:'音声カッター・トリマー', pt:'Cortador e Aparador de Áudio', it:'Taglia e ritaglia audio', ko:'오디오 자르기 및 트리밍', nl:'Audio-knipper en trimmer', pl:'Przycinanie audio', tr:'Ses kesici ve kırpıcı', vi:'Cắt và chỉnh sửa âm thanh', th:'ตัดและตัดแต่งเสียง', sv:'Ljudklippare och trimmer' }),
  'audio-compressor': Object.freeze({ en:'Audio Compressor', ar:'ضاغط الصوت', es:'Compresor de audio', fr:'Compresseur audio', de:'Audio-Kompressor', ru:'Компрессор аудио', zh:'音频压缩器', hi:'ऑडियो कंप्रेसर', id:'Kompresor Audio', ur:'آڈیو کمپریسر', ja:'音声圧縮', pt:'Compressor de Áudio', it:'Compressore audio', ko:'오디오 압축기', nl:'Audiocompressor', pl:'Kompresor audio', tr:'Ses sıkıştırıcı', vi:'Trình nén âm thanh', th:'เครื่องมือบีบอัดเสียง', sv:'Ljudkompressor' }),
  'audio-noise-reducer': Object.freeze({ en:'Audio Noise Reducer', ar:'تقليل ضوضاء الصوت', es:'Reductor de ruido de audio', fr:'Réducteur de bruit audio', de:'Audio-Rauschreduzierung', ru:'Шумоподавление аудио', zh:'音频降噪', hi:'ऑडियो नॉइज़ रिड्यूसर', id:'Pengurang Noise Audio', ur:'آڈیو شور کم کرنے والا', ja:'音声ノイズ低減', pt:'Redutor de Ruído de Áudio', it:'Riduzione rumore audio', ko:'오디오 노이즈 감소', nl:'Audioruisonderdrukker', pl:'Redukcja szumów audio', tr:'Ses gürültüsü azaltıcı', vi:'Giảm tiếng ồn âm thanh', th:'ลดเสียงรบกวน', sv:'Ljudbrusreducerare' }),
  'video-trimmer-splitter': Object.freeze({ en:'Video Trimmer & Splitter', ar:'تشذيب وتقسيم الفيديو', es:'Recortador y divisor de video', fr:'Éditeur et séparateur vidéo', de:'Video trimmen und teilen', ru:'Обрезка и разделение видео', zh:'视频裁剪与分割', hi:'वीडियो ट्रिमर और स्प्लिटर', id:'Pemangkas & Pemisah Video', ur:'ویڈیو ٹریمر اور اسپلٹر', ja:'動画トリミング・分割', pt:'Aparador e Divisor de Vídeo', it:'Trimmer e divisore video', ko:'비디오 트리머 및 분할기', nl:'Videotrimmer en splitter', pl:'Przycinanie i dzielenie wideo', tr:'Video kırpma ve bölme', vi:'Cắt và chia video', th:'ตัดและแยกวิดีโอ', sv:'Videotrimmer och delare' }),
  'video-gif-meme': Object.freeze({ en:'Video to GIF & Meme Generator', ar:'تحويل الفيديو إلى GIF ومنشئ الميمات', es:'Video a GIF y generador de memes', fr:'Vidéo en GIF et générateur de mèmes', de:'Video zu GIF und Meme-Generator', ru:'Видео в GIF и генератор мемов', zh:'视频转 GIF 与表情包生成器', hi:'वीडियो से GIF और मीम जनरेटर', id:'Video ke GIF & Generator Meme', ur:'ویڈیو سے GIF اور میم جنریٹر', ja:'動画GIF・ミーム生成', pt:'Vídeo para GIF e Gerador de Memes', it:'Video in GIF e generatore di meme', ko:'비디오 GIF 및 밈 생성기', nl:'Video naar GIF en memegenerator', pl:'Wideo do GIF i generator memów', tr:'Video GIF ve meme oluşturucu', vi:'Chuyển video sang GIF & tạo meme', th:'แปลงวิดีโอเป็น GIF และสร้างมีม', sv:'Video till GIF och memgenerator' }),
  'video-compressor-converter': Object.freeze({ en:'Video Compressor & Converter', ar:'ضغط وتحويل الفيديو', es:'Compresor y convertidor de video', fr:'Compresseur et convertisseur vidéo', de:'Video-Kompressor und Konverter', ru:'Компрессор и конвертер видео', zh:'视频压缩与转换器', hi:'वीडियो कंप्रेसर और कनवर्टर', id:'Kompresor & Konverter Video', ur:'ویڈیو کمپریسر اور کنورٹر', ja:'動画圧縮・変換', pt:'Compressor e Conversor de Vídeo', it:'Compressore e convertitore video', ko:'비디오 압축 및 변환', nl:'Videocompressor en converter', pl:'Kompresor i konwerter wideo', tr:'Video sıkıştırıcı ve dönüştürücü', vi:'Trình nén và chuyển đổi video', th:'บีบอัดและแปลงวิดีโอ', sv:'Videokompressor och konverterare' }),
  'ai-captioner-srt': Object.freeze({ en:'AI Captioner & SRT Generator', ar:'منشئ ترجمات AI وSRT تلقائي', es:'Generador de subtítulos AI y SRT', fr:'Générateur de sous-titres AI et SRT', de:'AI-Untertitel- und SRT-Generator', ru:'AI-генератор субтитров и SRT', zh:'AI 字幕与 SRT 生成器', hi:'AI कैप्शन और SRT जनरेटर', id:'Generator Caption AI & SRT', ur:'AI کیپشن اور SRT جنریٹر', ja:'AI字幕・SRT生成', pt:'Gerador de Legendas AI e SRT', it:'Generatore di sottotitoli AI e SRT', ko:'AI 자막 및 SRT 생성기', nl:'AI-ondertitel- en SRT-generator', pl:'Generator napisów AI i SRT', tr:'AI altyazı ve SRT oluşturucu', vi:'Trình tạo phụ đề AI & SRT', th:'เครื่องมือสร้างคำบรรยาย AI และ SRT', sv:'AI-textnings- och SRT-generator' }),
  'ai-vocal-instrumental-remover': Object.freeze({ en:'AI Vocal & Instrumental Remover', ar:'إزالة الغناء والآلات بالذكاء الاصطناعي', es:'Eliminador de voces e instrumentales AI', fr:'Suppression des voix et instrumentaux par IA', de:'AI-Vocal- und Instrumental-Entferner', ru:'AI-удаление вокала и инструментала', zh:'AI 人声与伴奏分离', hi:'AI वोकल और इंस्ट्रुमेंटल रिमूवर', id:'Penghapus Vokal & Instrumental AI', ur:'AI ووکل اور انسٹرومنٹل ریموور', ja:'AIボーカル・インストゥルメンタル除去', pt:'Removedor de Vocais e Instrumentais com IA', it:'Rimozione vocale e strumentale AI', ko:'AI 보컬 및 반주 제거', nl:'AI-vocalen- en instrumentalenverwijderaar', pl:'Usuwanie wokalu i instrumentalu AI', tr:'AI vokal ve enstrümantal kaldırıcı', vi:'Công cụ xóa giọng hát & nhạc cụ AI', th:'ลบเสียงร้องและดนตรีด้วย AI', sv:'AI-vokal- och instrumentborttagare' }),
  'ai-image-generator': Object.freeze({ en:'AI Image Generator', ar:'مولد الصور بالذكاء الاصطناعي', es:'Generador de imágenes AI', fr:'Générateur d’images AI', de:'KI-Bildgenerator', ru:'AI-генератор изображений', zh:'AI 图像生成器', hi:'AI इमेज जनरेटर', id:'Generator Gambar AI', ur:'AI امیج جنریٹر', ja:'AI画像生成', pt:'Gerador de Imagens com IA', it:'Generatore di immagini AI', ko:'AI 이미지 생성기', nl:'AI-afbeeldingengenerator', pl:'Generator obrazów AI', tr:'AI görsel oluşturucu', vi:'Trình tạo hình ảnh AI', th:'เครื่องมือสร้างภาพ AI', sv:'AI-bildgenerator' }),
  'word-character-counter': Object.freeze({ en:'Word & Character Counter', ar:'عدّاد الكلمات والأحرف', es:'Contador de palabras y caracteres', fr:'Compteur de mots et de caractères', de:'Wort- und Zeichenzähler', ru:'Счётчик слов и символов', zh:'字数与字符计数器', hi:'शब्द और कैरेक्टर काउंटर', id:'Penghitung Kata & Karakter', ur:'الفاظ اور حروف گننے والا', ja:'文字数・単語数カウンター', pt:'Contador de Palavras e Caracteres', it:'Contatore di parole e caratteri', ko:'단어 및 문자 수 카운터', nl:'Woorden- en tekenteller', pl:'Licznik słów i znaków', tr:'Kelime ve karakter sayacı', vi:'Đếm từ & ký tự', th:'ตัวนับคำและอักขระ', sv:'Ord- och teckenräknare' }),
  'text-diff-checker': Object.freeze({ en:'Text Diff Checker', ar:'مقارنة النصوص', es:'Comparador de texto', fr:'Comparateur de texte', de:'Text-Diff-Prüfer', ru:'Сравнение текста', zh:'文本差异检查器', hi:'टेक्स्ट डिफ चेकर', id:'Pemeriksa Perbedaan Teks', ur:'ٹیکسٹ ڈف چیکر', ja:'テキスト差分チェッカー', pt:'Comparador de Texto', it:'Confronto testo', ko:'텍스트 차이 검사기', nl:'Tekstverschilchecker', pl:'Porównywarka tekstu', tr:'Metin farkı denetleyici', vi:'Kiểm tra khác biệt văn bản', th:'ตรวจสอบความแตกต่างของข้อความ', sv:'Textdiffkontroll' }),
  'case-converter': Object.freeze({ en:'Case Converter', ar:'تحويل حالة الأحرف', es:'Convertidor de mayúsculas/minúsculas', fr:'Convertisseur de casse', de:'Groß-/Kleinschreibung konvertieren', ru:'Конвертер регистра', zh:'大小写转换器', hi:'केस कनवर्टर', id:'Konverter Huruf', ur:'حروف کیس کنورٹر', ja:'大文字・小文字変換', pt:'Conversor de Maiúsculas/Minúsculas', it:'Convertitore maiuscole/minuscole', ko:'대소문자 변환기', nl:'Hoofdletterconverter', pl:'Konwerter wielkości liter', tr:'Büyük/küçük harf dönüştürücü', vi:'Chuyển đổi chữ hoa/chữ thường', th:'ตัวแปลงตัวพิมพ์', sv:'Skiftlägeskonverterare' }),
  'qr-generator-reader': Object.freeze({ en:'QR Generator & Reader', ar:'مولد وقارئ QR', es:'Generador y lector QR', fr:'Générateur et lecteur QR', de:'QR-Generator und -Leser', ru:'Генератор и считыватель QR', zh:'二维码生成与读取', hi:'QR जनरेटर और रीडर', id:'Generator & Pembaca QR', ur:'QR جنریٹر اور ریڈر', ja:'QRコード生成・読み取り', pt:'Gerador e Leitor de QR', it:'Generatore e lettore QR', ko:'QR 생성기 및 리더', nl:'QR-generator en lezer', pl:'Generator i czytnik QR', tr:'QR oluşturucu ve okuyucu', vi:'Trình tạo & đọc QR', th:'เครื่องมือสร้างและอ่าน QR', sv:'QR-generator och läsare' }),
  'password-generator': Object.freeze({ en:'Password Generator', ar:'مولد كلمات المرور', es:'Generador de contraseñas', fr:'Générateur de mots de passe', de:'Passwortgenerator', ru:'Генератор паролей', zh:'密码生成器', hi:'पासवर्ड जनरेटर', id:'Generator Kata Sandi', ur:'پاس ورڈ جنریٹر', ja:'パスワード生成', pt:'Gerador de Senhas', it:'Generatore di password', ko:'비밀번호 생성기', nl:'Wachtwoordgenerator', pl:'Generator haseł', tr:'Şifre oluşturucu', vi:'Trình tạo mật khẩu', th:'เครื่องมือสร้างรหัสผ่าน', sv:'Lösenordsgenerator' }),
  'aspect-ratio-calculator': Object.freeze({ en:'Aspect Ratio Calculator', ar:'حاسبة نسبة العرض إلى الارتفاع', es:'Calculadora de relación de aspecto', fr:'Calculateur de ratio d’aspect', de:'Seitenverhältnis-Rechner', ru:'Калькулятор соотношения сторон', zh:'宽高比计算器', hi:'आस्पेक्ट रेशियो कैलकुलेटर', id:'Kalkulator Rasio Aspek', ur:'ایسپیکٹ ریشو کیلکولیٹر', ja:'アスペクト比計算', pt:'Calculadora de Proporção', it:'Calcolatore delle proporzioni', ko:'화면 비율 계산기', nl:'Beeldverhoudingscalculator', pl:'Kalkulator proporcji', tr:'En-boy oranı hesaplayıcı', vi:'Máy tính tỷ lệ khung hình', th:'เครื่องคำนวณอัตราส่วนภาพ', sv:'Bildförhållandekalkylator' }),
  'json-formatter-validator': Object.freeze({ en:'JSON Formatter & Validator', ar:'منسق ومحقق JSON', es:'Formateador y validador JSON', fr:'Formateur et validateur JSON', de:'JSON-Formatierer und Validator', ru:'Форматтер и валидатор JSON', zh:'JSON 格式化与验证', hi:'JSON फॉर्मेटर और वैलिडेटर', id:'Formatter & Validator JSON', ur:'JSON فارمیٹر اور ویلیڈیٹر', ja:'JSON整形・検証', pt:'Formatador e Validador JSON', it:'Formattatore e validatore JSON', ko:'JSON 포맷터 및 검증기', nl:'JSON-formatter en validator', pl:'Formater i walidator JSON', tr:'JSON biçimlendirici ve doğrulayıcı', vi:'Định dạng & xác thực JSON', th:'ตัวจัดรูปแบบและตรวจสอบ JSON', sv:'JSON-formaterare och validator' }),
  'base64-encoder-decoder': Object.freeze({ en:'Base64 Encoder & Decoder', ar:'ترميز وفك ترميز Base64', es:'Codificador y decodificador Base64', fr:'Encodeur et décodeur Base64', de:'Base64-Encoder und Decoder', ru:'Кодировщик и декодировщик Base64', zh:'Base64 编码与解码', hi:'Base64 एन्कोडर और डिकोडर', id:'Encoder & Decoder Base64', ur:'Base64 انکوڈر اور ڈیکوڈر', ja:'Base64エンコーダー・デコーダー', pt:'Codificador e Decodificador Base64', it:'Encoder e decoder Base64', ko:'Base64 인코더 및 디코더', nl:'Base64-encoder en decoder', pl:'Koder i dekoder Base64', tr:'Base64 kodlayıcı ve kod çözücü', vi:'Mã hóa & giải mã Base64', th:'ตัวเข้ารหัสและถอดรหัส Base64', sv:'Base64-kodare och avkodare' }),
  'color-picker-palette': Object.freeze({ en:'Color Picker & Palette', ar:'منتقي الألوان ولوحة الألوان', es:'Selector de color y paleta', fr:'Pipette et palette de couleurs', de:'Farbwähler und Palette', ru:'Выбор цвета и палитра', zh:'取色器与调色板', hi:'कलर पिकर और पैलेट', id:'Pemilih Warna & Palet', ur:'کلر پکڑنے والا اور پیلیٹ', ja:'カラーピッカー・パレット', pt:'Seletor de Cores e Paleta', it:'Selettore colori e tavolozza', ko:'색상 선택기 및 팔레트', nl:'Kleurkiezer en palet', pl:'Próbnik kolorów i paleta', tr:'Renk seçici ve palet', vi:'Chọn màu & bảng màu', th:'เครื่องมือเลือกสีและพาเลต', sv:'Färgväljare och palett' }),
  'regex-tester': Object.freeze({ en:'Regex Tester', ar:'اختبار Regex', es:'Probador de Regex', fr:'Testeur de Regex', de:'Regex-Tester', ru:'Тестер Regex', zh:'正则表达式测试器', hi:'Regex टेस्टर', id:'Penguji Regex', ur:'Regex ٹیسٹر', ja:'正規表現テスター', pt:'Testador de Regex', it:'Tester Regex', ko:'정규식 테스터', nl:'Regex-tester', pl:'Tester Regex', tr:'Regex test edici', vi:'Trình kiểm tra Regex', th:'เครื่องมือทดสอบ Regex', sv:'Regex-testare' }),
  'hash-generator': Object.freeze({ en:'Hash Generator', ar:'مولد الهاش', es:'Generador de hashes', fr:'Générateur de hash', de:'Hash-Generator', ru:'Генератор хешей', zh:'哈希生成器', hi:'हैश जनरेटर', id:'Generator Hash', ur:'ہیش جنریٹر', ja:'ハッシュ生成', pt:'Gerador de Hash', it:'Generatore di hash', ko:'해시 생성기', nl:'Hashgenerator', pl:'Generator hashy', tr:'Hash oluşturucu', vi:'Trình tạo hash', th:'เครื่องมือสร้างแฮช', sv:'Hashgenerator' }),
});

export function localizeMsUkToolTitle(locale: Locale, title: string): string {
  if (locale === 'ms') return `Alat ${title}`;
  if (locale === 'uk') return `Інструмент ${title}`;
  return title;
}

export function getToolSeoName(toolId: string, locale: Locale): string | undefined {
  const entry = TOOL_SEO_NAMES[toolId];
  if (!entry) return undefined;
  return entry[locale] ?? undefined;
}

export const TOOL_SEO_LOCALIZATION_LOCALES = LOCALES;
