import type { KnownLocale, Locale } from './config';

export const CATEGORY_LABELS: Record<Locale, Record<'Images' | 'AI' | 'Other', string>> = {
  ar: { Images: 'الصور', AI: 'الذكاء الاصطناعي', Other: 'أخرى' }, en: { Images: 'Images', AI: 'AI', Other: 'Other' }, es: { Images: 'Imágenes', AI: 'IA', Other: 'Otros' }, fr: { Images: 'Images', AI: 'IA', Other: 'Autres' }, de: { Images: 'Bilder', AI: 'KI', Other: 'Andere' }, hi: { Images: 'छवियाँ', AI: 'एआई', Other: 'अन्य' }, id: { Images: 'Gambar', AI: 'AI', Other: 'Lainnya' }, it: { Images: 'Immagini', AI: 'IA', Other: 'Altro' }, ja: { Images: '画像', AI: 'AI', Other: 'その他' }, ko: { Images: '이미지', AI: 'AI', Other: '기타' }, ms: { Images: 'Imej', AI: 'AI', Other: 'Lain-lain' }, nl: { Images: 'Afbeeldingen', AI: 'AI', Other: 'Overig' }, pl: { Images: 'Obrazy', AI: 'AI', Other: 'Inne' }, pt: { Images: 'Imagens', AI: 'IA', Other: 'Outros' }, ru: { Images: 'Изображения', AI: 'ИИ', Other: 'Другое' }, sv: { Images: 'Bilder', AI: 'AI', Other: 'Övrigt' }, th: { Images: 'รูปภาพ', AI: 'AI', Other: 'อื่นๆ' }, tr: { Images: 'Görseller', AI: 'YZ', Other: 'Diğer' }, uk: { Images: 'Зображення', AI: 'ШІ', Other: 'Інше' }, vi: { Images: 'Hình ảnh', AI: 'AI', Other: 'Khác' },
};

type LocalizedTerms = Partial<Record<KnownLocale, string>>;
const TERMS: Record<string, LocalizedTerms> = {
  image: { ar: 'صورة', es: 'Imagen', fr: 'Image', de: 'Bild', ru: 'Изображение', zh: '图像', hi: 'छवि', id: 'Gambar', ur: 'تصویر', ja: '画像', pt: 'Imagem', it: 'Immagine', ko: '이미지', nl: 'Afbeelding', pl: 'Obraz', tr: 'Görsel', vi: 'Hình ảnh', th: 'รูปภาพ', sv: 'Bild', ms: 'Imej', uk: 'Зображення' },
  images: { ar: 'الصور', es: 'Imágenes', fr: 'Images', de: 'Bilder', ru: 'Изображения', zh: '图像', hi: 'छवियाँ', id: 'Gambar', ur: 'تصاویر', ja: '画像', pt: 'Imagens', it: 'Immagini', ko: '이미지', nl: 'Afbeeldingen', pl: 'Obrazy', tr: 'Görseller', vi: 'Hình ảnh', th: 'รูปภาพ', sv: 'Bilder', ms: 'Imej', uk: 'Зображення' },
  photo: { ar: 'صورة', es: 'Foto', fr: 'Photo', de: 'Foto', ru: 'Фото', zh: '照片', hi: 'फ़ोटो', id: 'Foto', ur: 'تصویر', ja: '写真', pt: 'Foto', it: 'Foto', ko: '사진', nl: 'Foto', pl: 'Zdjęcie', tr: 'Fotoğraf', vi: 'Ảnh', th: 'ภาพถ่าย', sv: 'Foto', ms: 'Foto', uk: 'Фото' },
  background: { ar: 'الخلفية', es: 'Fondo', fr: 'Arrière-plan', de: 'Hintergrund', ru: 'Фон', zh: '背景', hi: 'पृष्ठभूमि', id: 'Latar belakang', ur: 'پس منظر', ja: '背景', pt: 'Fundo', it: 'Sfondo', ko: '배경', nl: 'Achtergrond', pl: 'Tło', tr: 'Arka plan', vi: 'Nền', th: 'พื้นหลัง', sv: 'Bakgrund', ms: 'Latar belakang', uk: 'Фон' },
  blur: { ar: 'ضبابية', es: 'Desenfoque', fr: 'Flou', de: 'Weichzeichnen', ru: 'Размытие', zh: '模糊', hi: 'धुंधलापन', id: 'Buram', ur: 'دھندلا', ja: 'ぼかش', pt: 'Desfoque', it: 'Sfocatura', ko: '흐림', nl: 'Vervagen', pl: 'Rozmycie', tr: 'Bulanıklaştırma', vi: 'Làm mờ', th: 'เบลอ', sv: 'Oskärpa', ms: 'Kabur', uk: 'Розмиття' },
  remove: { ar: 'إزالة', es: 'Eliminar', fr: 'Supprimer', de: 'Entfernen', ru: 'Удаление', zh: '移除', hi: 'हटाना', id: 'Hapus', ur: 'ہٹانا', ja: '削除', pt: 'Remover', it: 'Rimuovi', ko: '제거', nl: 'Verwijderen', pl: 'Usuwanie', tr: 'Kaldırma', vi: 'Xóa', th: 'ลบ', sv: 'Ta bort', ms: 'Buang', uk: 'Видалення' },
  remover: { ar: 'إزالة', es: 'Eliminador', fr: 'Suppression', de: 'Hinterferer', ru: 'Удаление', zh: '移除器', hi: 'हटाने वाला', id: 'Penghapus', ur: 'ہٹانے والا', ja: '削除', pt: 'Removedor', it: 'Rimozione', ko: '제거기', nl: 'Verwijderaar', pl: 'Usuwanie', tr: 'Kaldırıcı', vi: 'Công cụ xóa', th: 'ตัวลบ', sv: 'Borttagning', ms: 'Penyingkir', uk: 'Засіб видалення' },
  compressor: { ar: 'ضاغط', es: 'Compresor', fr: 'Compresseur', de: 'Kompressor', ru: 'Компрессор', zh: '压缩器', hi: 'कंप्रेसर', id: 'Kompresor', ur: 'کمپریسر', ja: '圧縮', pt: 'Compressor', it: 'Compressore', ko: '압축기', nl: 'Compressor', pl: 'Kompresor', tr: 'Sıkıştırıcı', vi: 'Trình nén', th: 'ตัวบีบอัด', sv: 'Kompressor', ms: 'Pemampat', uk: 'Компресор' },
  converter: { ar: 'محول', es: 'Convertidor', fr: 'Convertisseur', de: 'Konverter', ru: 'Конвертер', zh: '转换器', hi: 'कनवर्टर', id: 'Konverter', ur: 'کنورٹر', ja: '変換', pt: 'Conversor', it: 'Convertitore', ko: '변환기', nl: 'Converter', pl: 'Konwerter', tr: 'Dönüştürücü', vi: 'Trình chuyển đổi', th: 'ตัวแปลง', sv: 'Konverterare', ms: 'Penukar', uk: 'Конвертер' },
  cutter: { ar: 'قاصّ', es: 'Cortador', fr: 'Découpeur', de: 'Schneider', ru: 'Обрезчик', zh: '剪辑器', hi: 'कटर', id: 'Pemotong', ur: 'کٹّر', ja: 'カッター', pt: 'Cortador', it: 'Taglierina', ko: '커터', nl: 'Snijder', pl: 'Przycinarka', tr: 'Kesici', vi: 'Trình cắt', th: 'ตัวตัด', sv: 'Klippen', ms: 'Pemotong', uk: 'Обрізувач' },
  trimmer: { ar: 'مُشذِّب', es: 'Recortador', fr: 'Découpeur', de: 'Trimmer', ru: 'Триммер', zh: '修剪器', hi: 'ट्रिमर', id: 'Pemangkas', ur: 'ٹرمر', ja: 'トリマー', pt: 'Cortador', it: 'Ritagliatore', ko: '트리머', nl: 'Trimmer', pl: 'Trymer', tr: 'Kırpıcı', vi: 'Trình cắt', th: 'ตัวตัด', sv: 'Trimverktyg', ms: 'Pemangkas', uk: 'Тример' },
  generator: { ar: 'مولد', es: 'Generador', fr: 'Générateur', de: 'Generator', ru: 'Генератор', zh: '生成器', hi: 'जनरेटर', id: 'Generator', ur: 'جنریٹر', ja: '生成器', pt: 'Gerador', it: 'Generatore', ko: '생성기', nl: 'Generator', pl: 'Generator', tr: 'Oluşturucu', vi: 'Trình tạo', th: 'ตัวสร้าง', sv: 'Generator', ms: 'Penjana', uk: 'Генератор' },
  maker: { ar: 'منشئ', es: 'Creador', fr: 'Créateur', de: 'Ersteller', ru: 'Создатель', zh: '制作器', hi: 'निर्माता', id: 'Pembuat', ur: 'بنانے والا', ja: '作成', pt: 'Criador', it: 'Creatore', ko: '메이커', nl: 'Maker', pl: 'Twórca', tr: 'Oluşturucu', vi: 'Trình tạo', th: 'ตัวสร้าง', sv: 'Skapare', ms: 'Pembuat', uk: 'Створювач' },
  optimizer: { ar: 'محسن', es: 'Optimizador', fr: 'Optimiseur', de: 'Optimierer', ru: 'Оптимизатор', zh: '优化器', hi: 'ऑप्टिमाइज़र', id: 'Pengoptimal', ur: 'بہتر ساز', ja: '最適化', pt: 'Otimizador', it: 'Ottimizzatore', ko: '최적화기', nl: 'Optimalisator', pl: 'Optymalizator', tr: 'İyileştirici', vi: 'Trình tối ưu', th: 'ตัวเพิ่มประสิทธิภาพ', sv: 'Optimerare', ms: 'Pengoptimum', uk: 'Оптимізатор' },
  upscaler: { ar: 'مكبّر', es: 'Ampliador', fr: 'Agrandisseur', de: 'Hochskalierer', ru: 'Масштабировщик', zh: '放大器', hi: 'अपस्केलर', id: 'Peningkat resolusi', ur: 'ریزولوشن بڑھانے والا', ja: '高画質化', pt: 'Ampliador', it: 'Ingranditore', ko: '업스케일러', nl: 'Upscaler', pl: 'Skalowanie', tr: 'Büyütücü', vi: 'Tăng độ phân giải', th: 'เพิ่มความละเอียด', sv: 'Uppskalare', ms: 'Penskala', uk: 'Масштабувальник' },
  watermark: { ar: 'علامة مائية', es: 'Marca de agua', fr: 'Filigrane', de: 'Wasserzeichen', ru: 'Водяной знак', zh: '水印', hi: 'वॉटरमार्क', id: 'Tanda air', ur: 'واٹر مارک', ja: '透かし', pt: 'Marca d’água', it: 'Filigrana', ko: '워터마크', nl: 'Watermerk', pl: 'Znak wodny', tr: 'Filigran', vi: 'Hình mờ', th: 'ลายน้ำ', sv: 'Vattenstämpel', ms: 'Tanda air', uk: 'Водяний знак' },
  object: { ar: 'عنصر', es: 'Objeto', fr: 'Objet', de: 'Objekt', ru: 'Объект', zh: '对象', hi: 'वस्तु', id: 'Objek', ur: 'آبجیکٹ', ja: 'オブジェクト', pt: 'Objeto', it: 'Oggetto', ko: '개체', nl: 'Object', pl: 'Obiekt', tr: 'Nesne', vi: 'Đối tượng', th: 'วัตถุ', sv: 'Objekt', ms: 'Objek', uk: 'Об’єкт' },
  text: { ar: 'النص', es: 'Texto', fr: 'Texte', de: 'Text', ru: 'Текст', zh: '文本', ur: 'متن', hi: 'टेक्स्ट', id: 'Teks', ja: 'テキスト', pt: 'Texto', it: 'Testo', ko: '텍스트', nl: 'Tekst', pl: 'Tekst', tr: 'Metin', vi: 'Văn bản', th: 'ข้อความ', sv: 'Text', ms: 'Teks', uk: 'Текст' },
  audio: { ar: 'الصوت', es: 'Audio', fr: 'Audio', de: 'Audio', ru: 'Аудио', zh: '音频', ur: 'آڈیو', hi: 'ऑडियो', id: 'Audio', ja: '音声', pt: 'Áudio', it: 'Audio', ko: '오디오', nl: 'Audio', pl: 'Audio', tr: 'Ses', vi: 'Âm thanh', th: 'เสียง', sv: 'Ljud', ms: 'Audio', uk: 'Аудіо' },
  video: { ar: 'الفيديو', es: 'Vídeo', fr: 'Vidéo', de: 'Video', ru: 'Видео', zh: '视频', ur: 'ویڈیو', hi: 'वीडियो', id: 'Video', ja: '動画', pt: 'Vídeo', it: 'Video', ko: '비디오', nl: 'Video', pl: 'Wideo', tr: 'Video', vi: 'Video', th: 'วิดีโอ', sv: 'Video', ms: 'Video', uk: 'Відео' },
  pdf: { ar: 'PDF', en: 'PDF', es: 'PDF', fr: 'PDF', de: 'PDF', hi: 'PDF', id: 'PDF', it: 'PDF', ja: 'PDF', ko: 'PDF', ms: 'PDF', nl: 'PDF', pl: 'PDF', pt: 'PDF', ru: 'PDF', sv: 'PDF', th: 'PDF', tr: 'PDF', uk: 'PDF', vi: 'PDF', zh: 'PDF', ur: 'PDF' },
  ai: { ar: 'الذكاء الاصطناعي', en: 'AI', es: 'IA', fr: 'IA', de: 'KI', hi: 'एआई', id: 'AI', it: 'IA', ja: 'AI', ko: 'AI', ms: 'AI', nl: 'AI', pl: 'AI', pt: 'IA', ru: 'ИИ', sv: 'AI', th: 'AI', tr: 'YZ', uk: 'ШІ', vi: 'AI', zh: '人工智能', ur: 'اے آئی' },
};

export const getLocalizedTerm = (token: string, locale: Locale): string => TERMS[token]?.[locale] ?? token;

export function localizedToolName(toolId: string, locale: Locale): string {
  return toolId
    .split('-')
    .map((token) => getLocalizedTerm(token, locale))
    .join(' ');
}
