#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { spawn, spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT=process.cwd(), OUT=resolve(ROOT,'diagnostics/ci'); mkdirSync(OUT,{recursive:true});
const args=process.argv.slice(2), requested=args.find(a=>a.startsWith('--gate='))?.slice(7)??null, mode=args.find(a=>a.startsWith('--mode='))?.slice(7)??'certification';
const PLAN_PATH=resolve(ROOT,'scripts/ci/test-plan.json'), plan=JSON.parse(readFileSync(PLAN_PATH,'utf8')); const gates=['static','build','browser'];
if(!['certification','diagnose'].includes(mode)||(requested&&!gates.includes(requested)))process.exit(2);
const planSha=createHash('sha256').update(readFileSync(PLAN_PATH)).digest('hex'); const max=Number(plan.execution?.maxConcurrency??1);
if(!Number.isInteger(max)||max<1||max>32)process.exit(2);
const now=()=>new Date().toISOString();
const git=(a)=>{const r=spawnSync('git',a,{encoding:'utf8'});if(r.status!==0)throw new Error(String(r.stderr||'git command failed').trim());return r};
const exec=(check)=>new Promise(resolveResult=>{const started=now();const child=spawn(check.command,check.args??[],{cwd:ROOT,env:process.env,stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout.on('data',d=>{const s=d.toString();out+=s;process.stdout.write(s)});child.stderr.on('data',d=>{const s=d.toString();err+=s;process.stderr.write(s)});child.on('error',e=>resolveResult({...check,status:'FAIL',exitCode:1,startedAt:started,completedAt:now(),output:`${out}\n${err}\n${e.message}`.slice(-24000)}));child.on('close',(code,signal)=>resolveResult({...check,status:code===0?'PASS':'FAIL',exitCode:code??1,signal:signal??null,startedAt:started,completedAt:now(),output:`${out}\n${err}`.slice(-24000)}));});
const rootFor=(gate,check)=>{if(check.status==='PASS')return null;const o=check.output??'';const lines=o.split(/\r?\n/), marker='RUNTIME_EVIDENCE=', hit=lines.filter(l=>l.includes(marker)).at(-1);if(hit){try{const e=JSON.parse(hit.slice(hit.indexOf(marker)+marker.length));if((e.pageErrors?.length??0)||(e.consoleErrors?.length??0))return 'RC-RUNTIME-001';if((e.requestFailures?.length??0)||(e.failedResponses?.length??0))return 'RC-NETWORK-001';}catch{}}if(/npm ci|lockfile|package-lock|ERESOLVE|Missing: @rollup/i.test(o))return 'RC-DEPENDENCY-001';if(/TS\d+|not assignable|cannot find name/i.test(o))return 'RC-TYPE-001';if(/canonical|hreflang|sitemap|seo/i.test(o))return 'RC-SEO-001';if(/locale|translation|language|localized/i.test(o))return 'RC-I18N-001';if(/build failed|vite.*error|rollup|esbuild/i.test(o))return 'RC-BUILD-001';return gate==='browser'?'RC-BROWSER-001':'RC-UNKNOWN-001';};
async function runGate(name){const checks=(plan.gates?.[name]?.checks??[]);const expected=Number(plan.gates?.[name]?.expected??checks.length);const results=[];for(let i=0;i<checks.length;i+=max){const batch=checks.slice(i,i+max);const done=await Promise.all(batch.map(c=>exec({...c,gate:name})));for(const r of done){r.rootCauseId=rootFor(name,r);if(r.status==='FAIL')r.fingerprint=`FPR-${createHash('sha256').update([r.rootCauseId,r.gate,r.label,(r.output??'').replace(/\s+/g,' ').slice(-4000)].join('\n')).digest('hex').slice(0,12).toUpperCase()}`;else r.fingerprint=null;results.push(r)}}const failed=results.filter(r=>r.status==='FAIL');const report={version:7,schema:'flixo-gate-report/v7',sha:git(['rev-parse','HEAD']).stdout.trim(),gate:name.toUpperCase(),mode,status:failed.length===0&&results.length===expected?'PASS':'FAIL',failures:failed.length,checksExpected:expected,checksExecuted:results.length,rootCauses:[...new Set(failed.map(r=>r.rootCauseId).filter(Boolean))],coverage:[...new Set(results.flatMap(r=>r.coverage??[]))],assertions:[...new Set(results.flatMap(r=>r.assertions??[]))],completedAt:now(),checks:results};writeFileSync(resolve(OUT,`${name}.json`),`${JSON.stringify(report,null,2)}\n`);return report;}
const targets=requested?[requested]:gates,reports=[];for(const g of targets){if(reports.length&&reports.at(-1).status!=='PASS')break;reports.push(await runGate(g));}
const sha=git(['rev-parse','HEAD']).stdout.trim();const failures=reports.flatMap(r=>r.checks.filter(c=>c.status==='FAIL'));const expected=targets.reduce((n,g)=>n+Number(plan.gates?.[g]?.expected??0),0),executed=reports.reduce((n,r)=>n+r.checksExecuted,0);const allPass=reports.length===targets.length&&reports.every(r=>r.status==='PASS')&&executed===expected;
const canonical={version:7,schema:'flixo-ci-report/v5',mode,sha,testPlanSha256:planSha,status:allPass&&targets.length===gates.length?'PASS':'FAIL',gatesExpected:gates.length,gatesExecuted:reports.length,checksExpected:gates.reduce((n,g)=>n+Number(plan.gates?.[g]?.expected??0),0),checksExecuted:executed,rootCauses:[...new Set(failures.map(f=>f.rootCauseId).filter(Boolean))],assertions:{duplicateAssertions:[],uncoveredAssertions:[]},coverage:{},matrix:{maxConcurrency:max,gateDependencies:plan.gateDependencies??{}},reports};
writeFileSync(resolve(OUT,'canonical-result.json'),`${JSON.stringify(canonical,null,2)}\n`);writeFileSync(resolve(OUT,'report.json'),`${JSON.stringify(canonical,null,2)}\n`);console.log(`CANONICAL_STATUS=${canonical.status}`);console.log(`CANONICAL_SHA=${sha}`);if(canonical.status!=='PASS')process.exitCode=1;